### ISSUE TITLE
[Enhancement]: Link an email address automatically while composing a ticket

### ISSUE THREAD

**Issue by tanjiralmamun** [freescout-help-desk/freescout#4008]
While composing a ticket, it often becomes necessary to share an email address. Although an email is linked after sending a ticket, it would be better if an email address could be linked automatically while composing a ticket.

**Screenshot:** https://snipboard.io/EnBpOG.jpg

**Comment by freescout-helpdesk** [comment]
We'd appreciate a pull request.

**Comment by freescout-help** [comment]
It looks like no-one is going to implement this.
