### ISSUE TITLE
Triggering Workflow on Status "Closed" with action "Reply to Conversation" prevents "Send & Close" Replies from being Sent

### ISSUE THREAD

**Issue by JulianHn** [freescout-help-desk/freescout#4054]
Dear Freescout team,

we are in the process of implementing a new ticket system based on Freescout and so far we're really happy with it :)
To notify our customers of closed tickets, we created a workflow with condition "Status" -> "is equal to" -> "Closed" and Action "Reply to conversation", which should automatically mail our customers upon closing a ticket.
The workflow works very well, i.e. it gets triggered no matter in which way we close the ticket (Manual Close over button on top of ticket menu, e-mail command, setting the status to closed before replying, using the Send&Close functionality).

However, when we reply to a ticket and change its status to closed within the reply (or use the Send&Close functionality), only the workflow E-Mail gets sent, not the reply written by one of our support agents. This is also reflected when clicking on the expand arrow on the right side of this reply and checking the "Outgoing Emails" menu item, which says "There were no send attempts yet".
It would be crucial for us that it is possible to both send the agent reply as well as the automatic notification from the workflow triggered by closing the ticket.

// Julian

PHP version:  8.2.19
FreeScout version: 1.8.140 
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
We've checked it on our end - the customer receives an email containing both Workflow's reply and support agent's reply.
