### ISSUE TITLE
Workflows not working

### ISSUE THREAD

**Issue by MarianBMI** [freescout-help-desk/freescout#4058]
Hello, 
We did a fresh install a couple of weeks ago, trying to migrate from helpscout to freescout.
We copied all the workflows that we've been having in freescout (reproduces in freescout) but apparently the ones related to time are not triggering. Ones with "waiting since" or "last customer/user reply" and so on.
Here's an example which should've been triggered but it never happened:
![image](https://github.com/freescout-helpdesk/freescout/assets/171936408/38b9a86c-e639-420c-ae30-bd55043bdb51)
![image](https://github.com/freescout-helpdesk/freescout/assets/171936408/58f150d5-bb48-47f0-84cb-838e0a0fabcf)

This TT should've met the criteria.
![image](https://github.com/freescout-helpdesk/freescout/assets/171936408/4ac1c5a0-ff91-4d55-a83a-542f160e7a78)

I have other 10-12 similar workflows that are in the same situation, not triggering at all.

I tried various fixes from other threads like applies to previous and saving again or cron job configurations like specified in the troubleshooting of the module. 
I have no other idea what to do. Please advise.

-->

PHP version: PHP 8.0.30
FreeScout version:  1.8.141    
Database:  Mysql (10.6.16-MariaDB-0ubuntu0.22.04.1) 
Are you using CloudFlare:  No
Are you using non-official modules: No

**Comment by MarianBMI** [comment]
hi @freescout-helpdesk , could you please assist here ? It looks like no matter what conditions i'm adding, when it comes to time related ones, they aren't triggering...

**Comment by freescout-helpdesk** [comment]
All we can suggest is already written at the bottom of https://freescout.net/module/workflows/

**Comment by freescout-helpdesk** [comment]
The issue may be also related to your server configuration (like in [this case](https://github.com/freescout-helpdesk/freescout/issues/3761#issuecomment-1991575086)).

**Comment by MarianBMI** [comment]
Hello @freescout-helpdesk, we checked everything in both back and front end and nothing seems to be fixing this. Including the suggestions from the shared thread.
So it looks like all workflows with time-related conditions aren't triggering. All others are fine. 
Let me know what info you'd need in order to better understand the case and advice on how to fix this. 
Thanks a lot! Will be waiting eagerly.

**Comment by netlane** [comment]
Hi Marian, check #3840 - as far as I can see it, this issue has never been resolved

**Comment by freescout-help** [comment]
We can take a look at it on your server - email at support@freescout.net

**Comment by MarianBMI** [comment]
Hello. This has been fixed by the @freescout-help  team. Apparently the issue was in the code of the module. 
Workflows are working fine now.
Thank you!

**Comment by MarianBMI** [comment]
Hello, I'd like to reopen this thread as I noticed not all workflows are working properly. The one presented in this subject is now working, but it's the only one working.
Apart from 24hrs, there are others for 48h, 3 days, 4,5 & 6 days which are not working and so on. Somehow, regardless of meeting the conditions, they don't trigger.
 
@freescout-help is there a chance to check this our again ?
