### ISSUE TITLE
How to fetch all messages, not just unseen/unread?

### ISSUE THREAD

**Issue by aaversa** [freescout-help-desk/freescout#4064]
I'm aware that you can manually select 'all' emails when manually fetching, however we're trying to diagnose an issue where some emails are randomly not fetched. My best guess is that these emails (in Google workspace) are being marked READ, and therefore not fetched by Freescout.

What I'd like to do is modify Freescout's cron fetch to get all emails, not just unread.

Is there an easy config option for this that I might be overlooking? Thanks in advance

EDIT: Related to this, if there is a fetch failure (for example, we use Google workspace, and occasionally we see something in the logs that the destination IMAP server timed out) will the failed fetch be retried automatically or is the failure skipped?

**Comment by mattly6** [comment]
Automatic fetching of read e-mails was introduced in release 1.8.131.
Failed jobs are automatically retried after some time.

**Comment by aaversa** [comment]
I am on 1.8.138 and that definitely did not happen. I am looking at a simple plaintext email sitting on the server that Freescout did not fetch.

**Comment by freescout-helpdesk** [comment]
To fetch read email you need to set `APP_FETCH_UNSEEN=1` in the .env file and clear cache.

**Comment by nicnab** [comment]
Just in case someone comes across this ticket like I did: for me, `APP_FETCH_UNSEEN=0 `(instead of 1) was the right entry!

**Comment by NeptunedGmbH** [comment]
since both settings don't work for me... I guess I'm doing something wrong. Im using the Docker Image. Where should I set it then?
