### ISSUE TITLE
Inline images do not display, but some inline image are displaying

### ISSUE THREAD

**Issue by SecteurA** [freescout-help-desk/freescout#4070]
Hello, 

I migrate FreeScout to new server, but we noticed that some images are not displaying in the tickets, when i go to the folder of that image i can see that it exist, note that i read many threads to find a solution, i didn't find some issue, as you can see attached the permissions are correct, nginx configuration is correct, i reinstalled the server 2 times, i import database and attachement folders, with same issue.

Thank you

<img width="535" alt="Capture d’écran 2024-06-12 à 05 09 17" src="https://github.com/freescout-helpdesk/freescout/assets/112476252/0d4a357e-93b4-40d9-abb6-07cef9e341c8">
<img width="589" alt="Capture d’écran 2024-06-12 à 05 09 05" src="https://github.com/freescout-helpdesk/freescout/assets/112476252/fb5fa4f3-f820-4b7e-85eb-ec0567e7c6f7">
<img width="501" alt="Capture d’écran 2024-06-12 à 05 08 50" src="https://github.com/freescout-helpdesk/freescout/assets/112476252/c420ff1c-4f67-473c-94fa-1ee6838eedde">

**Comment by freescout-helpdesk** [comment]
> when i go to the folder of that image i can see that it exist

On your screenshots only folders can be seen, not actual files. Most likely https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by SecteurA** [comment]
Here is one highlighted 
<img width="781" alt="Capture d’écran 2024-06-12 à 06 24 22" src="https://github.com/freescout-helpdesk/freescout/assets/112476252/49ea59df-b80d-4a69-8ceb-bffa8323d44d">

**Comment by SecteurA** [comment]
I have executed permissions-issue with no luck !

**Comment by freescout-help** [comment]
Try to debug it your self https://github.com/freescout-help-desk/freescout/wiki/Debugging or find someone who can do it.
