### ISSUE TITLE
Sending emails and Basich Auth (Office 365)

### ISSUE THREAD

**Issue by lucafabbri365** [freescout-help-desk/freescout#4072]
Hello,
I'm trying to configure the _Sending Emails_ under _Connection Settings_ with Office 365. 
As I understand by reading this article [Connect FreeScout to Microsoft 365 Exchange via OAuth](https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth), the SMTP AUTH must be enabled.
Now, with security changes made by Microsoft SMTP AUTH works with OAuth2; the Basic Authentication is deprecated/disabled. However the Sending Emails section seems to support Basic Auth. only (Username/Password). 

Isn't it ?

Thank you.

**Comment by freescout-helpdesk** [comment]
We can take a look what can be done but we'll need an access to some MS 365 account. If you can provide it please email at support@freescout.net

**Comment by freescout-helpdesk** [comment]
Or you can test changes we've just pushed to the master branch.

SMTP via oAuth is configured similar to Fetching: https://github.com/freescout-helpdesk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth#fetching-emails

**Comment by lucafabbri365** [comment]
Hello @freescout-helpdesk,
using the same method (oAuth) used for fetching emails sound good.
I'll test the change and give you feedback...

**Comment by freescout-helpdesk** [comment]
Small clarification - same Microsoft Exchange app is used for sending emails as for fetching, you don't need to create two apps in your Microsoft Exchange.

**Comment by lucafabbri365** [comment]
Hello @

> Small clarification - same Microsoft Exchange app is used for sending emails and for fetching, you don't need to create two apps in your Microsoft Exchange.

Got it.

**Comment by freescout-helpdesk** [comment]
Does it work for you?

**Comment by lucafabbri365** [comment]
Hello @freescout-helpdesk,
I'm waiting for the guy who is managing Freescout. I'll let you know asap.
