### ISSUE TITLE
Updating modules from CLI

### ISSUE THREAD

**Issue by kluvi** [freescout-help-desk/freescout#4074]
When updating modules in CLI using command `php artisan freescout:module-update `, Deactivated modules wont update, instead it just outputs `All modules are up-to-date`.

When the button "Update Now" in UI (Manage > Modules), it updates even deactivated modules.

The artisan command should either update disabled modules as well, or have an argument for the ability to update disabled modules as well.

PHP version: 8.2.16
FreeScout version: 1.8.143
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
