### ISSUE TITLE
Freescout 1.8.143 Problem Fetching Emails on MS365

### ISSUE THREAD

**Issue by jimmie-jam** [freescout-help-desk/freescout#4076]
I just set up an Ubuntu Server 22.04 with Freescout 1.8.143 and have everything working except Fetching Emails. 

I am using an Outlook365 distribution group for outgoing and incoming (fetch). The outgoing works like a charm, but fetching messages fails with:
Error: connection setup failed; File: /www/html/vendor/webklex/php-imap/src/Client.php (391)

I also tried my own email address (still in Outlook365), and my personal Gmail address and get the same error. I do have IMAP enabled for my O365 accounts, so that is not the issue, and my O365 address can Send As the distribution group address I'm using for incoming and outgoing messages, so that should not be an issue. 

I'm stuck.

If my Gmail account worked, I would suspect the O365 account setup, but since neither were able to fetch messages, I think it's the FreeScout config. 

Any thoughts?

Thanks!

**Comment by freescout-help** [comment]
Check if IMAP ports are open on your server.

**Comment by freescout-help** [comment]
We'll close this in favor of https://github.com/freescout-helpdesk/freescout/issues/4002

**Comment by jimmie-jam** [comment]
Great thought, I tried allowing the IMAP port through the firewall, but to no avail. Any other suggestions?

Jamie Richter
Director of Information Technology
Eagle Specialty Products
1 Lincoln Way
St. Louis, MO 63120
888-241-9802
espinc.us


[eagle-logo-revision.png]

On Jun 16, 2024, at 4:29 AM, freescout-help ***@***.***> wrote:



Closed #4076<https://github.com/freescout-helpdesk/freescout/issues/4076> as completed.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/issues/4079#issuecomment-2173991160

**Comment by jimmie-jam** [comment]
> [#4079 (comment)](https://github.com/freescout-help-desk/freescout/issues/4079#issuecomment-2173991160)

I looked into this and I think I understand the setup through the app, but I'm stumped on the redirect URL portion. I am hosting this on an ubuntu server that is only on my network, and only accessible via IP. I'm not going to use a reverse proxy, nor am I going to host it behind https. When I enter my web app credentials that I created in MS Entra, the URLs don't match because it's not hosted behind a ssl and I'm accessing it via http.  Can I still implement Freescout? I truly did the interface.

Thank you!

**Comment by freescout-help** [comment]
We'll leave it open for a while. Maybe someone will help.

**Comment by jimmie-jam** [comment]
> We'll leave it open for a while. Maybe someone will help.

Thanks much!

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

I NEVER Even signed up to most of these NEW Issue threads that are poping up.. so Why the HELL am I getting emails from this garbage?

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!
