### ISSUE TITLE
block ip with extra security module

### ISSUE THREAD

**Issue by GreenSmart01** [freescout-help-desk/freescout#4077]
Hi all,

I have enabled the extra security module; https://freescout.net/module/extra-security/

i have added a long time a go my external ip for loggin in to freescout.
i have an dedicated ip adres. and.. ofcourse last week the ISP provider needed to change this ip. 
so now al our logins are blocked. ip block.

so i followed the following;
If you can’t login as an Administrator because your IP is blocked – open /.env file, remove “EXTRASECURITY_IPS_ENABLED=…” line and [clear cache](https://github.com/freescout-helpdesk/freescout/wiki/Clearing-the-Cache).

this didnot the trick.
does anyome have more ideas to fix this issu :) ?
Thanks in advance

**Comment by freescout-help** [comment]
It should work if you properly clear cache.
Try to remove from .env file all parameters starting with `EXTRASECURITY_` and clear cache.

**Comment by GreenSmart01** [comment]
Thanks for the reply :)
i have removed all of the parameters still no luck.
but i was able to grain access to visit my parents i have added ther ip also in history :)
