### ISSUE TITLE
Forward/Reply Attachment issue

### ISSUE THREAD

**Issue by cryptid1x** [freescout-help-desk/freescout#4082]
Running into an issue when you forward and email in freescout it will create new tickets. If you forward an email to 4 users it will create 4 new tickets is there a way to stop this from happening, and maybe just update statues/notes in the original email.

When hitting reply back to email and replying back to the original user and/or adding more users to that email makes the attachment they receive unable to be open.

I am fairly new to freescout and am learning, so not sure if there is a simple fix for the 2 issues above or if I am doing something wrong. I appreciate any feedback I can get, thank you.

**Comment by sofl88** [comment]
First thing is more like a feature and it has quite some advantages especially when it comes to handle answers recipient-wise

**Comment by cryptid1x** [comment]
> First thing is more like a feature and it has quite some advantages especially when it comes to handle answers recipient-wise

Do you happen to know if they currently have a feature to accomplish this?

**Comment by freescout-help** [comment]
> > First thing is more like a feature and it has quite some advantages especially when it comes to handle answers recipient-wise
> 
> Do you happen to know if they currently have a feature to accomplish this?

Unfortunately not.

Regarding the another issue - please create a separate issue with screenshots, etc.
