### ISSUE TITLE
Tags no longer visible to users without edit permissions

### ISSUE THREAD

**Issue by jbadson** [freescout-help-desk/freescout#4083]
We recently updated the Tags module to 1.0.37, and noticed the "Tags" option no longer appears under the Manage menu unless the user is admin or has PERM_EDIT_TAGS.  I won't post the code publicly, but the changes occurred on lines 354-355 in Modules/Tags/Providers/TagsServiceProvider.php.  The /tags route is also no longer accessible for regular users.  

I'd just like to confirm if this is the intended result.  It doesn't seem to match the info on https://freescout.net/module/tags, and in our use case, support agents have previously been able to view the list of tags for their mailboxes, but only supervisors were able to edit or delete them.

We can revert the changes on our end, but I'd like to avoid customizing the module if possible, so I'd like to check if there is any plan to allow regular users to view the tags list again.

PHP version: 8.3.8
FreeScout version: 1.8.143
Database: MySQL / PostgreSQL: MariaDB 10.6.16
Are you using CloudFlare: No
Are you using non-official modules: Yes

**Comment by freescout-help** [comment]
It works as designed.
