### ISSUE TITLE
Issue with Time Tracking Module

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4086]
Hi @freescout-help @freescout-help-desk,

We have purchased the "Time Tracking" module, but it is not working as expected. We have enabled the following setting:

**"The timer starts when the user views the conversation, the timer pauses when the user navigates away from the conversation."**

This means it should log the time when anyone starts viewing the ticket, irrespective of to whom the ticket is assigned. However, it is only tracking time when the ticket is assigned to someone and that particular person is viewing the ticket.

We want to track the time of everyone who visits the ticket.

Below are my settings:

<img width="1031" alt="Screenshot 2024-06-21 at 9 51 29 AM" src="https://github.com/freescout-help-desk/freescout/assets/118246547/ee45ced1-7fe8-4613-b56c-bdf517efe2d1">

Thank You.

**Comment by freescout-help** [comment]
It works as designed.

Feel free to [submit a feature request](https://freescout.net/request-feature/) or adjust the module by yourself.

**Comment by mahavirn** [comment]
Hi @freescout-help 

So what this setting actually means?

Can you elaborate it please:

"The timer starts when the user views the conversation, the timer pauses when the user navigates away from the conversation."

**Comment by freescout-help** [comment]
"The timer starts when the assignee views the conversation..."

**Comment by mahavirn** [comment]
Can you guide me if there is some code i should change to make it available for all users instead of just "Assignee"

It would be really helpful.

Thanks!

**Comment by denmilos** [comment]
@freescout-help Then in the settings and in the module description it should be written that it is the designated user who opens the conversation, and not just any abstract user. I also fell for this message and misunderstood it. Because the description is misleading. It turns out I bought the module for nothing.

**Comment by freescout-help** [comment]
Confusing indeed. The wording of "Tracking Module" options has been changed.
