### ISSUE TITLE
Move to IMAP folder + Mark email as read not working anymore

### ISSUE THREAD

**Issue by proserver1** [freescout-help-desk/freescout#4088]
problem: Move to IMAP folder + Mark email as read not working anymore since severals versions

currently running:  	1.8.145  
logs: no errors logged
PHP version: PHP 8.2.18
Database: 10.11.6-MariaDB-0+deb12u1 Debian 12
Are you using CloudFlare:  No
Are you using non-official modules:  No
imap-server: courier-imapd (running in combination with freescout since years)

**Comment by freescout-help** [comment]
We've double checked it and it works fine.

Someone may need to investigate it on your server. Maybe it's related to the IMAP server you are using.

**Comment by proserver1** [comment]
probably, but imap server and freescout config kept unchanged. only freescout got updated regularly.
I am sorry I can't provide the exact version when it stopped working, just found out by accident (no one logs in to the acutal imap account with a "normal" client)

since I posted the report and cleaned the inbox, all new messages where proceeded by freescout but not moved anymore...

IMAP server logs dont show errors. login, logout from helpdesk. that's it.
tried with a changed folder. no success.

btw -> "mark read" is still working within the context "IMAP folder + Mark email as read"

**Comment by freescout-help** [comment]
> btw -> "mark read" is still working within the context "IMAP folder + Mark email as read"

So what does not work? Can you attach a screenshot?

**Comment by proserver1** [comment]
![Screenshot from 2024-06-21 19-18-35](https://github.com/freescout-help-desk/freescout/assets/5900693/830e5fec-4e02-4dd0-a1c9-94f2b15db0f9)

^ the function "after fetching - move to imap folder + mark read"

* "mark read" is done, but "move to imap folder" doesnt work anymore. processed emails stay in the INBOX
* e.g. "imap folder to save outgoing mails" works too.
* all of the settings are unchanged and the folders exist

**Comment by freescout-help** [comment]
It works fine on our end.

It here anything in laravel log in "Manage > Logs > App Logs"?

And here is the place to debug: /Modules/ImapMove/Providers/ImapMoveServiceProvider.php (line 64)
https://github.com/freescout-help-desk/freescout/wiki/Debugging

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

I NEVER Even signed up to most of these NEW Issue threads that are poping up.. so Why the HELL am I getting emails from this garbage?

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!

**Comment by proserver1** [comment]
notifications are a github feature that YOU configured. has nothing to do with freescout.
besides that your tone is inaccaptable. so stop ranting, be kind and helpfull or silent.

under EVERY notification of github there is a direct link to "unsubscribe" or you log into your github account and configure notifications accordingly.

**Comment by proserver1** [comment]
@freescout-help still not working but I just have no time to debug. I will send usefull debugging infos when time allows.
