### ISSUE TITLE
Issue with Cron failing

### ISSUE THREAD

**Issue by ThePrincelle** [freescout-help-desk/freescout#4089]
PHP version: 8.2.20
FreeScout version: 1.8.145
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

I'm having an issue with Cron and fetching emails, I'm getting the following errors : 

`production.ERROR: The process has been signaled with signal "15".`

```
[2024-06-21 09:40:07] production.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 7941024 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 7941024 bytes) at /www/html/overrides/webklex/php-imap/src/Structure.php:133)
[stacktrace]
#0 {main}
"}
```

Thanks in advance for your help.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#allowed-memory-size-of-nnn-bytes-exhausted-error-when-fetching-large-attachments

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

I NEVER Even signed up to most of these NEW Issue threads that are poping up.. so Why the HELL am I getting emails from this garbage?

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!
