### ISSUE TITLE
Why was Improve Delivery hidden?

### ISSUE THREAD

**Issue by CdrMarks** [freescout-help-desk/freescout#4092]
I noticed on https://freescout.net/ under the Screenshots, this screenshot can be seen.
![image](https://github.com/freescout-help-desk/freescout/assets/3489003/82ca5270-96db-4b14-aca0-14a833f85894)

Though when looking through the code, I found https://github.com/freescout-help-desk/freescout/commit/af57cd00208839482b98d9fe40bb843d157c02c4 which hides this part of the user interface. 

Does this functionality still work?
Was it moved out into a module?

**Comment by freescout-help** [comment]
It existed only in the template and has never been implemented. There is no plans to implement this thing.

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

I NEVER Even signed up to most of these NEW Issue threads that are poping up.. so Why the HELL am I getting emails from this garbage?

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!
