### ISSUE TITLE
FWD not working :(

### ISSUE THREAD

**Issue by elyazalee** [freescout-help-desk/freescout#4095]
Hello,

Whether I add the tag '@fwd' alone or with an email address right after, it doesn't work. Same when I remove my email address if it is present in the body of the email.

Source mail : 
`<div>@fwd <a href="mailto:ew@XXXXX.fr">ew@XXXXX.fr</a><br></div><div><div>Cordialement,<br></div><div><br></div></div><div><br></div><div><div>---------- Message transféré ---------<br></div><div>De : Eric XXXXX <ew@XXXXX.fr><br></div><div>Date : 2024-06-23T20:09:27.000+02:00<br></div><div>Sujet : Astrid<br></div><div class="ws-ng-mail-style--8207eJzz9HPyjwAABGYBgQ"><div class=""><p class="">`

PHP version: 8.1
FreeScout version: 1.8.145
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

Thanks,

Loïc.

**Comment by freescout-help** [comment]
The email should be a proper forwarded email. It should have `In-Reply-To` header set and have subject starting with "FWD:", "FW:" or "F:".

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!

**Comment by elyazalee** [comment]
Yes, that is indeed the case :

![Capture d'écran 2024-07-08 182413](https://github.com/freescout-help-desk/freescout/assets/6560933/3c673463-42d3-420c-8efd-5a14b137dd01)

**Comment by elyazalee** [comment]
Why did you close this thread? The bug still exists and I encounter it very frequently.

**Comment by elyazalee** [comment]
![image](https://github.com/freescout-help-desk/freescout/assets/6560933/164ce0b0-9ac6-47c1-8465-999a3c47aac0)

**Comment by freescout-help** [comment]
> The email should be a proper forwarded email. It should have `In-Reply-To` header set and have subject starting with "FWD:", "FW:" or "F:".

Apparently your email does not satisfy `In-Reply-To` header requirement. If you want to debug it, here is the place: https://github.com/freescout-help-desk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L691
