### ISSUE TITLE
Still reports IMAP

### ISSUE THREAD

**Issue by pnkr** [freescout-help-desk/freescout#4097]
At logs I get the error infinite times

(Mailboxname) Could not fetch specific message by Message-ID via IMAP: Error: Unterminated mailbox: account@mysite.gr; Unterminated mailbox: account@mysite.gr; Unterminated mailbox: helaccount@mysite.gr; Unterminated mailbox: account@mysite.gr; Unterminated mailbox: helaccount@mysite.gr; File: /var/www/virtuals/sites/tickets/vendor/webklex/php-imap/src/Connection/Protocols/LegacyProtocol.php (103)

The issue is that I have a POP3 mailbox set. Why it tries to do something with IMAP?

PHP version: 8.2
FreeScout version: 1.8.145 
Database: MariaDB
Are you using CloudFlare: Yes 
Are you using non-official modules:  No

**Comment by pnkr** [comment]
The issue is that I have a POP3 mailbox set. Why it tries to do something with IMAP?

**Comment by freescout-help** [comment]
The error message was same for IMAP and POP3. We've fixed the error message in the `master` branch.

But "Unterminated mailbox" error is apparently returned by your mail server:
https://stackoverflow.com/questions/67905112/why-is-php-imap-with-gmail-logging-a-bunch-of-nonsense-of-late
