### ISSUE TITLE
SMTP Authentication - Swift_TransportException

### ISSUE THREAD

**Issue by i-Blaise** [freescout-help-desk/freescout#4098]
Hello guys, hope you're well.

Sending and fetching emails works perfectly, however, when i click 'Send invite email' when creating a new user I am met with the following error

`<html>
<body>

sending invitation email to user | Failed to authenticate on SMTP server with username "support@myemail.com" using 1 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535-5.7.8 Username and Password not accepted. For more information, go to 535 5.7.8 https://support.google.com/mail/?p=BadCredentials a640c23a62f3a-a724cac7c48sm269941466b.220 - gsmtp " in /var/www/helpdesk/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457 Stack trace: #0
-- | --

</body>
</html>`

![issue1](https://github.com/freescout-help-desk/freescout/assets/21373591/ed7f05ec-ccea-4c69-8b16-8da1721be1e8)
![issue2](https://github.com/freescout-help-desk/freescout/assets/21373591/60a80103-5f3a-491b-b90e-0a915610f5b0)

What is quite confusing about this issue is that prior to getting these errors, the "Send Invite Email" worked. It was used to add two new users before the errors begun. Also, all other mailing activities (sending and receiving email) works just fine.

I have recreated an app password on google, but it still doesnt work.
I typed in the mailing credentials in .env file directly and even in config/mail.php file which didnt work.

Thank you in advance.

PHP version: 8.2
FreeScout version: 1.8.145
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules:  No

**Comment by freescout-help** [comment]
It's hard to tell what is the reason. It need to be debugged on the server.

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

I NEVER Even signed up to most of these NEW Issue threads that are poping up.. so Why the HELL am I getting emails from this garbage?

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!
