### ISSUE TITLE
imap-move module remove emails only after 3 days (feature request)

### ISSUE THREAD

**Issue by stsimb** [freescout-help-desk/freescout#4100]
Hello,

Would it be possible for the https://freescout.net/module/imap-move/ module to have another option, to keep the messages for 3 days (or configurable amount) on the server and remove them afterwards?

This would be in sync with freescout's default behaviour, that fetches 3 days worth of emails.
It would be safety net in case something goes wrong.
One could login to the imap server and mark some emails (or all) unread, to have freescout fetch it again.

Thanks,

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).
