### ISSUE TITLE
How to add custom conversation statuses to a project?

### ISSUE THREAD

**Issue by mihdan** [freescout-help-desk/freescout#4101]
Is there an easy way to add custom statuses for conversations without rewriting the Conversation model file. I haven't found the necessary filters.

In blade templates, the loop is created based on a static property of the `public static $statuses` class.

I can make a pull-request by adding the necessary hooks and methods.

**Comment by TheBrianGraf** [comment]
I came to ask how to change or add additional statuses as well. I just installed today and it's a clear miss for me with the default statuses

**Comment by TheBrianGraf** [comment]
It looks like they are listed in https://github.com/freescout-help-desk/freescout/tree/7c3e57aa57b47e6c5127575cdb2792f42da597db/app
/Thread.php
Line 72. I don't know enough PHP to feel confident adding others, but I do need more status options, and the KanBan board should support more as well IMO

**Comment by freescout-help** [comment]
There is no such feature for now. 
Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

I NEVER Even signed up to most of these NEW Issue threads that are poping up.. so Why the HELL am I getting emails from this garbage?

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!
