### ISSUE TITLE
Merge mailboxes

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-help-desk/freescout#4102]
Hello,

Is there any way to merge mailboxes into single one? The purpose is to move all conversations and threads from one mailbox to another and then delete the first mailbox.

Thanks!

**Comment by freescout-help** [comment]
There is no such feature for now. 
Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!

**Comment by ilyakonovalenko** [comment]
> So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!

Unstar the repo and change your settings. It was you, no one else can subscribe you to the repo.

> I tried and wished Freescout would and could have worked as promised..
By the way, it works as promised :-)
