### ISSUE TITLE
Kanban View Issue with opening couple tickets

### ISSUE THREAD

**Issue by cryptid1x** [freescout-help-desk/freescout#4104]
We receive about 75-100 emails in freescout.
And we are running into an issue in kanban view where we are unable to open/view some tickets.
We can open the same ticket with no issue in the mailbox. 

Tickets that won't open are the same as any other other ticket in freescout. Just contains a subject description and a pdf attachement.

Any help with this is appreciate.

**Comment by freescout-help** [comment]
> we are unable to open/view some tickets.

What do you mean? Cards are not clickable? Some videos or screenshots would be helpful.
