### ISSUE TITLE
Uploading profile image may fail on Windows

### ISSUE THREAD

**Issue by achikhv** [freescout-help-desk/freescout#4105]
PHP version:  8.3
FreeScout version: 1.8.145
Database: PostgreSQL
Are you using CloudFlare:  No
Are you using non-official modules: No

On Windows uploading profile image may fall under certain circumstances. There is [a bug (a feature?)](https://bugs.php.net/bug.php?id=74411) in PHP when `getRealPath` may fail if user does not have read access to any directory in the hierarchy. It is a default setup for PHP8. Temporary upload directory is set to `C:\Windows\Temp`, while IIS user cannot access `C:\` and `C:\Windows` directly, though uploaded file is eventually readable.

As a result uploading profile avatar results in error:

```
Whoops, looks like something went wrong — check logs in /storage/logs
```

Stacktrace is:
```
[2024-06-28 09:12:02] production.ERROR: Path cannot be empty {"userId":1,"email":"user@domain","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Path cannot be empty at D:\\Inetpub\\wwwroot\\helpdesc\\app\\Misc\\Helper.php:647)
[stacktrace]
#0 D:\\Inetpub\\wwwroot\\helpdesc\\app\\Misc\\Helper.php(647): getimagesize()
#1 D:\\Inetpub\\wwwroot\\helpdesc\\app\\User.php(880): App\\Misc\\Helper::resizeImage()
#2 D:\\Inetpub\\wwwroot\\helpdesc\\app\\Http\\Controllers\\UsersController.php(184): App\\User->savePhoto()
 (omitted for clarity)
"} 

```

I think it should be reasonable to fallback to `getPathname` if `getRealPath` returns false. Right now this case is not handled. This part of User's `savePhoto` method may look like this.

```php
if (!is_string($uploaded_file)) {
    $real_path = $uploaded_file->getRealPath();
    $mime_type = $uploaded_file->getMimeType();

     if (!$real_path) {
         $real_path = $uploaded_file->getPathname();
     
}
```

I can file a PR if it is OK.

**Comment by freescout-help** [comment]
Pull request would be appreciated.

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!
