### ISSUE TITLE
Attachment URL is malformed on Windows

### ISSUE THREAD

**Issue by achikhv** [freescout-help-desk/freescout#4106]
PHP version:  8.3
FreeScout version: 1.8.145
Database: PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules: No

On Windows attachments URL's shown in message body are malformed. `Attachment`'s function `getStorageFilePath` returns string with backslashes, that are later escaped to `%5C` in `url` function. So final attachment URL contains `%5C` instead of forward slashes. That results in 404 when trying to view attachment.

URL should contain only forward slashes, so it is reasonable to replace DIRECTORY_SEPARATORS returned by `getStorageFilePath` with forward slashes.

I propose to rewrite `Attachment`'s `url()` like this:

```php
public function url()
{
	$file_path = $this->getStorageFilePath();

	// URL must contain only forward slashes.
	$file_path = str_replace(DIRECTORY_SEPARATOR, '/', $file_path);

	$file_url = Storage::url($file_path);

	// Fix percents.
	// https://github.com/freescout-helpdesk/freescout/issues/3530
	$file_url = str_replace('%', '%25', $file_url);

	return $file_url.'?id='.$this->id.'&token='.$this->getToken();
}
```

I can file PR if it is OK.

**Comment by freescout-help** [comment]
Pull request would be appreaciated.

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!
