### ISSUE TITLE
[error] 631#631: *411 open() "/var/www/html/public/js/datatables/DataTables-1.10.18/images/sort_desc.png" failed

### ISSUE THREAD

**Issue by LastStopITSolutions** [freescout-help-desk/freescout#4107]
PHP version: PHP 8.1.2-1ubuntu2.18 (cli)
FreeScout version: 1.8.145
Database: MySQL
Are you using CloudFlare: Yes
Are you using non-official modules: No

Error is showing in web server log

`[error] 631#631: *411 open() "/var/www/html/public/js/datatables/DataTables-1.10.18/images/sort_desc.png" failed (2: No such file or directory), client: 192.168.1.xxx, server: helpdesk.domain.com, request: "GET /js/datatables/DataTables-1.10.18/images/sort_desc.png HTTP/1.1", host: "helpdesk.domain.com", referrer: "https://helpdesk.domain.com/js/datatables/datatables.min.css"`

The directory /var/www/html/public/js/datatables/DataTables-1.10.18/images doesn't exist. Its not even in the source files on github. Not sure why its calling for those images in that directory but those images dont exist anywhere in the source files. the directory

`/var/www/html/public/js/datatables/` 

Only contains the following files:
`datatables.css  datatables.js  datatables.min.css  datatables.min.js`

Is this just a bug or is something actually missing?

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
