### ISSUE TITLE
Inbox is fetching but emails are missing.

### ISSUE THREAD

**Issue by aaversa** [freescout-help-desk/freescout#4109]
We have 6 mailboxes in use with Freescout. For the last 16 hours or so, one of the mailboxes has failed to pull several messages.

We received emails to our source inbox (Google Workspace) at 7:08pm local time on 6/27, 2:19am on 6/28, and 6:03am on 6/28.

These emails never appeared in Freescout in the corresponding "Partners" mailbox. I checked the fetch log and there are no errors from either day.

![fetch log](https://github.com/freescout-help-desk/freescout/assets/1279358/d99339c2-31f4-4aaf-96a5-6efe9dbb5cfb)

I also checked the app log and I can see that our "Partners" inbox reported as fetched.

![fetch log 2](https://github.com/freescout-help-desk/freescout/assets/1279358/a4484f54-3114-4ce9-b3c1-c7e267a0aded)

No other application errors of any kind. I did clear cache about 30 minutes ago. Other inboxes are seemingly fetching correctly. I did test connection on the Partners inbox in Freescout and it was successful.

PHP version:  PHP 8.3.6
FreeScout version: 1.8.138
Database: Mysql (8.0.37-0ubuntu0.24.04.1)
Webserver: nginx/1.24.0
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Fetching-Emails#troubleshooting-fetching

**Comment by aaversa** [comment]
We are still having this issue intermittently. I would say 99% of emails get fetched and then sometimes, randomly, they don't. There is nothing in the logs about this. How can we get more detail about WHY certain emails did not fetch?

**Comment by freescout-help** [comment]
You can do some debugging: https://github.com/freescout-help-desk/freescout/wiki/Debugging

Also make sure that something does not mark emails as READ in your mailbox.
