### ISSUE TITLE
Automatic agent assignment. Workflow

### ISSUE THREAD

**Issue by vy34vlg** [freescout-help-desk/freescout#4110]
Good afternoon.
Is it possible to automatically assign an agent to the New Ticket?
If so, what conditions are correct to use?
There are 10 agents in the system, 7 of whom execute tickets, ideally you need to assign a less busy employee automatically.
Workflow module purchased.

PHP version: PHP 8.2.16
FreeScout version: 1.8.118
Database: PostgreSQL 15.5
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
You may need to play with conditions yourself to achieve what you need.
