### ISSUE TITLE
User portal

### ISSUE THREAD

**Issue by yabloky** [freescout-help-desk/freescout#4111]
Hello friends!

Thank you for the wonderful product, more than one company already use it and are happy with it. Here again I am facing a problem and I am thinking how to solve it with Freescout.

The company is a logistics company - the client writes in messenger, then he is given a link to a google table, which the manager together with the client fills out. I haven't figured out how in Freescout ticketing system, to make a collaborative table or integrate Freescout with google exel.

Or at least add an active link in the client's card to their google table.

**Comment by freescout-help** [comment]
There is no any such feature for now.

Feel free to [submit feature requests](https://freescout.net/request-feature/).

**Comment by yabloky** [comment]
ok. Is it still impossible to insert random active links into a custom field? I want to have a link to his facebook in his profile. I create a custom field - Link, I go to the profile to fill it, but you can not fill it. I can choose from placeholders, where it will lead to in advance, but each user has his own profile.

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!

**Comment by ilyakonovalenko** [comment]
@greggblazer please stop posting this in every thread.

**Comment by yabloky** [comment]
> How the HELL DO you UNSUBSCRIBE for these Freescout threads!!? I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!
> 
I like freescout, it's a very user friendly system, if you haven't figured out how to use it, that's your problem. 
-
Who knows about active link in client card - how to do it? I need to attach to each client an active link to his google table. I put plugin custom fields, but unfortunately there I did not understand how to insert an arbitrary link.

**Comment by freescout-help** [comment]
You can create an extra custom field and store some part of the URL there. And use `{%cf_CUSTOMER_FIELD_ID%}` placeholder to compose the link in the "Link" custom field.

**Comment by yabloky** [comment]
"You can create an extra custom field and store some part of the URL there. And use `{%cf_CUSTOMER_FIELD_ID%}` placeholder to compose the link in the "Link" custom field."

Thanks for the reply, but I don't really understand how it works. I thought I just create a "link" field, and then each user has their unique link inserted. But no. I can only specify one link for everyone? That's kind of weird.

![Uploading iScreen Shoter - Brave Browser - 240710102308.jpg…]()

**Comment by yabloky** [comment]
**Please support the possibility of adding unique for each user, active links in the client:** cardhttps://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/443721

**Comment by ilyakonovalenko** [comment]
> But no. I can only specify one link for everyone? That's kind of weird.

No. Just create some text custom field and then fill it out for every customer. You will need CRM module, not user custom fields module.

**Comment by yabloky** [comment]
I have a CRM module as well as custom fields. But now I can create inactive links. If you managed to add unique active links for customer card - please tell me how you did it.

**Comment by ilyakonovalenko** [comment]
> But now I can create inactive links. If you managed to add unique active links for customer card - please tell me how you did it.

As far I know, you can't. Text is not parsed as links. The solution is to modify the CRM module to show text as a link. Adding another type of custom fields is easy.

**Comment by yabloky** [comment]
That they have in the module custom fields, there is a type of field Link, but some genius decided that it is necessary to write a link there at once, that it appeared for all users in the card, the same, I can not imagine why it is done, so I need to set a different link for each user in that field.

**Comment by ilyakonovalenko** [comment]
Yes, that is strange, I see no reason for a static link too. Maybe FreeScout devs will do something about this after your message. Anyway, you can modify the module for now.

**Comment by freescout-help** [comment]
Use Single Line customer field. If you enter a text starting with "http://" or "https://" into the Single Line field, it will be shown as a link in the customer profile.

**Comment by yabloky** [comment]
It will be just text, an inactive link, you have to copy it to the clipboard, open your browser and paste it there - which is not very convenient.

**Comment by freescout-help** [comment]
Yes. For now it will be shown as a link only in the conversation sidebar.

**Comment by yabloky** [comment]
Would you mind showing me a screenshot of how it works? Because even on the sidebar of the dialog, I don’t have an active link, but just text, I just checked
