### ISSUE TITLE
Draft missing in draft folder after undo sending message

### ISSUE THREAD

**Issue by sofl88** [freescout-help-desk/freescout#4112]
Reproducible in the freescout demo. After undo sending a message, the draft is only accessible over the search (?) Also the receiver address (TO)  is copied into CC.

https://github.com/freescout-help-desk/freescout/assets/12407767/2e1374aa-f63e-4b4c-92a3-d4739abda1c1

In the search result it looks like the draft / message is assigned to the current user but it is also not visible under "Mine"

Thanks in advance

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
