### ISSUE TITLE
Indication of the status of outgoing emails to non-admin users

### ISSUE THREAD

**Issue by ThomasEKolb** [freescout-help-desk/freescout#4114]
Hello!

Would it be possible to show the “Outgoing Emails” dropdown option to non-admin users as well? If not, would it be possible to indicate within the mail UI that a ticket was received by the recipient? Even a small indicator would be enough.

Currently, only admin users can see if an email was successfully sent to the customer. This is a problem because users cannot check if the email was successfully sent, which can be an issue in some edge cases.

Thank you very much!

**Comment by freescout-help** [comment]
See https://github.com/freescout-help-desk/freescout/wiki/FAQ#how-can-support-team-know-that-there-are-problems-with-sending-emails-and-emails-are-not-being-sent

> If not, would it be possible to indicate within the mail UI that a ticket was received by the recipient?

Technically it's impossible. You can read more here: https://github.com/freescout-help-desk/freescout/wiki/Sending-Issues#how-emails-are-being-sent

Support agents can see when the email has been read by the customer.

**Comment by greggblazer** [comment]
How the HELL DO you UNSUBSCRIBE for these Freescout threads!!?    I tried and wished Freescout would and could have worked as promised.. but it was Such a Piece of CRAP with Soooo MANY Issues and BUGS that I finally found a WAY Better solution, osTicket that is FREE and Just WORKS BUG FREE!

I could Never get Proper Help here to fix anything serious.. so forced to give up. Good luck to you all.

So I No Longer wish to hear of all the Shitty BUGS and Issues you all are plagued with.. Please UNSUBSCRIBE ME! I have tried a bunch of times!

**Comment by ThomasEKolb** [comment]
> See https://github.com/freescout-help-desk/freescout/wiki/FAQ#how-can-support-team-know-that-there-are-problems-with-sending-emails-and-emails-are-not-being-sent
> 
> > If not, would it be possible to indicate within the mail UI that a ticket was received by the recipient?
> 
> Technically it's impossible. You can read more here: https://github.com/freescout-help-desk/freescout/wiki/Sending-Issues#how-emails-are-being-sent
> 
> Support agents can see when the email has been read by the customer.

Thank you very much for the fast reply. What I'm thinking about is an option to share the information of "Emails to Customers -> "Accepted for delivery"" with non admin users. 

<img width="905" alt="mail-log" src="https://github.com/freescout-help-desk/freescout/assets/16431559/90392454-5d3d-463c-8c5f-8b2c98f776df">

Alternatively, could we add an (optional) option that allows non-admin users to see the “outgoing emails” dropdown?

**Comment by freescout-help** [comment]
Unfortunately there is no such plans for now. Do you have cases where the email has not been passed for delivery and the support agent has not been informed about it?
