### ISSUE TITLE
There is a problem when installing an update to the Freescout system: messages stop being sent to telegram and whatsapp, what should I do?

### ISSUE THREAD

**Issue by alexsokolik** [freescout-help-desk/freescout#4115]
PHP version: 8.1.6
FreeScout version: 1.8.135
Database: MySQL 
Are you using CloudFlare: / No
Are you using non-official modules: Yes

**Comment by alexsokolik** [comment]
Sorry Are you using non-official modules: no
I bought modules
There is also a problem with the database, I can’t figure out what the problem is!
![Uploading 2024-07-06_02-35-51.png…]()

**Comment by freescout-help** [comment]
Make sure background jobs are running after the update: https://github.com/freescout-help-desk/freescout/wiki/Background-Jobs
