### ISSUE TITLE
Is there a way to set a custom header to a custom field?

### ISSUE THREAD

**Issue by aaukt** [freescout-help-desk/freescout#4119]
We are trying to get some additional data to the conversation from the sending side.
We are using the "Custom Fields" module and are wondering if there is a way to fill a field from a mail header.
For example the sending application adds a header "X-Customer-Id: 1234" to the mail. How would we go about setting the value of that custom header to our custom field in freescout? (The "Workflow Module" does not seem to have this functionality.)

PHP version: 8.1
FreeScout version: 1.8.146 
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
There is no such feature for now. You can implement it by adjusting module's code.
