### ISSUE TITLE
Workflow Module: Body Customer Message Contains Condition not Matching

### ISSUE THREAD

**Issue by Aulig** [freescout-help-desk/freescout#4120]
PHP version: PHP 7.4.3-4ubuntu2.23
FreeScout version: 1.8.138
Database: Mysql (8.0.37-0ubuntu0.20.04.3) 
Are you using CloudFlare: No
Are you using non-official modules: Yes

I have a workflow that works without but not with the condition that the customer message must contain "invited". Therefore I conclude that the issue must be somewhere with the "Body" condition.

![image](https://github.com/freescout-help-desk/freescout/assets/32148066/e2ddcb7a-ad4e-4a46-8abb-3bb62104fdd8)

Here's the e-mail body (taken from Freescout) of an e-mail that the condition should be true on.

```
<div style="width: 590px;"><div style="background: url('https://www.gstatic.com/android/market_images/email/email_top.png') no-repeat;width:100%; height: 75px; display:block"><div style="padding-top: 30px; padding-left: 50px; padding-right: 50px;"><a href="https://play.google.com/store"><img src="https://www.gstatic.com/android/market_images/email/play_logo_email_2022.png" alt="Google Play Logo" style="border:none;"></a></div></div><div style="background: url('https://www.gstatic.com/android/market_images/email/email_mid.png') repeat-y; width:100%; display:block"><div style="padding-left: 50px; padding-right: 50px; padding-bottom: 1px;"><div style="border-bottom: 1px solid #EDEDED;"></div>Hello,<p>xxx@gmail.com has invited you to share a Google Play Console account 'XXX' using your own email address and password.</p><p>Your use of Google Play must abide by the applicable terms, including the <a href="https://play.google.com/about/developer-distribution-agreement.html">Developer Distribution Agreement</a>.</p><p>To accept this invitation, visit the link below. You'll then create a Google Account or choose an existing one to sign in to Google Play Console in the future. A Google Account is made up of a single email address and password, and gives you a simple and secure way to access your other Google services.</p><p>Once you complete the process, xxx@gmail.com will be able to confirm your acceptance and grant you access to the Google Play Console account. This invitation expires on 28 June 2024.</p>Your access to this Google Play Console account expires on 28 June 2024.<p>To accept your invitation, visit<br><a href="https://play.google.com/console/signup/invitation/xxx">https://play.google.com/console/signup/invitation/xxx</a></p><p>If you're unable to click on any of the links above, copy and paste the URL into a new browser window instead.</p><p>For more information, please visit our <a href="https://support.google.com/googleplay/android-developer/">frequently asked questions</a>.</p><p>Note: Even if you already have access to this Google Play Console account, it's a good idea to create your own username and password.</p>Sincerely,<br>The Google Play Team</div></div></div><div style="background:url('https://www.gstatic.com/android/market_images/email/email_bottom.png') no-repeat; width:100%; min-height:50px; display:block"><div style="padding-left:50px; padding-right:50px"></div></div>
```

Thank you in advance for your help.

**Comment by freescout-help** [comment]
Try to leave only "Body" condition and check.

**Comment by Aulig** [comment]
Thanks for your quick reply.

The issue seems to be dependent on another workflow (let's call it workflow 2) being active:
![image](https://github.com/freescout-help-desk/freescout/assets/32148066/1260ee5e-bc45-4455-9525-04ad1b938a25)

So if:
Workflow 2 inactive: Body condition in Workflow 1 works
Workflow 2 active: Body condition in Workflow 1 doesn't work, but when I have just the customer e-mail condition it works fine.

Unfortunately I couldn't find any docs on how to give one workflow priority over another in case that is playing a role here. If it makes a difference, Workflow 2 is above Workflow 1 on the workflows page (/mailbox/1/workflows)

**Comment by freescout-help** [comment]
Can you share conditions and actions of Workflow 2.

**Comment by freescout-help** [comment]
We've just checked it with exactly the same workflows and same email body and it works just fine.

![2024-07-19_07-55-57](https://github.com/user-attachments/assets/f491db19-7d26-42b6-8190-36d0057879b4)

So someone may need to debug it on your server.

**Comment by Aulig** [comment]
Thanks for your help. I guess I'll need to set up a fresh installation maybe. I'll let you know if I can figure out anything else about the issue!
