### ISSUE TITLE
Question: Plan for SMTP when Google Workspace removes "allow less secure apps"

### ISSUE THREAD

**Issue by reneenoble** [freescout-help-desk/freescout#4121]
I'm configuring my mailboxes now with SMTP linking, using Google Workspace as my mail server. 

What is the plan for the near future when Google Workspace mandates Oauth?
![Screenshot 2024-07-12 at 5 02 05 PM](https://github.com/user-attachments/assets/a0e922ea-1b57-4e5b-a661-963edb7d7827)

Here is the timeline from Google: https://support.google.com/a/answer/14114704?hl=en-GB

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/issues/3707#issuecomment-1902060615

https://github.com/freescout-help-desk/freescout/wiki/Connect-G-Suite-to-FreeScout
