### ISSUE TITLE
Adding Time Log Entry for day that has passed?

### ISSUE THREAD

**Issue by Creanimo** [freescout-help-desk/freescout#4122]
Hello everyone, awesome product, love using it! Keep doing the fantastic work! 🙂 👍 

I was wondering if I am overlooking something with regards to the time tracking module:
As I sometimes start working without looking at the ticket, I sometimes forget to start time tracking. I want to add the time to the previous day, not the current day. **Is there any way to add a time log entry for a day that has already past?**

My manager does not like if I track more than 8 hours to one work day as this may have legal consequences during an audit.

All the best and thanks again!

PHP version: 8.2.20
FreeScout version: 1.8.145
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
There is no such feature for now.  Feel free to [submit a feature request](https://freescout.net/request-feature/).
