### ISSUE TITLE
Workflow Module with Action "Move to mailbox" is not working

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4123]
Hi @freescout-help 

"Workflow Module" with Action "Move to mailbox" is not working, after doing it, it gives "Too Many Redirects" error.

<img width="346" alt="Screenshot 2024-07-13 at 10 46 07 PM" src="https://github.com/user-attachments/assets/f35507f5-3e48-49ca-9952-99ca46204bd7">

**Comment by freescout-help** [comment]
Are you using any non-official modules? If so try to disable them.

Also check errors in Manage > Logs > App Logs.

**Comment by mahavirn** [comment]
No, not using any of them, all bought from the FreeScout Marketplace.

**Comment by mahavirn** [comment]
There is no error related to this in ErrorLog.

**Comment by freescout-help** [comment]
We can't reproduce the issue. 
The only way to figure out what is the reason is to debug it on your server.

**Comment by mahavirn** [comment]
Are there any specific steps to debug on server?

**Comment by freescout-help** [comment]
In your case you can try first to figure out what causes the infinite redirect:
https://github.com/freescout-help-desk/freescout/blob/dist/app/Http/Controllers/ConversationsController.php#L75

https://github.com/freescout-help-desk/freescout/wiki/Debugging

**Comment by mahavirn** [comment]
Hi @freescout-help 

Its updating the Mailbox id properly but unable to update Folder Id..

Its assigning previous (original) mailbox's "Assigned" folder to "Folder Id"

**Comment by freescout-help** [comment]
We still can't reproduce the issue. Try to figure out why it's not changing the `folder_id`:
https://github.com/freescout-help-desk/freescout/blob/dist/app/Conversation.php#L1285

**Comment by mahavirn** [comment]
Hi @freescout-help 

I have check there and its updating $this->folder_id but again folder_id is reset back to some other id (Assigned folder of previous mailbox)

We also have multiple other Workflows, can it be because of that?

**Comment by freescout-help** [comment]
Yes, try to disable other workflows.
