### ISSUE TITLE
Wallboards Module: Editing permissions for wallboards not working

### ISSUE THREAD

**Issue by banditrider** [freescout-help-desk/freescout#4124]
Only the user who creates a wallboard is able to edit it (also according to the wallboard module page).

However, there are user permissions regarding editing wallboards. Those permissions (can see and can edit wallboards) don't seem to do anything; and other admins can't edit a wallboard they didn't create, independently of any user permissions.

This is not great, as other admins will also have to edit wallboards in our organization without having to share their login data.

Would it be possible to get this behavior updated so it's consistent with the user permissions that are available? Ideally, all wallboards could be also edited by other admins, as long as they are shared with admins.

**Comment by freescout-help** [comment]
> can see and can edit wallboards

There is no such permission. Under General Settings there is "Users are allowed to access wallboards", it allow non-admin users to access "Wallboards" page.

There is no an option allowing admins to edit any wallboards for now. You can ask your support agents not to create wallboards and let only admins to do it.

**Comment by banditrider** [comment]
Thanks for your reply.

You're right, the permission's not called "edit wallboards" but "manage wallboards":
![image](https://github.com/user-attachments/assets/a4f1de9d-d7eb-4f37-9dd3-5553860c58f5)

Personally, I understand editing to be a subset of managing.

However, besides the semantics, it would just be really useful to be able to grant editing access to at least other admins:

> You can ask your support agents not to create wallboards and let only admins to do it.

Unfortunately, this doesn't solve the issue for us. We have multiple admins, and they still wouldn't be able to edit wallboards from other admins. If an admin leaves the organization, as it is now, the other admins would have to recreate the wallboards of the admin who left or log in with the gone admin's account just to edit wallboards.

It's feasible, but why not just allow admins to edit the wallboards they can see (rather than just the ones they've created)? 
Admins have very broad rights anyway, being able to change way more mission-critical settings; so giving them the permission to edit wallboards shouldn't be an issue for any organization.

**Comment by freescout-help** [comment]
In Wallboards Module v1.0.7 admins now can edit all accessible wallboards.

**Comment by Kerovsky** [comment]
In Wallboards thread Closures are not counted, only those assigned to the user, in general reports Closures to the user are counted, even those not assigned to the user
