### ISSUE TITLE
Reports Module: Productivity Reports - Inconsistencies between Closed Issues and Resolution Time

### ISSUE THREAD

**Issue by banditrider** [freescout-help-desk/freescout#4125]
According to the Reports Module Page, the “Closed” number shows the number of conversations which has been closed in the selected period. Without taking the opening time of the conversation into consideration.

However, the resolution time only shows values calculated for conversations that have been opened and closed in the selected period (at least that's our interpretation looking at the numbers). To us, this is confusing, as these numbers are not related to the numbers of closed issues. Also, this means that super long reply times only show up if the selected period is really long, making such issues potentially never visible.

Would it be possible to calculate the resolution times based on the closed issues that are also displayed in the productivity reports to make these metrics consistent?

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by banditrider** [comment]
I'll do so, thanks. But isn't this more about fixing the current implementation rather than a new feature?

**Comment by freescout-help** [comment]
It works as designed.
