### ISSUE TITLE
Add old conversation context to `conversation.state_changed` event

### ISSUE THREAD

**Issue by IchHabeHunger54** [freescout-help-desk/freescout#4127]
PHP version: 8.2.20
FreeScout version: 1.8.139
Database: MySQL / ~~PostgreSQL~~
Are you using CloudFlare: ~~Yes~~ / No
Are you using non-official modules: Yes / ~~No~~

Hello!

I'm currently writing a plugin that is supposed to show changes to the subject of a conversation, in a similar fashion to status changes. My initial scouring through the Freescout codebase led me to the `conversation.state_changed` event, however that one is crucially missing the old conversation state that I could use to get the old subject.

So my humble request would be to add the old conversation context to that event, or some other way to get the old subject in that event. (If I'm doing this completely wrong to begin with, then please direct me towards the correct way!)

**Comment by freescout-help** [comment]
You can submit a pull request with the changes needed.

**Comment by IchHabeHunger54** [comment]
Closed by linked PR.
