### ISSUE TITLE
Unable to Send Emails and Auto-Reply Not Working in FreeScout

### ISSUE THREAD

**Issue by VinayakYadav929** [freescout-help-desk/freescout#4128]
**Issue Description:**
We have successfully installed and configured FreeScout, and it is able to receive emails from external sources such as Gmail without any issues. However, we are encountering the following problems:

**1. Outgoing Emails:** When trying to send replies or new emails from FreeScout, these outgoing emails are not being received by the intended recipients.
**2. Auto-Reply:** In FreeScout, if an email is received, it should send an auto-reply. However, this feature is not working as expected. Emails that should trigger an auto-reply do not receive any response.

**I have configured the SMTP settings in FreeScout**
We have verified these settings by using the "Send Test Email" feature in FreeScout, and we do receive a test email confirming that the mailbox can send emails.

Thank you very much for your support. 
We look forward to your guidance to resolve these matters promptly.

**Comment by freescout-help** [comment]
All things we can suggest are already listed here: https://github.com/freescout-help-desk/freescout/wiki/Sending-Issues

**Comment by freescout-help** [comment]
Keep in mind that email address of your mailbox should be the same as email of your Gmail account.

**Comment by VinayakYadav929** [comment]
yes it is same

**Comment by VinayakYadav929** [comment]
By mistake, it was clicked as completed but it's not completed.

And I'm also not receiving any issues in the logs.
