### ISSUE TITLE
Add Max File Upload Size restriction to Chat Module

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4129]
Hi @freescout-help,

I am using the "Chat Module" provided by you.

I believe it is missing one important setting: the option to configure the maximum file upload size limit inside the chat widget.

Could you please provide this option to prevent users from uploading larger files and bloating our server?

Thanks!

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).
