### ISSUE TITLE
How do I turn off email notifications completely?

### ISSUE THREAD

**Issue by mihdan** [freescout-help-desk/freescout#4131]
We are load testing FreeScout and creating 10000 new conversations, how can we completely disable email notifications so as not to overload the SMTP server and spam mailboxes?

**Comment by freescout-help** [comment]
You can disable email notifications for all your support agents in their profiles.

**Comment by mihdan** [comment]
We have 10,000 agents

**Comment by mihdan** [comment]
Thanks, that should solve our problem.
