### ISSUE TITLE
Call to a member function getFirstName() on null 

### ISSUE THREAD

**Issue by rabbate** [freescout-help-desk/freescout#4132]
App Version = 1.8.146
I have the following modules installed:
-API and Webhooks
-Internal Conversations
-Satisfaction Ratings
-Tags

Keep seeing this in the error logs:

Call to a member function getFirstName() on null (View: /var/www/freescout/resources/views/emails/user/notification.blade.php) {"exception":"[object] (ErrorException(code: 0): Call to a member function getFirstName() on null (View: /var/www/freescout/resources/views/emails/user/notification.blade.php) at /var/www/freescout/storage/framework/views/995ce08d5670edf181ced61731cb102d205581ce.php:44, Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getFirstName() on null at /var/www/freescout/storage/framework/views/995ce08d5670edf181ced61731cb102d205581ce.php:44)

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
