### ISSUE TITLE
Variables from Saved Replies are gone

### ISSUE THREAD

**Issue by MarianBMI** [freescout-help-desk/freescout#4133]
Hello,

I just noticed that the Variables from the Saved Replies module are gone. 
Why were these removed? They were an important function.
![image](https://github.com/user-attachments/assets/ef98ffd1-195c-4d5a-a54c-5aae20e51f1e)

The module looked like this:
![image](https://github.com/user-attachments/assets/6efb426b-bb3c-4276-9c75-45977348ffc6)

-->

PHP version: PHP 8.0.30
FreeScout version: 1.8.141
Database: Mysql (10.6.16-MariaDB-0ubuntu0.22.04.1)
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Fixed in Saved Replies v1.0.42
