### ISSUE TITLE
Migrated to new server, but file path keeps somewhere remembered?

### ISSUE THREAD

**Issue by dewced** [freescout-help-desk/freescout#4134]
I moved database & files to new server, and updated my .env file with the new database and new URL ... cleared cache. However, it keeps giving errors on file upload / sending e-mail.
Looks like it somewhere refers to my old server path?

/var/www/clients/client5/web14/web/ => server path of old server.?

error | production | 2024-07-17 18:47:36 | Uncaught ErrorException: file_exists(): open_basedir restrictionin effect. File(/var/www/clients/client5/web14/web/resources/views/errors/500.blade.php) is not within the allowed path(s): (/home/waswacwu/:/tmp:/var/tmp:/opt/alt/php81/usr/share/pear/:/dev/urandom:/usr/local/lib/php/:/usr/local/php81/lib/php/) in /home/waswacwu/domains/care.connectwork.be/public_html/overrides/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:23

error | production | 2024-07-17 18:47:36 | file_exists(): open_basedir restriction in effect. File(/var/www/clients/client5/web14/web/resources/views/errors/500.blade.php) is not within the allowed path(s): (/home/waswacwu/:/tmp:/var/tmp:/opt/alt/php81/usr/share/pear/:/dev/urandom:/usr/local/lib/php/:/usr/local/php81/lib/php/) {"exception":"[object] (ErrorException(code: 0): file_exists(): open_basedir restriction in effect. File(/var/www/clients/client5/web14/web/resources/views/errors/500.blade.php) is not within the allowed path(s): (/home/waswacwu/:/tmp:/var/tmp:/opt/alt/php81/usr/share/pear/:/dev/urandom:/usr/local/lib/php/:/usr/local/php81/lib/php/) at /home/waswacwu/domains/care.connectwork.be/public_html/overrides/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:23)

------------------------------------------------
PHP version: 8.2
FreeScout version: 1.8.146
Database: MySQL
Are you using CloudFlare: Yes
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Try Step 4 from https://github.com/freescout-help-desk/freescout/wiki/Upgrade-PHP

**Comment by dewced** [comment]
Just tried it twice, but same. It also complains about "lost internet connection". Would it be an issue in my installation? All system stats are OK, permissions also OK.
