### ISSUE TITLE
Customer Data Enrichment not working

### ISSUE THREAD

**Issue by orbnetde** [freescout-help-desk/freescout#4135]
Customer Data Enrichment does not work. No logs, no data. Module is activated.

The Service https://domainbigdata.com/ is down, this Module can't work anymore.

PHP version: 8.2.21
FreeScout version: 1.17.78
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Yes. The module just enriches user avatars.
