### ISSUE TITLE
Missing "disconnect" button in connection settings of outlook mail account

### ISSUE THREAD

**Issue by kai-hier** [freescout-help-desk/freescout#4136]
Due to corporate policy the password of the outlook account connected has to be renewed, thus preventing the oAuth token from being refreshed. The new password is set and the mail-account has to be reconnected, but I simply can not disconnect it, because the button for doing so is missing:

![grafik](https://github.com/user-attachments/assets/919ec3a3-f4c8-4879-8172-e21575d80d21)

         
| Anwendungs-Version | 1.8.146 |
| -- | -- |
| Protokoll | HTTPS |
| Mysql  | (8.0.37-0ubuntu0.22.04.3) |
| Webserver | nginx/1.18.0 |
| PHP     |               8.1.2-1ubuntu2.18|
| CloudFlare | No |
| Comunity Modules | Calendar, Themes|

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
