### ISSUE TITLE
Search for custom fields content does not work

### ISSUE THREAD

**Issue by ilyakonovalenko** [freescout-help-desk/freescout#4137]
I noticed search does not work in case there are multiple custom fields with the same name in mailboxes.
I am using /search endpoint, there are custom fields listed on the left side of the page. When you click on any of those with the same names, search does not work at all.

To reproduce:
* Mailbox A has custom field Priority.
* Mailbox B has custom field Priority.
* Search will not work for Priority in the case.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/issues/3690

**Comment by ilyakonovalenko** [comment]
Any custom field has ID, maybe use ID instead of name in search area?

**Comment by freescout-help** [comment]
In Custom Fields Module v1.0.36 filtering Custom Fields with the same name (in different mailboxes) has been implemented.
