### ISSUE TITLE
Application with identifier for OAuth is keeped after change

### ISSUE THREAD

**Issue by ThomasBergmann123456** [freescout-help-desk/freescout#4138]
I need to change Username and Passwort for OAuth (new App) but the old ID is  still somewhere in use.

The Account in Frescout is still Active (green) and connected to Exchange (green) - even after the change.

Error: Error occurred refreshing oAuth Access Token: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '277xxxxxxxxxx' was not found in the directory 'xxx'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. xxxxx","error_uri":"https://login.microsoftonline.com/error?code=700016"}; File: /usr/www/users/speyer/intern/tickets/app/Misc/Mail.php (746)

How can I fix this without creating a news mailbox?

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/issues/4136
