### ISSUE TITLE
Fallback for variables

### ISSUE THREAD

**Issue by PoeHaH** [freescout-help-desk/freescout#4139]
Hi,

I love the "variables" feature in saved replies. I'd like to implement "fallback" behavior just like HelpScout. Their variable looks like this: 

Hi `{%customer.firstName,fallback=there%}`,

If `customer.firstName` is not available, "there" will be inserted instead.

I'd love to implement similar behavior, but there's no filter to alter the output from variables? Would you be willing to include it?

Thanks!

**Comment by freescout-help** [comment]
It would be better to implement this in the core of the application.

**Comment by PoeHaH** [comment]
Can I do something to make this happen?

**Comment by freescout-help** [comment]
Yes, you can implement it and submit a pull request.

**Comment by MarianBMI** [comment]
hi @freescout-help I totally understand @PoeHaH . This feature should be set by default. Why not setting it?
