### ISSUE TITLE
Whatsapp Module: Images not displaying

### ISSUE THREAD

**Issue by Sawyus** [freescout-help-desk/freescout#4140]
Hello!
We've been using the whatsapp module for a few weeks now, after having a lot of trouble with meta to integrate our whatsapp business account with 1msg io, it finally worked, but over the last days I've gotten feedback from coworkers that whenever clients try to send us images via whatsapp, it only shows 'Image' in freescout as plain text.
As I can't look into conversations in 1msg io, nor on their middleware 360dialog, I can't send it manually to them either, thus we have to ask our clients to send us images via mail, which isn't that useful, nor comfortable of course.
When testing, I wasn't able to trigger any error messages, so I wanted to ask, if that behavior is expected with the module and when using 1msg io.
The only thing I was able to find in the system settings was the server user didn't have the rights to wright into storage/framework/cache/data tough I'm not sure wether this is related to images that are sent to us over whatsapp.
Text displays fine.

PHP version: 8.1.29
FreeScout version: 1.8.141
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
You can try to debug the integration: https://github.com/freescout-help-desk/freescout/wiki/Debugging

Add for example the following code on the line 161 in /Modules/WhatsApp/Http/Controllers/WhatsAppController.php and try to send an image to your WhatsApp account:
```
\Log::error("message: ".json_encode($message)."; body: ".json_encode($body)."; attachments: ".json_encode($attachments));
```

**Comment by freescout-help** [comment]
Also in the `master` branch we've added logging to App Logs when downloading of a remote file is unsuccessful: https://github.com/freescout-help-desk/freescout/commit/efca2acbe24ad56a5d36bab1a0bd6d88a66cfbeb
