### ISSUE TITLE
Out of Office module not working

### ISSUE THREAD

**Issue by astick360** [freescout-help-desk/freescout#4142]
PHP version: 8.3.9
FreeScout version: 1.8.146
Database: PostgreSQL
Are you using CloudFlare:  No
Are you using non-official modules:   No
Service: Pikapods
Module: Out of Office
Module version: 1.0.7
DataBase: Pgsql (13.13 (Debian 13.13-1.pgdg120+1))
Server: nginx/1.27.0

Hi, I encountered a problem with purchased Out of Office module, I can't switch any user into not available, because an error appears. Those are logs i get after error with anonymised data:

SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "available" of relation "users" violates not-null constraint

DETAIL:  Failing row contains (3, name, surname, name.surname@domain.com, $2y$10$gATcrmULdGPA6dJOlccPDOuk2xzcI0GtpHTM6oNiDWls59AsV0IBu, 1, Europe/Berlin, null, 1, 1, , null, IT specialist, 723688978, 2, f, f, O5Oeo0C32NmImBNtHb5EDB4GSCfoZ5sRjEHpI1bOeJy8E9tk9rAFOB8BC6PT, 2024-06-08 22:31:46, 2024-07-22 14:46:05, pl, 1, null, null). (SQL: update "users" set "updated_at" = 2024-07-22 14:46:05, "available" =  where "id" = 3) {"userId":2,"email":"admin.mail@domain.com","exception":"[object] (Illuminate\\Database\\QueryException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"available\" of relation \"users\" violates not-null constraint
DETAIL:  Failing row contains (3, name, surname, name.surname@domain.com, $2y$10$gATcrmULdGPA6dJOlccPDOuk2xzcI0GtpHTM6oNiDWls59AsV0IBu, 1, Europe/Berlin, null, 1, 1, , null, IT specialist, 723688978, 2, f, f, O5Oeo0C32NmImBNtHb5EDB4GSCfoZ5sRjEHpI1bOeJy8E9tk9rAFOB8BC6PT, 2024-06-08 22:31:46, 2024-07-22 14:46:05, pl, 1, null, null). (SQL: update \"users\" set \"updated_at\" = 2024-07-22 14:46:05, \"available\" =  where \"id\" = 3) at /www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"available\" of relation \"users\" violates not-null constraint
DETAIL:  Failing row contains (3, name, surname, name.surname@domain.com, $2y$10$gATcrmULdGPA6dJOlccPDOuk2xzcI0GtpHTM6oNiDWls59AsV0IBu, 1, Europe/Berlin, null, 1, 1, , null, IT specialist, 723688978, 2, f, f, O5Oeo0C32NmImBNtHb5EDB4GSCfoZ5sRjEHpI1bOeJy8E9tk9rAFOB8BC6PT, 2024-06-08 22:31:46, 2024-07-22 14:46:05, pl, 1, null, null). at /www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"available\" of relation \"users\" violates not-null constraint
DETAIL:  Failing row contains (3, name, surname, name.surname@domain.com, $2y$10$gATcrmULdGPA6dJOlccPDOuk2xzcI0GtpHTM6oNiDWls59AsV0IBu, 1, Europe/Berlin, null, 1, 1, , null, IT specialist, 723688978, 2, f, f, O5Oeo0C32NmImBNtHb5EDB4GSCfoZ5sRjEHpI1bOeJy8E9tk9rAFOB8BC6PT, 2024-06-08 22:31:46, 2024-07-22 14:46:05, pl, 1, null, null). at /www/html/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)

What should I do to fix it? What causes the problem?

**Comment by freescout-help** [comment]
Fixed in Out Of Office Module v1.0.2

**Comment by astick360** [comment]
Yeah, maybe, but I have newer version of the module than v1.0.2 (currently I have v1.0.7, as I stated in the post) and have this problem.

**Comment by freescout-help** [comment]
You are probably mixing https://freescout.net/module/office-hours/ and https://freescout.net/module/out-of-office/.

Just update Out of Office Module to the latest version.

**Comment by astick360** [comment]
Oh, right, sorry, thanks a lot :)
