### ISSUE TITLE
Circular email Loop

### ISSUE THREAD

**Issue by steveb85** [freescout-help-desk/freescout#4143]
We've had quite a day of circlular email loops. I've seen a few threads on here, and been chasing tails all around and shutting emails out all over the place but found an un-likely culprit, i thought I'd share, I'm hoping it's fixed now, but perhaps will help the team or someone else. I'm still not quite sure of the cause, but after scouring logs and having quite the day, our email server was sending out6 emails a second, which is enough to constantly get shut down in short order, making catching it hard, as it would be a hectic 40 mins and then be shut down by microsoft and go dead for an hour and then start back up again abruptly. 

the fetch email logs, (yes fetch not send, not app, but fetch) finally led me to find this log, where by every user was getting sent an email saying they needed to have the fetch account email added to their alternative emails on their user account ? but that is marked as optional? quiet weird... perhaps someone can shine a light on that. then after a while that cuased another loop because microsoft marked the sender as spam, (makes sense) and so then i was getting undelieverable emails, which of course go to the inbox of the help, and then that trigggers an autoreply which triggers another email, and so on. so you can see how it got out of hand quickly and i was seeing emails everywhere but finding the route was very hard... anyway, I'll paste some text from the actual "first contact" i finally found of the loop.... in case it provides some help... and hopefully tomorrow is fine...thanks all

Jul 22, 15:54:45 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match michal m user email: michal@theaudiohunt.com. Add michal@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
-- | -- | -- | -- | --
Jul 22, 15:54:44 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Oscar G user email: oscar@studioassistant.io. Add oscar@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:44 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Alex Cernichiari user email: alex@studioassistant.io. Add alex@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:44 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match John Flores user email: john@theaudiohunt.com. Add john@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:44 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Steve Bartlett user email: steve@theaudiohunt.com. Add steve@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:43 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match michal m user email: michal@theaudiohunt.com. Add michal@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:43 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Oscar G user email: oscar@studioassistant.io. Add oscar@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:43 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Alex Cernichiari user email: alex@studioassistant.io. Add alex@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:43 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match John Flores user email: john@theaudiohunt.com. Add john@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:42 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Steve Bartlett user email: steve@theaudiohunt.com. Add steve@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:42 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match michal m user email: michal@theaudiohunt.com. Add michal@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:42 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Oscar G user email: oscar@studioassistant.io. Add oscar@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:42 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Alex Cernichiari user email: alex@studioassistant.io. Add alex@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:42 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match John Flores user email: john@theaudiohunt.com. Add john@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:41 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match Steve Bartlett user email: steve@theaudiohunt.com. Add steve@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address. | Studio Assistant Support
Jul 22, 15:54:41 | Oscar G | Error fetching email | Sender address support@studioassistant.io does not match michal m user email: michal@theaudiohunt.com. Add michal@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.

Jul 22, 15:54:45	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match michal m user email: michal@theaudiohunt.com. Add michal@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:44	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Oscar G user email: oscar@studioassistant.io. Add oscar@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:44	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Alex Cernichiari user email: alex@studioassistant.io. Add alex@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:44	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match John Flores user email: john@theaudiohunt.com. Add john@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:44	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Steve Bartlett user email: steve@theaudiohunt.com. Add steve@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:43	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match michal m user email: michal@theaudiohunt.com. Add michal@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:43	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Oscar G user email: oscar@studioassistant.io. Add oscar@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:43	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Alex Cernichiari user email: alex@studioassistant.io. Add alex@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:43	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match John Flores user email: john@theaudiohunt.com. Add john@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:42	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Steve Bartlett user email: steve@theaudiohunt.com. Add steve@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:42	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match michal m user email: michal@theaudiohunt.com. Add michal@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:42	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Oscar G user email: oscar@studioassistant.io. Add oscar@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:42	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Alex Cernichiari user email: alex@studioassistant.io. Add alex@studioassistant.io to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:42	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match John Flores user email: john@theaudiohunt.com. Add john@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:41	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match Steve Bartlett user email: steve@theaudiohunt.com. Add steve@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.	Studio Assistant Support
Jul 22, 15:54:41	[Oscar G](https://help.studioassistant.io/users/profile/7)	Error fetching email	Sender address support@studioassistant.io does not match michal m user email: michal@theaudiohunt.com. Add michal@theaudiohunt.com to user's Alternate Emails in the users's profile to allow the user reply from this address.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L821

FreeScout fetches emails and determines them as replies to email notifications from support agents. But "From" fields in those emails do not match support agents' emails in your FreeScout. 

Have you checked what do these emails look like:

> Jul 22, 15:54:41 [Oscar G](https://help.studioassistant.io/users/profile/7) Error fetching email Sender address [support@studioassistant.io](mailto:support@studioassistant.io) does not match michal m user email: [michal@theaudiohunt.com](mailto:michal@theaudiohunt.com). Add [michal@theaudiohunt.com](mailto:michal@theaudiohunt.com) to user's Alternate Emails in the users's profile to allow the user reply from this address.

**Comment by steveb85** [comment]
@freescout-help when i look at the inbox for support@studioassistant.io there is no email to fetch, which is the odd thing? it also seems this isn't fixed i awoke to another 8k emails...

**Comment by steveb85** [comment]
and i had removed the password from the fetch emails setting so clearly i was wrong on this being the cause...

**Comment by icwt-2024** [comment]
I'm having the same issue.. as I noticed now it's been going on for a while ... filled up 100G+ space on the email server

**Comment by steveb85** [comment]
are you using microsoft office 365 as mail server @icwt-2024 ?

**Comment by icwt-2024** [comment]
no I'm using gmail as SMTP 
connection via IMAP "unsecure app"

**Comment by icwt-2024** [comment]
I think I've found something... 
the notifications are handled on user level as well, and I've noticed for one of the users in question had some email notification on. 

so if a notification went out to an alias, freescout picked it up as a new msg, and sent out as a new notification ... and rinse and repeat .. .

**Comment by freescout-help** [comment]
Make sure:
- You don't have auto responders configured for support@studioassistant.io email.
- There is no forwarding from support@studioassistant.io to oscar@studioassistant.io configured and vice versa.

**Comment by raramuridesign** [comment]
We had a similar issue, I can confirm the forwarding and auto responders was a major headache!
