### ISSUE TITLE
Using solely the new imap php-implementation "Show original" does not work.

### ISSUE THREAD

**Issue by cluster15** [freescout-help-desk/freescout#4145]
We are are using the new php-imap implementation for quite a while now, without any major issue. The only thing that does not work is "Show original", it throws an error: 

error 	production 	2024-07-16 16:18:06 	
Call to undefined function App\Misc\imap_rfc822_parse_headers() {"userId":1,"email":"annymous@somemail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined function App\\Misc\\imap_rfc822_parse_headers() at /data/HELPDSKBIOPHYS/app/Misc/Mail.php:645) 

Turns out, that imap_rfc822_parse_headers() is a leftover call to a function implemented in the old imap-module. 

The attached patch helps me. I do not know whether this is the correct way of doing it. 

PHP version: 8.3
FreeScout version:  8.147
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Make sure you have `IMAP` extension enabled in your PHP.

**Comment by cluster15** [comment]
The whole point of having the new imap-access library (that I think you made it the default) is not having to use the old imap-extension anymore. And as I said it already works here quite flawlessly. I'll include the patch file here, it did not work in the first version of the report. 

[app-misc-mail-php.patch.txt](https://github.com/user-attachments/files/16363156/app-misc-mail-php.patch.txt)

**Comment by freescout-help** [comment]
`IMAP` extension will be always required.

**Comment by cluster15** [comment]
It will in the long run kill freescout because the imap-extension is abandoned for 15 years now and will in the long not work with modern openssl - implementations. It will drop out of distributions and simply not be available anymore. 

But anyway you should then specify better what is in our release notes for 1.8.140 meant by: 

[1.8.140](https://github.com/freescout-help-desk/freescout/releases/tag/1.8.140)

If after installing this release fetching does not work, go to mailbox Fetching settings and try other "Encryption" methods (see https://github.com/freescout-helpdesk/freescout/issues/4002#issuecomment-2118638402).

Changed

    Switch to the new fetching library (Webklex/php-imap).

I thought Webklex/php-imap is a php-only implementation of the imap-access provided by the imap-extension.

**Comment by freescout-help** [comment]
FreeScout uses and will continue to use imap-extension functions: https://github.com/freescout-help-desk/freescout/blob/dist/app/Jobs/SendReplyToCustomer.php#L521

There was no announcements that imap-extension can be dropped now - it's listed in the list of required extensions.

**Comment by cluster15** [comment]
I did not write that you dropped the support for the imap-extension but that with 1.8.140 the new Webklex/php-imap was made the default. BTW how do you explain that our installation of freescout happily works without the imap-extension present: 

[FreescoutwithoutImapExtension](https://github.com/user-attachments/assets/c5298cd3-27c1-4e5f-be1a-ea0cff81b070)

**Comment by freescout-help** [comment]
FreeScout works without imap-extension but some features not: https://github.com/freescout-help-desk/freescout/issues/4145#issuecomment-2248115724
