### ISSUE TITLE
Workflows:  Email the Customer question

### ISSUE THREAD

**Issue by MarianBMI** [freescout-help-desk/freescout#4149]
Hi, 
Is the email sent through the "Email the Customer" Action considered as a user reply when using "last user reply" condition? 
As far as I can see it looks like it but not all the times. 
I need a confirmation since I will need to think of a workflow that would suit my needs.

THanks!

PHP version: PHP 8.0.30
FreeScout version: 1.8.141
Database: Mysql (10.6.16-MariaDB-0ubuntu0.22.04.1)
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
For "Waiting Since" and "Last User Reply" replies created by Workflows are considered to be support agent replies.

**Comment by jmcclelland** [comment]
Yes - I was surprised by this one. Our rule was "customer has not replied in 15 days" then close it. So, when I opened an email to the customer, workflow immediately closed it because there was no customer reply yet.  We added a new "and" condition: issue is more than 15 days old to resolve it.

**Comment by freescout-help** [comment]
> Yes - I was surprised by this one. Our rule was "customer has not replied in 15 days" then close it. So, when I opened an email to the customer, workflow immediately closed it because there was no customer reply yet. We added a new "and" condition: issue is more than 15 days old to resolve it.

This "feature" has been implemented by @MarianBMI request. We've just reverted it in Workflows Module v1.0.71.
