### ISSUE TITLE
I have multiple Mailbox and i want to disable "Fetching Emails" for one of Mailbox

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4150]
Hi @freescout-help-desk 

I have multiple Mailbox and i want to disable "Fetching Emails" for one of Mailbox, but i want to keep "Sending Emails" setting on. How can i do it?

<img width="478" alt="Screenshot 2024-07-26 at 9 42 32 AM" src="https://github.com/user-attachments/assets/77f16d58-0620-46cb-b34f-4caf014a446f">

Thank You.

**Comment by freescout-help** [comment]
Simply remove the Password from Fetching settings.

**Comment by mahavirn** [comment]
Thanks @freescout-help-desk
