### ISSUE TITLE
Microsoft365 - forced SMTP replacement

### ISSUE THREAD

**Issue by AB-random** [freescout-help-desk/freescout#4151]
Version 1.8.147

Outgoing SMTP credentials are being overwritten automatically with Fetch mail credentials, not giving the ability to use different SMTP server.

**Comment by AB-random** [comment]
#4084 -> Mail.php replaced with mail.zip available in the thread does not work.

**Comment by freescout-help** [comment]
Try to enable Fetching first and after that configure your custom SMTP.

**Comment by AB-random** [comment]
Dear Freescout-Help-Desk/Freescout Team,

Already Tried, doesn't work.

The moment microsoft authentication (connect) is done at the fetch side,
the SMTP is overwritten and change is disabled unless disconnected. After
disconnecting, Fetch stops working.

Additionally the suggested workaround is not a very clean and professional
solution. It is better to disconnect both and have both work independently.

I also saw that there was a request on the thread by the development team
for Microsoft accounts for testing, if still required, I can set up an
independent domain with email accounts for your team to properly solve the
issue and for future as well.

Your solution is very good and allows a lot many possibilities that other
SaaS ticketing solutions do not. I would love to contribute however, I have
not programmed for the last 15+ years, I would however contribute in any
other capacity that you may direct.

Best Regards

**Comment by AB-random** [comment]
> SMTP username and password should not be disabled. Unless your SMTP Server name contains `.office365.com`. Or you are using not the latest FreeScout version.
> 
> What is your SMTP host name? Does it contain `.office365.com` in it?

Yes it does, but even as it does thats not an accepted behavior logically.

**Comment by freescout-help** [comment]
So what SMTP server are you using? Is it on premise MS365 or some custom SMTP? Does your SMTP host name look like "abc.office365.com" or "outlook.office365.com"?

We need to figure out how to adjust the condition https://github.com/freescout-help-desk/freescout/blob/master/app/Http/Controllers/MailboxesController.php#L949

**Comment by AB-random** [comment]
It is smtp.office365.com which gets overwritten. IMAP and SMTP should work
independently, an admin shall have the ability to change or play with
various settings. The moment the system sees imap settings to be from
office365 it jumps and overrides the smtp credentials.

Implementation Senarios:-
1) Microsoft still allow SMTP to operate normally, the administrator may
choose to use that while still using office365 via imap and
azure/identities authentication.
2) The Administrator may have the need to route the outgoing mails from a
non Microsoft SMTP like Amazon or some other third party.
3) The Administrator may need to have an in between sitting server, in
between Microsoft and Email Client (Freescout in this case) for various
technical/legal or administrative purposes of the organization.

Anyways, we moved away from Freescout and had to discard the server.

All purchased licenses stand as a waste for now.

Best of luck to you guys, looking forward to a more stable experience with
future release for next deployment sometime in the future.
