### ISSUE TITLE
User photo size at pikapods

### ISSUE THREAD

**Issue by astick360** [freescout-help-desk/freescout#4152]
Hello, I found information that to change the size of the profile photo you need:

> How can I make user photo size larger than 50px?
> You can do so via APP_USER_PHOTO_SIZE variable in .env file (don't forget to clear cache after setting it).

Only how to do it with the application hosted at pikapods.com?

**Comment by freescout-help** [comment]
APP_USER_PHOTO_SIZE and APP_CUSTOMER_PHOTO_SIZE should be available in Pikapods panel now.

**Comment by astick360** [comment]
The APP_USER_PHOTO_SIZE and APP_CUSTOMER_PHOTO_SIZE variables are available to enter. However, after loading the photo, it still displays at 50/50px.

**Comment by freescout-help** [comment]
Clear cache in "Manage > System > Tools".

**Comment by m3nu** [comment]
We've added this information to our FAQ too. That's linked next to each pod.

https://docs.pikapods.com/apps/freescout
