### ISSUE TITLE
How to change color of ACTIVE users and INVITED users and DISABLED users

### ISSUE THREAD

**Issue by jshrek** [freescout-help-desk/freescout#4153]
This is just a quick "How to" tutorial if you want to change the colors of the different types of users on the MANAGE > USERS page.

**Step 1**
Purchase and activate the **Customization & Rebranding** module which will allow you to add custom CSS.

**Step 2**
Go to MANAGE > SETTINGS then CUSTOMIZATION

**Step 3**
Add the following CSS in the Custom CSS box and save it:

```
/* change background color of ACTIVE users */
a.card.hover-shade { background-color:#50C878; }

/* change background color of INVITED users */
a.card.hover-shade.card-inactive { background-color:lightyellow; }

/* change background color of DISABLED users and color of NOT INVITED glyph */
a.card.hover-shade:has(> i.invite-state.not-invited.glyphicon.glyphicon-ban-circle) { background-color:#FF7518; }
a.card.hover-shade > i.invite-state.not-invited.glyphicon.glyphicon-ban-circle { background-color:yellow; }
```

**Step 4**
Go to MANAGE > USERS and behold your beautiful creation!
![users](https://github.com/user-attachments/assets/c003e559-317f-4932-9b12-c0d00f27146f)

**Comment by freescout-help** [comment]
Thanks for sharing it.
