### ISSUE TITLE
Issue with HTMLPurifier

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4154]
Hi @freescout-help-desk 

Please check below issue, i am not able to open the ticket, and its keeps redirecting....

```
Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) {"userId":1,"email":"any@any.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at freescout/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Zipper.php:155)[stacktrace] #0 {main} "}
```

Thanks!

**Comment by freescout-help** [comment]
The error is self-explanatory. Your server does not have enough memory to process the message.
Either increase the memory available to PHP or check the email to figure out why it's so big.

**Comment by mahavirn** [comment]
Okay @freescout-help 

Kept you in loop just to make sure its not an issue from FreeScout for larger emails.
