### ISSUE TITLE
1.8.147 - No "Connect" button for Microsoft Exchange OAuth2

### ISSUE THREAD

**Issue by natechoiniere** [freescout-help-desk/freescout#4156]
PHP version: 8.3
FreeScout version: 1.8.147
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

Looking to connect my Microsoft Exchange inbox, and while following the tutorial to set up OAuth, I found that there is no "Connect" button for me to set up OAuth with. I believe this feature was originally added somewhere around 1.8.9x

Here's what it looks like:
![image](https://github.com/user-attachments/assets/cd54de2d-685a-4e70-86c0-f5378047a232)

**Comment by freescout-help** [comment]
See Step 4 at https://github.com/freescout-help-desk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth#fetching-emails
