### ISSUE TITLE
which module allows you to add multiple task performers?

### ISSUE THREAD

**Issue by scadariz** [freescout-help-desk/freescout#4157]
which module allows you to add multiple task performers?

**Comment by freescout-help** [comment]
There is only Teams Module: https://freescout.net/module/teams/

**Comment by scadariz** [comment]
I don't need a team. 
In each ticket, I want to add several different people for execution.
Each time there is a new squad, for this you need to create more than 50 teams.

This is not appropriate. It is necessary to choose people from the list.

**Comment by scadariz** [comment]
> Есть только модуль команд: [https://freescout.net/module/teams /](https://freescout.net/module/teams/)

I don't need a team. 
In each ticket, I want to add several different people for execution.
Each time there is a new squad, for this you need to create more than 50 teams.

This is not appropriate. It is necessary to choose people from the list.

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).
