### ISSUE TITLE
Some emails imported as [invalid_address@.syntax-error]

### ISSUE THREAD

**Issue by VacationTeam** [freescout-help-desk/freescout#4158]
I have some emails I generate from our CRM and send to our email box ( we create them and control the addition of hears using SENDMAIL in PHP.

They import to scout as [invalid_address@.syntax-error]
![image](https://github.com/user-attachments/assets/e51f63d4-c1a6-422d-8752-220890abdf6e)

What could be causing this?
The headers look good in GMAIL
![image](https://github.com/user-attachments/assets/672df9e3-7d4c-4dac-819c-13f9d300c41d)

PHP version: 8.1.29
FreeScout version: 	1.8.146
Database: MySQL 
Are you using CloudFlare: Yes
Are you using non-official modules:  No

Thank you for your help

Edited to correct some grammar and spelling

**Comment by freescout-help** [comment]
Feel free to share EML file of the email or send it to support@freescout.net

**Comment by VacationTeam** [comment]
EML shared via email to Support

**Comment by freescout-help** [comment]
The problem is `Reply-To: <>` - it has an invalid value.

**Comment by VacationTeam** [comment]
That Fixed It.
Thank you for the fast reply
