### ISSUE TITLE
Failure fetching emails - invalid date

### ISSUE THREAD

**Issue by gino0631** [freescout-help-desk/freescout#4159]
If an email contains invalid date header, like (note the whitespaces below, which obviously get treated as folding):
```
Date: Thu, 1 Aug 2024 10:55:28 +0300
    Precedence: bulk
    Auto-Submitted: auto-replied
```
an error is logged in the "Fetch Errors" log:
```
Invalid message date. ID: Date:Thu, 1 Aug 2024 10:55:28 +0300 Precedence: bulk Auto-Submitted: auto-replied ...
```
and the conversation is not created. Moreover, and that is the worst, other unread (and technically correct) emails present in the mailbox at the same time are marked as read, and no conversations are created from them (obviously because of the error in processing of the first email).

The desired behaviour is: 1) incorrect headers should be ignored, if that is possible (in this case, current date could be used in place of the message date), and 2) technically incorrect emails should not prevent fetching and processing of other emails.

PHP version: 8.2.19
FreeScout version: 1.8.147
Database: PostgreSQL 13.7
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Can you share the EML file of the email or send it to support@freescout.net

**Comment by freescout-help** [comment]
Both issues fixed in the `master` branch and will be published in the next release.

**Comment by gino0631** [comment]
Thanks!

> Can you share the EML file of the email or send it to [support@freescout.net](mailto:support@freescout.net)

Do you still need EML file of the email? We can not share the original email because it contains personal data, but I could try to prepare a similar one to reproduce the problem, if that is still necessary.

**Comment by freescout-help** [comment]
It's not needed anymore.
