### ISSUE TITLE
Replies to forwarded conversations end up in original conversation 

### ISSUE THREAD

**Issue by OneTwo3D** [freescout-help-desk/freescout#4161]
PHP version: 8.1
FreeScout version: 1.8.147
Database: MySQL 
Are you using CloudFlare: Yes 
Are you using non-official modules:  No

Hi,
When forwarding a ticket to a third party, the forwarded thread is correctly opened but replies by this third party don't end up in the separate thread but in the main thread. Is there something I need to configure to fix that?

**Comment by freescout-help** [comment]
We can't reproduce the issue. Some screenshots may be helpful.

**Comment by OneTwo3D** [comment]
Hi,
Here some screenshots:
https://photos.app.goo.gl/qfDuyUv7kzMBUmiY6

https://photos.app.goo.gl/ZAGzRaVxvWddA1hF9

First one shows the original thread with forwarded email and response from the third party in the main thread. Second one is the thread generated by forwarding the email but the reply hasn't been added to that one.

**Comment by freescout-help** [comment]
We still can't figure it out. Write a step-by-step instruction on how to reproduce the issue.

**Comment by OneTwo3D** [comment]
I received an email from a customer in the inbox, forwarded this email via the "forward" function in freescout to a third party. This created a separate thread in the inbox. The third party replied to this forwarded email. The reply got added to the original thread instead of the new one generated by the forwarded email.

**Comment by freescout-help** [comment]
We can't reproduce it on our end. Are you able to reproduce it or it happened with just one email?

**Comment by OneTwo3D** [comment]
Hi,
I can't reproduce it either: when I generate a test conversation it works as intended. 

But in "real life" customer conversations the replies to forwarded messages end up in the wrong thread and I have no idea why that's happening.

**Comment by freescout-help** [comment]
What email client or ticketing system those customers are using?

**Comment by OneTwo3D** [comment]
The affected third party Recipient seems to be using qqmail.

**Comment by OneTwo3D** [comment]
Hi,
It is still happening for "real support" cases. I don't know why it works fine when I try to reproduce it myself, but as soon as "real" customer emails are getting involved, the separation in two threads stops working.

**Comment by freescout-help** [comment]
If someone will manage to reproduce it and fix - please submit a pull request.

**Comment by OneTwo3D** [comment]
Hi, the issue is still existing. It would be great if this could be fixed somehow, as it makes forwarding emails to 3rd parties really difficult (if their reply ends up in the main email thread and is then sent out to the customer with the next reply to the main thread).
