### ISSUE TITLE
downloading attachment = "Access Denied, Go To Homepage"

### ISSUE THREAD

**Issue by iceryan354** [freescout-help-desk/freescout#4162]
-->

Running most recent version on a hetzner vm with all permissions green.
PHP version: 8 2 18
FreeScout version: 1 8 147
Database: MySQL 
Are you using CloudFlare:  no
Are you using non-official modules:  no

Love the product and running many official add ons.
inline images never show and although i see attachments are actually on the server from people sending them to us, i am never able to download them, getting an access denied page - and i am not able to upload attachments or images either. "seems like" permissions issue but everything is green on system page and no strange issues in log.
i notice the link for an example attachment is:
https://example.com/storage/attachment/0/6/1/example.pdf?id=198&token=4ce0863adfcc0044104f8afec1fcf5ab
which results in access denied
and i notice on server its actually located in /storage/app/attachment..... but adjusting url still doesnt bring it up...
nothing else running on this vm or wan ip....

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#attachments-are-showing-access-denied-message
