### ISSUE TITLE
Feature Request: RMM intergrations

### ISSUE THREAD

**Issue by Brandon-Roff** [freescout-help-desk/freescout#4165]
I am raising this if there could be an intergration made for RMM's like 

Ninja
Datto
Tactical RMM 
Remtotely 

And auto resolve alerts when issues are resolved in the RMM's, in addition to Maybe sync information back and forth,  devices lists with device info, webhooks to remote on, minor stats about machines like storage stats ect

**Comment by freescout-help** [comment]
There are no such integrations for now. Feel free to [submit a feature request](https://freescout.net/request-feature/).
