### ISSUE TITLE
Cron Job Not Fetching

### ISSUE THREAD

**Issue by jeskremer** [freescout-help-desk/freescout#4168]
I know this has been discussed in a few previous threads and supposedly resolved, but I have been banging my head on the wall trying to get fetching to work for a few weeks now.  

We have the cron job setup on the server (VPS).  I confirmed tonight that all of the logs are showing it running, however, I can not received IMAP emails unless I go to System and Fetch manually.

Any suggestions are greatly appreciated.  I really want to utilize this software and add a bunch of modules to it.

Thank you.

**Comment by jeskremer** [comment]
Yes, I’ve got someone else looking into it now.  It is an issue with the .env file and QUEUE connection not setting up correctly in the automatic download from Softaculous.

**Comment by freescout-help** [comment]
Let us know if you'll find out the reason.
