### ISSUE TITLE
SMTP Authentication Fails with "0 Possible Authenticators" Error in FreeScout

### ISSUE THREAD

**Issue by Jaggob** [freescout-help-desk/freescout#4170]
I am encountering an issue with sending emails from FreeScout. The system fails to authenticate with the SMTP server, returning an error: "Failed to authenticate on SMTP server with username "5465rf7tuzb@stura-tuebingen.de" using 0 possible authenticators."

Logs say:
"Failed to authenticate on SMTP server with username "5465rf7tuzb@stura-tuebingen.de" using 0 possible authenticators. {"exception":"[object] (Swift_TransportException(code: 0): Failed to authenticate on SMTP server with username \"5465rf7tuzb@stura-tuebingen.de\" using 0 possible authenticators. at /var/www/html/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:191)
[stacktrace]
#0 /var/www/html/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo()
#1 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#2 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\\Mail\\Mailable->send()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\\Mail\\Mailer->sendMailable()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\\Mail\\Mailer->send()
#9 /var/www/html/app/Jobs/SendNotificationToUsers.php(148): Illuminate\\Mail\\PendingMail->send()
#10 [internal function]: App\\Jobs\\SendNotificationToUsers->handle()
#11 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#12 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#26 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#28 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#30 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#32 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#34 /var/www/html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#35 /var/www/html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#36 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#39 /var/www/html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#40 {main}
"}"

Other Mailboxes using other Mailservers do work, the error only occurs on this specific SMTP Server.

PHP version: PHP 8.0.30
FreeScout version: 1.8.147
Database: Mysql (8.0.36-0ubuntu0.20.04.1)
Are you using CloudFlare:  No
Are you using non-official modules: No

I updated from FreeScout version: 1.8.143 few days ago. Noticed the error today when tried to send a mail from this server so guess it has something to do with #4084 ?

Thanks a lot for help! Please let me know if any additional details are required.

**Comment by freescout-help** [comment]
Release 1.8.144 is related only to Microsoft 365 SMTP account. Are you using MS365 or have you connected your SMTP via oAuth somehow?

**Comment by Jaggob** [comment]
I am not using Microsoft 365 and have not connected my SMTP via OAuth. Instead, I am using the traditional method with a username and password for authentication. 
I have installed the OAuth & Social Login Module plugin but guess that has nothing to do with this problem?

Here's the SMTP log from the Sending Emails section:

++ Starting Swift_SmtpTransport
<< 220 zucker.schokokeks.org ESMTP

>> EHLO mails.vs-tuebingen.de

<< 250-zucker.schokokeks.org Ok.
250-AUTH PLAIN
250-XCOURIEREXTENSIONS
250-XVERP=Courier
250-XEXDATA
250-XSECURITY=NONE,STARTTLS
250-PIPELINING
250-8BITMIME
250-SMTPUTF8
250-SIZE
250 DSN

**Comment by freescout-help** [comment]
It's not clear what can be the reason of the issue. Someone may need to check it on your server.

https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer

**Comment by bekre10** [comment]
I have the same issue after the recent update to 1.8.148.
It worked fine before and still does for customers using an older version of FreeScout.
We use M365 OAUTH credentials to send out emails.

**Comment by Jaggob** [comment]
@freescout-help thanks for the answer anyway! We only used the affected server for one mailbox anyway and have now moved it to another mail server and solved the problem for us.

@bekre10 your error message looks more like the problem described and solved here: #4173
