### ISSUE TITLE
Attachments are not opening in new Tab

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4171]
Hi @freescout-help-desk 

I checked the source code and there is `target="_blank"` statement, but while rendering attachment in Mailbox, that is removed, and Attachment link opens in same tab instead of new tab.

Can you please look into this issue.

Thank You.

**Comment by freescout-help** [comment]
It's not clear what you are talking about. Can you attach few screenshots.

**Comment by mahavirn** [comment]
Hi @freescout-help-desk 

Below is the Attachment:

<img width="548" alt="Screenshot 2024-08-08 at 11 07 21 AM" src="https://github.com/user-attachments/assets/1ca66a26-4e3b-4ff7-b3dc-76bce533d884">

When i am clicking on it, instead of opening in new tab, it opens in current tab.

**Comment by freescout-help** [comment]
We can't reproduce the issue. Disable all non-official modules or customizations you are using.

**Comment by mahavirn** [comment]
I am only using modules which are provided by FreeScout.

**Comment by freescout-help** [comment]
You may need to find someone who can investigate it on your server.
https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer
