### ISSUE TITLE
Conversations list - blurried line

### ISSUE THREAD

**Issue by carlozleite** [freescout-help-desk/freescout#4172]
Hello

I installed the TAGS and CUSTOM FOLDERS modules, but I noticed that the rendering of conversations is obfuscated in half of the table with a blurred line that prevents the entire title of the conversation from being displayed.

![image](https://github.com/user-attachments/assets/d508355a-5a05-46a1-aac5-d36106949d2c)

PHP version: 8.2.1
FreeScout version: 1.8.146
Database:PostgreSQL
Are you using CloudFlare: Yes 
Are you using non-official modules: No

**Comment by freescout-help** [comment]
It's not related to modules. This is how it looks by default. If someone can fix it - please submit pull request.
