### ISSUE TITLE
Could the composer.json be updated to not require the `--ignore-platform-reqs`?

### ISSUE THREAD

**Issue by Mythique** [freescout-help-desk/freescout#4174]
Could the composer.json be updated to not require the `--ignore-platform-reqs`?

It's a bit too error prone, and messes up some workflow (for example the git deployment in plesk, it automatically try to run composer install, but fail and break the website until the proper commands are run manually).

_Originally posted by @Mythique in https://github.com/freescout-help-desk/freescout/issues/4033#issuecomment-2243074111_

**Comment by freescout-help** [comment]
Unfortunately not.

**Comment by Mythique** [comment]
For anyone finding this issue because they use plesk, I ended up fixing the git deployment process.

- Access the laravel module associated to your website
- In the deployment section make sure to uncheck `4. Install composer.json dependencies`
- Click the "edit script" button and write something like this (change the php version to the one that is available):
```
/opt/plesk/php/8.3/bin/php /usr/lib/plesk-9.0/composer.phar install --ignore-platform-reqs
/opt/plesk/php/8.3/bin/php artisan freescout:after-app-update
```

Automatic deployment should now work without errors.
