### ISSUE TITLE
IMAP - No unseen emails (because of " around date in query"

### ISSUE THREAD

**Issue by skilltryck** [freescout-help-desk/freescout#4175]
PHP version: 7.4/8.3
FreeScout version: 1.8.148
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

After upgrading to 1.8.148 no new emails came.
After troubleshooting some time I found the problem to be with the query to our IMAP server.

UID SEARCH SINCE "7-Aug-2024" UNSEEN returned empty
UID SEARCH SINCE 7-Aug-2024 UNSEEN returned correctly

Changed in overrides/webklex/php-imap/src/Query/Query.php
```
if (is_numeric($statement[1])) {
  $query .= $statement[0] . ' ' . $statement[1];
} else {
  $query .= $statement[0] . ' "' . $statement[1] . '"';
}
```

to:
```
if (is_numeric($statement[1])) {
  $query .= $statement[0] . ' ' . $statement[1];
 } else if ($statement[0] == 'SINCE') {
  $query .= $statement[0] . ' ' . $statement[1];
} else {
  $query .= $statement[0] . ' "' . $statement[1] . '"';
 }
```

Is a workaround for me.
There is probably a much better solution though...

**Comment by freescout-help** [comment]
Which mail server are you using?

**Comment by freescout-help** [comment]
We've noticed that your date `7-Aug-2024` is missing leading zero.

Try to hardcode the following and check if this is the reason of your issue:
```
} else if ($statement[0] == 'SINCE') {
  $query .= $statement[0] . ' "07-Aug-2024"';
```

**Comment by skilltryck** [comment]
> Which mail server are you using?

Using an old server, Eudora Internet Mail Server.

**Comment by skilltryck** [comment]
> We've noticed that your date `7-Aug-2024` is missing a leading zero.
> 
> Try to hardcode the following and check if this is the reason of your issue:
> 
> ```
> } else if ($statement[0] == 'SINCE') {
>   $query .= $statement[0] . ' "07-Aug-2024"';
> ```

Same problem.
Still works without quotes around the date.

Looks in RFC that dates following SINCE is used without quotes.
https://www.rfc-editor.org/rfc/rfc3501

**Comment by freescout-help** [comment]
We've changed it in the `master` branch. It will be published in the next release.

**Comment by freescout-help** [comment]
Did you have some error in logs when the date was enclosed in quotes?

**Comment by skilltryck** [comment]
> Did you have some error in logs when the date was enclosed in quotes?

No errors, just wrong result. 
Instead of returning UIDs of UNSEEN messages I got an empty response from IMAP-server.

**Comment by freescout-help** [comment]
Starting from FreeScout v1.8.150 you need to set `APP_SINCE_WITHOUT_QUOTES_ON_FETCHING=true` parameter in the .env file and clear cache.
