### ISSUE TITLE
Issue with FreeScout "Extend Attachment" Extension - Images Not Displaying

### ISSUE THREAD

**Issue by groovelikeapig** [freescout-help-desk/freescout#4176]
Hello FreeScout team,

I hope you're doing well. I'm currently using FreeScout and have encountered an issue with the "Extend Attachment" extension that I was hoping you could assist with.

I installed the "Extend Attachment" extension to allow for the display of images directly within the emails. However, I've noticed that when I receive emails with image attachments, the images do not appear as expected. Instead of displaying the images, they are either not shown at all or appear as broken links. This has been quite frustrating, and I'm unsure of how to resolve the issue.

Could you please advise on what might be causing this problem? Is there something specific I need to configure or check to ensure that the images are displayed correctly? I'm using the latest version of FreeScout, and I've already tried clearing the cache and disabling/re-enabling the extension, but the issue persists.

Any guidance or suggestions you could provide would be greatly appreciated. Thank you in advance for your help, and I look forward to your response.

Best regards,

Johann

<img width="1880" alt="Capture d’écran 2024-08-12 à 17 43 26" src="https://github.com/user-attachments/assets/35f59242-adfe-40d3-869a-d620d3a25ce6">

<img width="1880" alt="Capture d’écran 2024-08-12 à 17 43 26" src="https://github.com/user-attachments/assets/1ad27c27-78cb-45b0-a01f-b41e2e3b8f33">

PHP version: 
FreeScout version: 
Database: MySQL / PostgreSQL
Are you using CloudFlare: Yes / No
Are you using non-official modules: Yes / No

**Comment by groovelikeapig** [comment]
I wanted to add some more information to the issue I previously reported regarding the "Extend Attachment" extension.

In addition to the images not displaying within the emails, I've also noticed that when I try to download JPEG or PNG files from the attachments, the download process fails. When I click to download the image files, nothing happens—no download starts, and there’s no error message or indication of what might be wrong. This is further complicating the situation as I can’t access the images at all.

I've attached a screenshot to help illustrate the problem.

Could you please look into this issue as well? Any advice on how to resolve both of these issues would be greatly appreciated.

Thanks again for your support.

Best regards,

Johann

<img width="1900" alt="Capture d’écran 2024-08-12 à 18 00 38" src="https://github.com/user-attachments/assets/0b079a10-75e9-44dd-ba36-83a7c76c0fb3">

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#-inline-images-do-not-display-and-attachments-lead-to-404-errors

**Comment by groovelikeapig** [comment]
Thank you very much.
