### ISSUE TITLE
Woocommerce add-on: not loading orders

### ISSUE THREAD

**Issue by OneTwo3D** [freescout-help-desk/freescout#4177]
PHP version:  8.1.29
FreeScout version: 1.8.148
Database: MySQL
Are you using CloudFlare: Yes
Are you using non-official modules: No

Hi,
I've installed and correctly connected the Woocommerce add-on, but it isn't loading any orders (the spinner comes up for a second and then it shows "no orders".

When entering the Woocommerce credentials on the settings page, it comes up with a success message.

**Comment by freescout-help** [comment]
You can try to find someone who can check it on your server https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer or email at support@freescout.net
