### ISSUE TITLE
Feature Recommendation (Not a request)

### ISSUE THREAD

**Issue by cakmapilot** [freescout-help-desk/freescout#4180]
I wrote a new field type in CustomFields module.

It's a multiple selectable dropdown.

Main Differences between Dropdown, Single Line Tags and Dropdown Multiple are:
Dropdown: You can't select multiple values from Dropdown. You can select multiple values from this new field.
Single Line Tags: You can't limit users to choose from pre defined choices. You can define choices instead of free text search and usage.

What should i do next?

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/FreeScout-Modules#5-modifying-modules
