### ISSUE TITLE
In Workflow Module, the dynamic values are not replaced in Subject

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4183]
Hi @freescout-help-desk 

In Workflow Module, the dynamic values are not replaced in Subject. Below is the example of same:

<img width="620" alt="Screenshot 2024-08-16 at 9 09 53 PM" src="https://github.com/user-attachments/assets/812e7249-c712-455b-8ac7-5c493f4012c2">

Is it bug or its intentional?

Thank You.

**Comment by freescout-help** [comment]
Variables can be used only in the message body.

**Comment by freescout-help** [comment]
You can try do implement it yourself or find someone https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer
