### ISSUE TITLE
Is it possible to create an user with an empty last name? 

### ISSUE THREAD

**Issue by planetahuevo** [freescout-help-desk/freescout#4184]
Just that.  What it says in the title.
Is it possible to create an user with an empty last name? 
:) 
I searched, read the docs and the faq, and maybe I missed it, because there was a lot of info, but I could not find anything related to that. 

Thanks

**Comment by freescout-help** [comment]
No.

**Comment by piegamesde** [comment]
Please reopen. Mononymous people (with only one name) exist, and per GDPR in Europe we are legally required to support this.

**Comment by freescout-help** [comment]
Implemented in the `master` branch and will be published in the next release.
