### ISSUE TITLE
Is there a way to pre-fill search field in knowledge base widget?

### ISSUE THREAD

**Issue by cweagans** [freescout-help-desk/freescout#4185]
I'm using the official KB module. I have the widget embedded in my application. Is there a way to pre-fill the search field in the widget so that when a user clicks on the widget button, they have some search results that are relevant to the page they're currently looking at? Not sure if there's an option for that anywhere. If not, I can open a feature request -- just thought I'd double check here first in case the feature already existed.

**Comment by freescout-help** [comment]
There is no such feature for now.
