### ISSUE TITLE
Modules can not be installed, no Modules are displayed to install

### ISSUE THREAD

**Issue by markusbenkert** [freescout-help-desk/freescout#4190]
Still here? Well clean this out and go ahead :)
-->

PHP version: 8.2.22
FreeScout version: 1.8.150
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

Hello, I set up a fresh instance today using Docker Compose. However, I can't install any modules through the "Modules" menu because none are displayed. It only asks if I want to be notified when new modules are released.

**Comment by markusbenkert** [comment]
![Screenshot 2024-08-23 111500](https://github.com/user-attachments/assets/fbca41ff-c4db-4dd8-9ed2-f8e7248b1774)

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#11-troubleshooting
