### ISSUE TITLE
LDAP Connection Issue After Updating Certificates on Freescout Server

### ISSUE THREAD

**Issue by Sunshine8456** [freescout-help-desk/freescout#4192]
Hey,

We recently updated the certificates on our Freescout server, and the IMAP mail connection is working fine. However, since the certificate change, we are no longer able to establish an LDAP connection (to our Active Directory) through the LDAP module. After some time, we just get a connection timeout error. Disabling TLS encryption resolves the issue and allows the LDAP connection to work as expected. We're using Ubuntu 20.04, installed freescout with the install script

My questions are:

a) Are there any extended log files available for the LDAP module on the Freescout server that could provide more details?
b) Is there any other location where the old certificates may be stored and still being used by Freescout, instead of the new certificates?

I appreciate any insights or suggestions on how to resolve this LDAP connectivity problem after updating the server certificates.

Greetz
Dennis

PHP version: 8.1
FreeScout version: 1.8.145 
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Unfortunately the module can't provide any LDAP connection logs as PHP LDAP extension does not have this feature.

**Comment by Sunshine8456** [comment]
Thank you for the feedback. Since the PHP LDAP extension does not have the capability to provide detailed LDAP connection logs, that makes it more challenging to troubleshoot the issue.

Regarding question b) - are there any other locations where the old certificates might still be used by Freescout instead of the new ones? This could potentially be causing the LDAP connection problem, even though the IMAP mail connection is working fine with the new certificates.

**Comment by freescout-help** [comment]
> b) Is there any other location where the old certificates may be stored and still being used by Freescout, instead of the new certificates?

Who knows. Maybe PHP can do some caching.
