### ISSUE TITLE
Wrong search results

### ISSUE THREAD

**Issue by cashycash** [freescout-help-desk/freescout#4194]
When searching tickets with the specific keyword (example "A4R") I get conversations that do not contain the keyword.

**Comment by freescout-help** [comment]
Here are the fields where the search term is being searched: https://github.com/freescout-help-desk/freescout/blob/dist/app/Conversation.php#L2278

**Comment by cashycash** [comment]
Thanks for fast reply! That means "hidden" information is also searched like e.g. the body of the mail?

**Comment by freescout-help** [comment]
Yes.
