### ISSUE TITLE
Error: Undefined array key 1, emails not fetched

### ISSUE THREAD

**Issue by ybizeul** [freescout-help-desk/freescout#4195]
![image](https://github.com/user-attachments/assets/b8f99ed8-ab5c-4210-8053-c1f920c758b2)

I'm not able to determine what makes some emails not being fed into Freescout.

During my tests I was not able to break it, but a couple users email are not showing up.

Sending messages to you

PHP version: 8.2.22
FreeScout version: 1.17.82
Database: MySQL / ~PostgreSQL~
Are you using CloudFlare: ~Yes~ / No
Are you using non-official modules: ~Yes~ / No

**Comment by ybizeul** [comment]
Uh-owww.. Someone's been hacked.

**Comment by ybizeul** [comment]
But still there is code accessing an array out of bound, no clue what could cause this code path ?

I've been really happy with Freescout for the last couple of years and 4 or 5 months ago I started having many problems like that I hope it'll get better.

**Comment by freescout-help** [comment]
It's hard to tell what's on those line where you have an error. You've specified non-existing FreeScout version (1.17.82) and current Structure.php file does not have any code on those line.

**Comment by ybizeul** [comment]
Well, that's weird...

That wouldn't be this line then ? https://github.com/freescout-help-desk/freescout/blob/c0ce07a2b97473165d84f404d1b90f40a37b999c/overrides/webklex/php-imap/src/Structure.php#L151

As for the version : 
```
                                                                       ,---.
,--------.,--.                 ,--.            ,---.    ,--. ,--------.|   |
'--.  .--'`--',--.--. ,---.  ,-|  |     ,---. /  .-'    |  | '--.  .--'|  .'
   |  |   ,--.|  .--'| .-. :' .-. |    | .-. ||  `-,    |  |    |  |   |  |
   |  |   |  ||  |   \   --.\ `-' |    ' '-' '|  .-'    |  |.--.|  |   `--'
   `--'   `--'`--'    `----' `---'      `---' `--'      `--''--'`--'   .--.
                                                                       '--'
Image:  tiredofit/freescout | Version  1.17.82 Type 'image_changelog' for details
Repository/Documentation: https://github.com/tiredofit/docker-freescout/
License: MIT | © 2024 Dave Conroy

If this image provides you value  - Consider sponsoring my work for continued
development, timely updates, and feature requests. Commercial support available.

                    More Info:  https://www.tiredofit.ca
```

That would be a docker issue ?

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by ybizeul** [comment]
I can confirm it's now fetching emails.

Emails are empty, just like half of the emails I get anyways but that's a different issue.

I'm not sure I should reopen an issue, last time the blame was put on mail server or internet connection, really that's not the case but can't really prove it
