### ISSUE TITLE
Module request "Reply all" and "No auto open ticken on closed"

### ISSUE THREAD

**Issue by tomaswallentinus** [freescout-help-desk/freescout#4196]
Hi.

I would love to see two modules beeing developed.

One is for the merged tickets. If I click reply on it, only one of the respondents are selectable, If you want to answer everyone in a swope, you need to add them as CC. An added alternative to reply all would be great.

The other one is an checkbox to stop closed tickets to reopen if the customer reply with "Thank you" or something that is not a help request. Maby ability to add a email footer with info if you want to reopen the ticket please click here.

Regards Tomas

**Comment by freescout-help** [comment]
Feel free to [submit feature requests](https://freescout.net/request-feature/).
