### ISSUE TITLE
Additional URI required for Microsoft Entra

### ISSUE THREAD

**Issue by pkoutsolampros-decisal** [freescout-help-desk/freescout#4198]
Hi there, thanks for this great software!

I only have a suggestion for the wiki: When connecting with o365 I get:
> Error occurred refreshing oAuth Access Token: {"error":"invalid_client","error_description":"AADSTS50011: The redirect URI 'https://example.com/artisan/mailbox/oauth' specified in the request does not match the redirect URIs configured for the application

I added this URI to the Entra App configuration and it seems to have fixed it.

I assume that's enough, but is there another suggestion?

**Comment by freescout-help** [comment]
Can you attach screenshot of the Entra App configuration to help people find it.

**Comment by pkoutsolampros-decisal** [comment]
Apologies, "Entra" is the new name of the "Azure Active Directory" app you have in the wiki [here](https://github.com/freescout-help-desk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-OAuth#fetching-emails), and it's just step 1 that needs to be updated with an additional URL "https://yourdomain.com/artisan/mailbox/oauth". Here's the screenshot: 
![image](https://github.com/user-attachments/assets/681bce17-1f08-43e4-81b3-a23d35d4acd8)

**Comment by freescout-help** [comment]
It looks like your FreeScout is located in the subfolder. So you had to add your "/artisan/" subfolder to the Redirect URI.

**Comment by pkoutsolampros-decisal** [comment]
Indeed, that seems to be because I'm using the compose docker image from here: https://github.com/tiredofit/docker-freescout. @tiredofit perhaps this should be documented by you somewhere?
