### ISSUE TITLE
Error to Fetch via IMAP and Send through SMTP (GMAIL)

### ISSUE THREAD

**Issue by tp-edjunior** [freescout-help-desk/freescout#4199]
PHP version: 8.1.24
FreeScout version: 1.8.151
Database: MySQL / PostgreSQL: Mysql (8.0.39-cll-lve)
Are you using CloudFlare: Yes
Are you using non-official modules: No

I've noticed since August 23rd Freescout stopped fetching and send mails. The way to fetch is IMAP (imap.gmail.com) and to send is SMTP (smtp.gmail.com). No changes have been made.

There are some errors on app logs as follow:

fetch-emails.log
`2024-08-27 09:39:35 | connection failed - stream_socket_client(): Unable to connect to ssl://imap.gmail.com:993 (Connection timed out); File: /home/serviced/domains/servicedesk.textecnologia.io/public_html/freescout/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (85)`
-- | --
laravel-2024-08-23.log
`error | production | 2024-08-23 23:06:57 | Connection could not be established with host smtp.gmail.com [Connection timed out #110] {"exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host smtp.gmail.com [Connection timed out #110] at /home/serviced/domains/servicedesk.textecnologia.io/public_html/freescout/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:271)`
-- | -- 
```
error | production | 2024-08-23 22:06:27 | Connection could not be established with host smtp.gmail.com [Connection timed out #110] {"exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host smtp.gmail.com [Connection timed out #110] at /home/serviced/domains/servicedesk.textecnologia.io/public_html/freescout/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:271)
error | production | 2024-08-23 21:05:55 | Connection could not be established with host smtp.gmail.com [Connection timed out #110] {"exception":"[object] (Swift_TransportException(code: 0): Connection could not be established with host smtp.gmail.com [Connection timed out #110] at /home/serviced/domains/servicedesk.textecnologia.io/public_html/freescout/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:271)
```
-------
Fetch Errors

`Aug 27, 09:45:04 | Error fetching email | Error: connection failed - stream_socket_client(): Unable to connect to ssl://imap.gmail.com:993 (Connection timed out); File: /home/serviced/domains/servicedesk.textecnologia.io/public_html/freescout/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php (85)`
-- | -- | --

I've created a new account to test, no success.

I sustain three mailboxes on Freescout and the three accounts stopped working at the same time.

For the sake of curiosity, my printer uses the same strategy to send emails through smtp and it's working fine, so I'm discarding the possibility of any issue on Gmail SMTP/IMAP protocols.

I appreciate any kind of help.

Thanks in advance.

**Comment by freescout-help** [comment]
Try https://stackoverflow.com/a/28014425

**Comment by diogogpinto** [comment]
> Try https://stackoverflow.com/a/28014425

If this doesn't work, check if your hosting provider didn't disable access to the required external ports like 25, 465, or 587.

I had the exact same issue that occurred on a shared instance when some other user started abusing these connections to send SPAM and outside connections to the ports were blocked on the whole server to prevent it.

**Comment by tp-edjunior** [comment]
Hi guys.

The problem is now solved. It had an issue with the webhosting (Interserver) to reach de smtp.gmail.com address.

Thank you all.

**Comment by Geraldwithholding34** [comment]
@diogogpinto https://google-cloud-datastore-b.github.io/malloy/
