### ISSUE TITLE
Parsing problem, after downloaded message (upgrade 1.8.151)

### ISSUE THREAD

**Issue by janselato** [freescout-help-desk/freescout#4201]
PHP version:  8.2.22
FreeScout version: 1.8.151
Database: MySQL
Are you using CloudFlare No
Are you using non-official modules: No

Since updating to version 1.8.151, we've been encountering issues with email retrieval. Freescout is either failing to parse emails completely, removing all content, or adding a CSS code to the first line. We're pulling emails from a Gmail account. 
![2024-08-28_08-22](https://github.com/user-attachments/assets/3223a3e0-b186-40d3-904b-7353b8ca8eb5)
![original-allegro](https://github.com/user-attachments/assets/3fe62f14-3e1e-40dd-a8fc-31e75ef15d5f)

![2024-08-28_08-20](https://github.com/user-attachments/assets/af406254-e5b5-4903-b4ac-b6cae511e640)
![original-inpost](https://github.com/user-attachments/assets/9dcb8913-1c55-4e86-b1a3-d069bcbbe9c7)

**Comment by freescout-help** [comment]
Are you using POP3 or IMAP? Try FreeScout v1.8.152.

Also try to send sample emails to support@freescout.net

**Comment by janselato** [comment]
We are using IMAP. 
After upgrade to 1.8.152 problem resolved. Thanks
