### ISSUE TITLE
Feature discussion: Cross-Mailbox Inbox List for Agents

### ISSUE THREAD

**Issue by diogogpinto** [freescout-help-desk/freescout#4204]
I’m looking for a feature that would enhance agent efficiency and provide a more comprehensive view of their workload, in our usecase.

**Feature:**
A module that displays all conversations assigned to an agent across their various mailboxes.

**Current Situation:**
Currently, agents need to switch between different mailboxes to view and manage their assigned conversations. This can lead to reduced productivity and potential oversight of important communications.

**Proposed Solution:**
Implement a centralized view that aggregates all conversations assigned to an agent, regardless of the mailbox origin. This would provide a single point of access for agents to manage their workload efficiently.

**Questions for Consideration:**

1. Has a similar feature been implemented or considered before?
2. Would this be valuable as a global feature for the community?
3. Are there any potential performance limitations or concerns with implementing this feature?

**Potential Benefits:**

- Improved agent productivity
- Better workload management
- Reduced risk of overlooking important conversations

I believe this feature could significantly enhance the user experience for agents handling multiple mailboxes. I’d appreciate the community’s thoughts on the feasibility and potential value of this development.

I'm up to develop this internally and release it later to the community or PR to the core.

Thank you for considering this proposal.

**Comment by freescout-help** [comment]
Take a look at https://freescout.net/module/global-mailbox/

**Comment by diogogpinto** [comment]
@freescout-help I don't know how I missed that, but that's pretty much I was looking for.

Some thoughts (I'm thinking about extending the module once I buy it):

- Show which mailbox each conversation belongs to in the conversation list
- Hiding Global Mailbox from the dashboard list and showing link in the header
- Maybe limiting it to **my** global mailbox - only show my tickets (attributed to the logged in agent) and, in the sidebar, select by Active, Pending or Closed

Here are some thoughts I'm considering. If our team goes with it and we have the manpower to work this out, I will submit the source privately to you so you can considering extending the current module functionality.

Thank you for your incredible work!

**Comment by freescout-help** [comment]
> Show which mailbox each conversation belongs to in the conversation list

Mailboxes' names are already shown in square brackets under subjects.

**Comment by diogogpinto** [comment]
> > Show which mailbox each conversation belongs to in the conversation list
> 
> Mailboxes' names are already shown in square brackets under subjects.

That's great, missed that too. Sorry! Will try and extend the following functionality and let you know if maybe you want to add it to the module later.
