### ISSUE TITLE
Additional recipients not added to CC on reply

### ISSUE THREAD

**Issue by sofl88** [freescout-help-desk/freescout#4205]
I **cannot** reproduce this in the freescout demo (1.8.139).
When a email is recived with additional recipments (only tested with one CC address) and someone is about to write an answer, the CC address was automatically added to CC recipments in the reply. This behaviour seems lost (at least) in the latest version (1.8.152).

PHP version: PHP 8.0.3
FreeScout version: 1.8.152
Database: Mysql (10.5.26-MariaDB)
Are you using CloudFlare: No
Are you using non-official modules: Yes

Thanks in advance

**Comment by freescout-help** [comment]
We also can't reproduce the issue.
