### ISSUE TITLE
A custom developed module fails to show up in the modules list on the production server

### ISSUE THREAD

**Issue by sheikhumar93** [freescout-help-desk/freescout#4207]
PHP version: 8.2.14
FreeScout version: 1.8.152
Database: PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules: Yes

Hi all, first time Freescout developer here, this is my first time developing a custom module for Freescout. I completed the development on a local installation of Freescout using Docker. Now I am moving the module to the production server. But it doesnt show up in the Modules list. Locally it works perfectly, shows up I can activate and it performs perfectly. There are no error logs for this Module in the production server. Its as if it doesnt even exist. I have placed the Custom module inside the /Modules directory where all other modules from freescout also reside and they are working perfectly. I checked the config files and compared them with the default ones, they are pretty much the same.

I checked the permissions on the custom module folder and they are the same as the rest of the modules as well

I have run out of ideas on how to debug this further. Any help would be highly appreciated.

Thanks

**Comment by freescout-help** [comment]
Try to clear cache.

**Comment by sheikhumar93** [comment]
Hi @freescout-help already tried doing that. Did that again but still nothing shows up in the logs or Modules list

**Comment by sheikhumar93** [comment]
Is there any config file/environment variable/place from which loading Modules can be disabled inside Freescout?

**Comment by freescout-help** [comment]
No. Here is the place where to start debugging: https://github.com/freescout-help-desk/freescout/blob/dist/app/Http/Controllers/ModulesController.php#L27

https://github.com/freescout-help-desk/freescout/wiki/Debugging
