### ISSUE TITLE
Unable to select more files to upload at once in the Freescout App [Android]

### ISSUE THREAD

**Issue by mattly6** [freescout-help-desk/freescout#4211]
Hi,

I have a problem with attaching files via Freescout App on Android.

On the mobile web browser (Chrome) when clicking the Attach File button, there's a dialog appearing and lets me choose what I want to attach (Take a photo, Take a video or Choose Media) - Choose Media option lets me upload one or more files and that's the desired behavior.

However, when clicking the Attach File icon in the Freescout App, I immediately get redirected to the Android file manager and can only choose one file at once, then I have to click attach file icon again and again.
I tried to choose a different file manager from within the default manager, but the behavior is still the same - only one file can be chosen.

Is there a chance that behavior in case of Freescout App could be the same as browser's?

(Freescout Server)
PHP version: 8.1.2
FreeScout version: 1.8.143
Database: **MySQL** / PostgreSQL
Are you using CloudFlare: Yes / **No**
Are you using non-official modules: Yes / **No**

**Comment by freescout-help** [comment]
Unfortunately it can't be changed in the mobile app.
