### ISSUE TITLE
Chat Keyboard accessibility Control

### ISSUE THREAD

**Issue by sumit-nknews** [freescout-help-desk/freescout#4212]
Hi FreeScout Team,

I’ve been using FreeScout on my server for a few years and have been really impressed with its performance. However, I’m having some issues with keyboard accessibility in the chat window, which is important for web accessibility.

I’ve added the `tabindex` attribute to enable keyboard navigation, but I’m still struggling with closing the chat and navigating to other options efficiently. To improve this, it would be great to see features like proper focus management when opening and closing the chat window and keyboard shortcuts for common actions (such as using `Alt + C` to open and `Esc` to close the chat).

These changes would significantly enhance the accessibility of FreeScout and make it more user-friendly for those who rely on keyboard navigation.

Thanks for your continuous updates and support!

**Comment by freescout-help** [comment]
What do you mean under "_proper focus management when opening and closing the chat window_"?

**Comment by sumit-nknews** [comment]
> What do you mean under "_proper focus management when opening and closing the chat window_"?

So when I open the chat popup, I can't navigate any of its function (like attachment, send, close) with keyboard, not with `Tab` nor with any keyboard arrows and neither I can close it via `Esc`. So, keyboard control is needed there within chat popup to make it compatible with web-accessibility for all users. Proper focus will help to navigate through each function of chat popup. 

<img width="351" alt="image" src="https://github.com/user-attachments/assets/34f5506b-566f-4a40-b124-6affe7a0eb0e">

**Comment by freescout-help** [comment]
`tabindex` and minimizing using ESC has been added in Chat Module v1.0.41. In order to use ESC one first will need to click inside the chat window or press some key to focus on chat window.

**Comment by sumit-nknews** [comment]
@freescout-help Wow, that's nice. That's exactly what I needed. Thank you for prompt response.
