### ISSUE TITLE
Checklist - reorder

### ISSUE THREAD

**Issue by eljakim** [freescout-help-desk/freescout#4214]
PHP version: 
FreeScout version: 1.18.152
Database: MySQL 
Are you using CloudFlare:  No
Are you using non-official modules:  No

We have just bought the checklist module. It works fine, but it would be great if the tasks in the checklist can be manually reordered. Currently they are shown in the order that they were created.

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).
