### ISSUE TITLE
Change Page Titel with white label or Customization modul

### ISSUE THREAD

**Issue by cmarina** [freescout-help-desk/freescout#4215]
Hi,

running FreeScout on our VPS and added several moduls.
All working fine so far - thanks for the great work.

There is one thing we would really like to change: The page title in the browser tab!
Could this been added to one of the existing moduls?
Or can this been changed via CSS?

Thank you,
Chris

**Comment by freescout-help** [comment]
Are you talking about the `... - FreeScout` suffix added to page titles?
