### ISSUE TITLE
Add inline code option in Extended Editor Module

### ISSUE THREAD

**Issue by ybizeul** [freescout-help-desk/freescout#4217]
Inline code doesn't seem to be part of [summernote](https://github.com/summernote/summernote), but this [extension](https://github.com/tylerecouture/summernote-add-text-tags) seems like it could be a good add-on to the Extended Editor Module.

Right now to type inline code I have to switch to code mode, and wrap text with a `<code></code>` block

**Comment by freescout-help** [comment]
Current implementation of the `code` feature using `<pre>` in the Extended Editor Module is not suitable for you?

![2024-09-09_19-50-21](https://github.com/user-attachments/assets/d2b9ff5f-ea8a-4553-bee1-8bd1a87f8209)

**Comment by ybizeul** [comment]
The problem with `<code>` is that it does the whole paragraph.
What I often like to to is some `inline` monospace font, but also
```
Some lines
of code
sometimes
```

I can achieve this in freescout by switching to code editor, and manually wrap text in `<code>` which doesn't act on a whole paragraph.

![image](https://github.com/user-attachments/assets/f9b7e86c-248a-4317-bc4b-a021bcddfb74)

**Comment by freescout-help** [comment]
Maybe someone will implement it as a module.

**Comment by ybizeul** [comment]
Yes. Someone did. There is already a module to summernote https://github.com/tylerecouture/summernote-add-text-tags
