### ISSUE TITLE
Emails are shown empty due to problems with mailbox signatures

### ISSUE THREAD

**Issue by CoE2013** [freescout-help-desk/freescout#4219]
Hi all,

since about one week - out of a sudden - tickets can no longer be shown in GUI.
Body is in DB, Gui in general works, thus we can navigate, update modules, etc.... but whenever opening a ticket, only title is shown - looks like rendering of ticket simply gets interrupted.

Error occurred about 1 week ago and persists even after updating system and all modules etc.
Mailserver is on Microsoft, thus O365 Inbox.

Any ideas?
We can not reply to tickets for about 1 week now.

In other mailclients, Mails are ok (and fully shown)

![Screenshot 2024-09-09 082715](https://github.com/user-attachments/assets/b39603c3-b0f7-427e-8b9e-6b2fc780a3f5)

**Comment by CoE2013** [comment]
Looks like this then, e.g.:

![Screenshot 2024-09-09 083800](https://github.com/user-attachments/assets/cfabe9a8-1aab-4df8-9460-5cb568bed7a9)

**Comment by freescout-help** [comment]
Can you share the body of one of such emails or send it to support@freescout.net

**Comment by CoE2013** [comment]
Sure, is sent out.
By teh way: ALL ticktes are affected, thus not only new tickety, but also if I want to open old / existing tickets.


We already checked the webserver, but can't find any information pointing us to the problem.
The only thing being logged in the apache logs is sth like

2024-09-09 09:41:43 | Error | 109.250.38.186 | 419 | POST /polycast/receive HTTP/1.0 |   |   | 884 | SSL/TLS-Zugriff für Apache
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by freescout-help** [comment]
We've checked the `body` of the received thread. It's being successfully shown in the FreeScout interface.

You may need someone who can investigate the issue on your server. Also make sure to check logs in Manage > Logs > App Logs.

**Comment by CoE2013** [comment]
Ok, thanks a lot for letting us know.
We will debug the app.

Logs are empty => nothing that indicates an error, that's why we got in touch.
We will let you know once we found the issue - must be sth on our server if you can open the ticket.

**Comment by CoE2013** [comment]
Quick Update:

When commenting out 

{{--                        @include('conversations/editor_bottom_toolbar')--}}

in view.blade.php it seems to work again, so we think the issue can be fopund there, but have not drileld down yet.

**Comment by CoE2013** [comment]
SOLVED: turned out that it was the signature. We do not know what exactly, but seems like there must have been some error in the signature causing the threads to stop rendering.

We have removed the signature for now and are comparing with backups a couple of days a ago.

**Comment by mitchplze** [comment]
We are also seeing the same issue. No changes to signatures have been made recently. 

Message shows up as normal in the source mailbox, but does not render in Freescout (1.8.151). This seems to be at random.

<img width="1503" alt="image" src="https://github.com/user-attachments/assets/cedcce74-0267-4520-835e-865348fbf6e6">

There is absolutely nothing remarkable about the msg:

<img width="853" alt="image" src="https://github.com/user-attachments/assets/3fc13e72-c020-493e-a90c-11185642a643">

**Comment by CoE2013** [comment]
Foy us, checking view.blade did the trick, thus we :

- dumped variables to checked if contents in general are ok
- commented out parts of the file to see where the error occurs
- doing this, we quickly drilled down the problem to the signature

if the GUI works in general, only tickets are not rendering, then probably some contents of the ticket contain invalid HTML / Code causing it to abort...

**Comment by freescout-help** [comment]
@CoE2013  @mitchplze Share HTML-code of your mailbox's signature here or send it to support@freescout.net

**Comment by freescout-help** [comment]
Now FreeScout strips `<script>`, `<form>` and `<iframe>` tags (and their content) from HTML-code of your mailbox signatures. So make sure to revise and adjust the code of your signatures (or clear them and enter from scratch if you can't fix them).

**Comment by CoE2013** [comment]
Thanks a lot.

 

Weh ave already cleared the complete html of the signature.
Not sure what happens, since we have adjusted the signature a couple of days ago – maybe script tags or sth got accidentally inserted …

 

 

Viele Grüße

Ihr Team von Center of Efficiency

Hinweis:

Im Zeitraum vom 17.09.2024  - 25.09.2024 sind wir nur eingeschränkt erreichbar.
Anfragen werden nur per Email beantwortet. Bei der Bearbeitung von Anfragen und Bestellungen kann es zu Verzögerungen kommen.





Webentwicklung | IT-Services 


  <https://www.centerofefficiency.com/media/logo/mail_logo.png> 

			
Center of Efficiency 


  <https://www.centerofefficiency.com/media/logo/icon_phone.png> 

+49 (0) 7721 402050 


  <https://www.centerofefficiency.com/media/logo/icon_mail.png> 

 ***@***.***> ***@***.*** 


  <https://www.centerofefficiency.com/media/logo/icon_link.png> 

 <https://www.centerofefficiency.com/> www.centerofefficiency.com 


  <https://www.centerofefficiency.com/media/logo/icon_map-pin.png> 

Wilhelm-Binder-Str. 15 | 78048 Villingen-Schwenningen | Deutschland 

	
	
	

Gesellschft mit beschränkter Haftung mit Sitz in Villingen-Schwenningen || Amtsgericht Freiburg || HRB 728018 
Geschäftsführer: Dipl.-Wi.-Ing. Bernhard Seitler
USt-IdNr.: DE291682477
