### ISSUE TITLE
When forwarding emails, attachments are not included

### ISSUE THREAD

**Issue by jdevalk** [freescout-help-desk/freescout#4220]
When I forward messages to another email address, the attachments are not included in the forwarded message. Am I doing something wrong? Is this a setting?

PHP version: 8.2.23
FreeScout version: 1.8.152
Database: MySQL
Are you using CloudFlare: Yes
Are you using non-official modules: Yes

**Comment by freescout-help** [comment]
Are you sure you are using the latest FreeScout version?
Check errors in the browser console.

**Comment by jdevalk** [comment]
Well it's not showing me any updates?

I'm seeing the following error in the app logs:

> Path cannot be empty {"userId":1,"email":"joost@<redacted>","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Path cannot be empty at /var/www/<redacted>/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:207)

**Comment by freescout-help** [comment]
What is your OS? Are you able to attach files?

**Comment by jdevalk** [comment]
I'm on Linux.

Yes I'm able to attach files; this doesn't happen consistently for all messages either it seems, only for messages with multiple attachments.

**Comment by freescout-help** [comment]
Try to debug this function: https://github.com/freescout-help-desk/freescout/blob/dist/app/Attachment.php#L427

https://github.com/freescout-help-desk/freescout/wiki/Debugging

**Comment by jdevalk** [comment]
What would you like to know? It seems to be adjusting the variables correctly.

The error has the following stacktrace:

> [stacktrace]
#0 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(207): fopen()
#1 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Http/UploadedFile.php(84): Illuminate\\Filesystem\\FilesystemAdapter-&gt;putFileAs()
#2 /var/www/&lt;redacted&gt;/app/Attachment.php(155): Illuminate\\Http\\UploadedFile-&gt;storeAs()
#3 /var/www/&lt;redacted&gt;/app/Attachment.php(443): App\\Attachment::saveFileToDisk()
#4 /var/www/&lt;redacted&gt;/app/Http/Controllers/ConversationsController.php(1754): App\\Attachment-&gt;duplicate()
#5 [internal function]: App\\Http\\Controllers\\ConversationsController-&gt;ajax()
#6 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#7 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller-&gt;callAction()
#8 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\\Routing\\ControllerDispatcher-&gt;dispatch()
#9 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route-&gt;runController()
#10 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route-&gt;run()
#11 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router-&gt;Illuminate\\Routing\\{closure}()
#12 /var/www/&lt;redacted&gt;/app/Http/Middleware/CustomHandle.php(27): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#13 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\CustomHandle-&gt;handle()
#14 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#15 /var/www/&lt;redacted&gt;/app/Http/Middleware/FrameGuard.php(14): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#16 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\FrameGuard-&gt;handle()
#17 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#18 /var/www/&lt;redacted&gt;/app/Http/Middleware/LogoutIfDeleted.php(28): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#19 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\LogoutIfDeleted-&gt;handle()
#20 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#21 /var/www/&lt;redacted&gt;/app/Http/Middleware/Localize.php(27): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#22 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\Localize-&gt;handle()
#23 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#24 /var/www/&lt;redacted&gt;/app/Http/Middleware/HttpsRedirect.php(46): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#25 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\HttpsRedirect-&gt;handle()
#26 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#27 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#28 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings-&gt;handle()
#29 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#30 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(45): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#31 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate-&gt;handle()
#32 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#33 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(67): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#34 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken-&gt;handle()
#35 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#36 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#37 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession-&gt;handle()
#38 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#39 /var/www/&lt;redacted&gt;/app/Http/Middleware/TokenAuth.php(32): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#40 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TokenAuth-&gt;handle()
#41 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#42 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#43 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession-&gt;handle()
#44 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#45 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#46 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse-&gt;handle()
#47 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#48 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(61): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#49 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies-&gt;handle()
#50 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#51 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#52 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Pipeline\\Pipeline-&gt;then()
#53 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router-&gt;runRouteWithinStack()
#54 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router-&gt;runRoute()
#55 /var/www/&lt;redacted&gt;/overrides/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router-&gt;dispatchToRoute()
#56 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router-&gt;dispatch()
#57 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel-&gt;Illuminate\\Foundation\\Http\\{closure}()
#58 /var/www/&lt;redacted&gt;/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#59 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler-&gt;handle()
#60 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#61 /var/www/&lt;redacted&gt;/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#62 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders-&gt;handle()
#63 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#64 /var/www/&lt;redacted&gt;/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#65 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies-&gt;handle()
#66 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#67 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#68 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest-&gt;handle()
#69 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#70 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#71 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest-&gt;handle()
#72 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#73 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#74 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize-&gt;handle()
#75 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#76 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#77 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode-&gt;handle()
#78 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline-&gt;Illuminate\\Pipeline\\{closure}()
#79 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline-&gt;Illuminate\\Routing\\{closure}()
#80 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline-&gt;then()
#81 /var/www/&lt;redacted&gt;/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel-&gt;sendRequestThroughRouter()
#82 /var/www/&lt;redacted&gt;/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel-&gt;handle()
#83 {main}
"}

**Comment by freescout-help** [comment]
Add the following debugging code before this line https://github.com/freescout-help-desk/freescout/blob/dist/app/Attachment.php#L155
```
\Log::error("file_dir=".$file_dir.", file_name=".$file_name);
```

**Comment by jdevalk** [comment]
```
file_dir=1/0/1/, file_name=7212110-00048.pdf
```

**Comment by jdevalk** [comment]
Ok this is extremely weird. I was debugging deeper.

I added:

```php
\Log::error("path=".$path.", name=".$name.", options=".$options);
```

before:

```php
$options = $this->parseOptions($options);
```

in `vendor/laravel/framework/src/Illuminate/Http/Uploadedfile.php`

And suddenly, the error goes away and forwarding properly adds the attachments.

**Comment by jdevalk** [comment]
The fact that `DISK = 'private';` seems to create the issue.

**Comment by jdevalk** [comment]
Continuing. It dies in the second time this gets called:

```php
$result = Container::getInstance()->make(FilesystemFactory::class)->disk($disk)->putFileAs(
            $path, $this, $name, $options
        );
```

**Comment by freescout-help** [comment]
Let us know if you'll find out the reason.
