### ISSUE TITLE
Amazon customer emails with alias addresses create new tickets despite same subject

### ISSUE THREAD

**Issue by eroplex** [freescout-help-desk/freescout#4222]
Hello,

I am using FreeScout on All-Inkl web hosting, and the system works mostly fine. However, I have an issue with processing emails from Amazon customers. Each new message from these customers creates a new ticket, even though it is part of the same conversation. Here are the details:

Issue:
When a customer contacts us through Amazon, an email is sent with an alias or cryptic email address as the sender (e.g., xxxxxxx12+xxxxx123-123x-x123-12x3xx4xxx5@marketplace.amazon.de). This email contains the order number in the subject, which remains the same in all communications. We reply to the email and send it back to the customer.

However, when the customer contacts us again, a new ticket is created in FreeScout, even though:

The email address (alias) is the same.
The subject line, including the order number, has not changed.
Expected Behavior:
Emails from the same alias email address and with the same subject (order number) should be assigned to an existing ticket, instead of creating new tickets each time.

Additional Notes:

This issue only occurs with Amazon customer emails. For other email conversations, the ticket assignment works correctly.
Hosting: All-Inkl web hosting without root access, with FreeScout fully installed.
Does anyone have a solution or suggestion on how to make FreeScout correctly handle alias emails and assign messages to the same ticket?

Thank you in advance for your help!

**Comment by freescout-help** [comment]
Can you share some email sent to Amazon customer and the reply (in EML format) or send it to support@freescout.net

**Comment by eroplex** [comment]
Thanks, I sent something to the email address.

**Comment by freescout-help** [comment]
FreeScout is not designed to track Amazon order numbers placed in emails subjects: **(Ordine: 123-456789-12345678)**. So for FreeScout emails from Amazon customers will always be new conversations. 

Maybe someone can implement a module especially to handle emails from Amazon.

**Comment by eroplex** [comment]
As I understand it, it doesn't have to be done using the order number, because the subject and the email address are the same. It works for all other conversations too, so that when a customer replies to an email, it is assigned to the same conversation. Even without an order number etc.

**Comment by sebix** [comment]
@eroplex An e-mail can contain references to other e-mails that the e-mail responds to or forwarded etc. The most popular headers are `In-Reply-To` and `References`. All e-mail clients do that. If those are missing, adding e-mails to a thread based on some heuristics is pure luck. It appears that Amazon and e-bay help desks' software lack that feature.

**Comment by sebix** [comment]
> So that means there is no way [...]

No, it doesn't. I provided you some explanations.

**Comment by eroplex** [comment]
would it work with such a module?

`<?php

namespace Modules\AmazonEmailNormalizer;

use App\Email;
use App\Mail;
use Illuminate\Support\ServiceProvider;

class AmazonEmailNormalizer extends ServiceProvider
{
    public function boot()
    {
        // Hook into the mail processing event
        \Event::listen(Email::SAVING, function ($email) {
            $this->normalizeEmailHeaders($email);
        });
    }

    private function normalizeEmailHeaders($email)
    {
        // Check if it's an Amazon email
        if (strpos($email->from, '@marketplace.amazon') !== false) {
            // Ensure that In-Reply-To and References headers are properly set
            if (!$email->references) {
                $email->references = $email->message_id;
            }
            if (!$email->in_reply_to) {
                $email->in_reply_to = $email->references;
            }
        }
    }
}`

**Comment by freescout-help-desk** [comment]
You may need to find someone who can implement it for you.

**Comment by POLY-17** [comment]
I would also like to add my voice to the question: we have a problem with eBay. When replying, the email reference number must always be included with the new message: something like [#xxxxxxiqblj#]_[#aa18f9941xxxxxxxxxxxxxxefbfcc681#]. It's only possible if you reply with the last message sent (option under Settings/Emails to Customers/Conversation History), but it's the option for all mailboxes and it's very inconvenient to always duplicate the information in the reply. So, the customer basically always gets a reply plus their message at the bottom. Is there a solution for this? Can someone provide a module (not free, of course)?
