### ISSUE TITLE
convo.note.created does not fire immediately or a previous entry and this does not have to be a note

### ISSUE THREAD

**Issue by kwm365** [freescout-help-desk/freescout#4223]
Hello Team,

When setting up **Webhooks**, we noticed that convo.note.created does not work in the same way as convo.created, for example.
We have a webhook that always fires when a new ticket is created. This is then corrected in Mattermost and is displayed immediately.

But not in the notes (**convo.note.created**). We want every new note to be posted in a specific channel in Mattermost. But this does not happen or rather happens incorrectly.

So if I create a note, it is not fired via the webhook. If I create another note in the same ticket, the first note is fired with a time delay. However, new replies from customers are also fired via convo.note.created. So it is always the penultimate object in the ticket, regardless of whether it is a note or a customer response. 

We believe that this is a bug.

<img width="1158" alt="2024-09-10_12-32-48" src="https://github.com/user-attachments/assets/08d41a76-5aaa-4e9c-a4ba-cd1869d7b785">

**We use a Freescout Docker installation with the latest Freescout version and various modules!**

**Comment by freescout-help** [comment]
We can't reproduce the issue. Make sure you are using the latest FreeScout and you don't have other webhooks configured to trigger the same Mattermost endpoint.

**Comment by kwm365** [comment]
Hi, as I wrote, we always have the latest/most recent version of Freescout with all modules up to date. We have 3 webhooks, each with different endpoints. There are no errors listed in the logs of the webhooks.

**Comment by freescout-help** [comment]
Someone will need to check it on your server.

**Comment by kwm365** [comment]
that should not be a problem. Who should I send what to?
The interesting thing is that it works immediately and perfectly with convo.created.

**Comment by freescout-help** [comment]
Email at support@freescout.net

**Comment by kwm365** [comment]
Hi team,
we found out that pabbly (we go with the webhooks via pabbly because we can format the output of Freescout well there) and then write in Mattermost actually set the webhook for new tickets and new notes identically.

pabbly has named the webhook the same when cloning the first connect connection for some unknown reason. I have now created a new connection for the notes and now it works as it should. Many thanks and sorry for the effort. Learned something new again.

**Comment by kwm365** [comment]
too early, it is still the case that when I write a new note, it is not the note itself that is fired, but the last element before the note. This can also be a reply from the customer.

**Comment by kwm365** [comment]
so I will send you data an monday

**Comment by freescout-help-desk** [comment]
According to performed tests, it works fine.
