### ISSUE TITLE
Mobile notifications not working

### ISSUE THREAD

**Issue by SakhOnline** [freescout-help-desk/freescout#4229]
Hello. At about the end of last week, notifications stopped coming to the app on your mobile phone. There are three of us agents and three of them stopped working at the same time. I tried reinstalling the application. I've tried disabling and enabling push messages. I saw your instructions, I gave everything as it says. but it still doesn't work. I see new tickets in the application, that is, there is a connection with the server, but notifications about new tickets do not come when the application is minimized or closed on a mobile phone

**Comment by freescout-help** [comment]
It should be working now.

**Comment by SakhOnline** [comment]
Thanks, it's working now
