### ISSUE TITLE
When looking in scout, it stacks all emails into 1 thread. However, it is not showing the most current sender of the email. It just shows the original sender 

### ISSUE THREAD

**Issue by mauriceesp** [freescout-help-desk/freescout#4230]
PHP version: 
FreeScout version: 
Database: MySQL / PostgreSQL
Are you using CloudFlare: Yes / No
Are you using non-official modules: Yes / No

**Comment by freescout-help** [comment]
It's by design. New customer's email is displayed in the `From:` field of the message if FreeScout.

**Comment by mauriceesp** [comment]
so there is not a way to change the focus to have the next sender to the thread have the new senders name displayed?

**Comment by freescout-help** [comment]
No. You can develop a custom module to achieve this.
