### ISSUE TITLE
Freescout Connection to Mailcow SMTP fails with Error 535

### ISSUE THREAD

**Issue by PadawanDeluxe** [freescout-help-desk/freescout#4231]
PHP version:  8.2
FreeScout version: 1.8.152 
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: No
===

Hey folks,
I am trying to setup Freescout with an Mailcow server to send out my emails. We spin up the Freescout instance using a webspace package and have configured mail access. All in all recieving works fine, but sending causes issues. What I can see from the Freescout site is:

`<< 535 Incorrect authentication data

!! Expected response code 235 but got code "535", with message "535 Incorrect authentication data
" (code: 535)
!! Expected response code 235 but got code "535", with message "535 Incorrect authentication data
"
Log data:
++ Starting Swift_SmtpTransport
<< 220-webspaces.server.net ESMTP Exim 4.97.1 #2 Sun, 15 Sep 2024 14:06:40 +0200 
220-We do not authorize the use of this system to transport unsolicited, 
220 and/or bulk e-mail.`

What I have done on the mailcow site is veryfing the access to the mailbox as well as checking SSL/TLS settings on the server. I am able to access the mailbox either via SSL or TLS. This means that the auth coming from freescout is not clear to me and I am rising up this issue here. I am looking for help to tweak the authentication using the SMTP section. Following along the Q&A as well as the Docs didnt help me out on this one. 

thanks in advance for all of your help and patience!

regards
Carsten

**Comment by freescout-help** [comment]
You'll need to figure it out by yourself diagnosing it on your server.
