### ISSUE TITLE
Feature Request: Implement failover smtp

### ISSUE THREAD

**Issue by planetahuevo** [freescout-help-desk/freescout#4232]
Today PostmarkAPP mess completely the delivery with their SMTP server (check twitter for more info). 

So people are recommending to have a failover on laravel. 
https://laravel.com/docs/10.x/mail#failover-configuration

Could this be setup on freescout, as an addon or as a core feature? 

The day there is an issue is when you need your email most... :) 

Thanks!

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).
