### ISSUE TITLE
allowed memory size exhausted

### ISSUE THREAD

**Issue by badgerhill** [freescout-help-desk/freescout#4233]
Hi,
for some reason i start getting an error.

the ui says: "Whoops, looks like something went wrong — check logs in /storage/logs "
the log says:

Allowed memory size of 1073741824 bytes exhausted (tried to allocate 2109800 bytes) at ../freeScout/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:187

i am using one mailbox with two additional users.
there are about 100 threads in there,...

any help appreciated

**Comment by zpfvo** [comment]
See here:

https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#allowed-memory-size-of-nnn-bytes-exhausted-error-when-fetching-large-attachments

if you are using docker, set the memory limit in the environment using
`PHP_MEMORY_LIMIT`.

More info here: https://github.com/tiredofit/docker-nginx-php-fpm/?tab=readme-ov-file#container-options
