### ISSUE TITLE
Issue with APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS not working

### ISSUE THREAD

**Issue by ebuzzz** [freescout-help-desk/freescout#4235]
I'm trying to use the APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS environment variable. I've set it to a large number of users (about 30). 

- All these users have access to a central mailbox (we are not using the Global Inbox)
- These users should only see and have access to tickets assigned to them.
- There are 3 team members (Team HQ), that manage the tickets. None of the users in the Team HQ are set in the environment variable.
- Tickets are automatically assigned to the Team HQ.
- HQ want to assign tickets to a user that should only have access to these tickets.

This seems to be the workflow that APP_SHOW_ONLY_ASSIGNED_CONVERSATIONS should solve. But for some reason, it doesn't. When I give a user access to the mailbox, he or she always sees all tickets.

Any ideas on how to debug or resolve this?

PHP version: 8.2.22
FreeScout version: 1.8.152 
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Debugging

Or find someone who can debug it on your server.
