### ISSUE TITLE
Symlink not created

### ISSUE THREAD

**Issue by AndyMillne** [freescout-help-desk/freescout#4236]
PHP version: 8.1
FreeScout version: 1.8.152
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

The system status page shows symlink as not present even though it is. I've debugged this and it appears to be because the file_exists check is actually looking for a .gitignore file that doesn't exist. Install was manual from distro download not via git pull.

`// Check if public symlink exists, if not, try to create.
        $public_symlink_exists = true;
        $public_path = public_path('storage');
        $public_test = $public_path.DIRECTORY_SEPARATOR.'.gitignore';

        if (!file_exists($public_test) || !file_get_contents($public_test)) {
            \File::delete($public_path);
            \Artisan::call('storage:link');
            if (!file_exists($public_test) || !file_get_contents($public_test)) {
                $public_symlink_exists = false;
            }
        }`

**Comment by freescout-help** [comment]
So why does this https://github.com/freescout-help-desk/freescout/blob/dist/storage/app/public/.gitignore file not exist in your installation?

**Comment by AndyMillne** [comment]
Not sure, it's not in the download (freescout-dist.zip) from freescout.net and isn't created by php artisan storage:link

It doesn't seem to be a reliable check. Perhaps is_link() should be used on the actual symlink location?

**Comment by freescout-help** [comment]
.gitignore is present in `/storage/app/public/` folder in freescout-dist.zip

![2024-09-20_13-12-20](https://github.com/user-attachments/assets/de7a4472-6fb3-4df6-b6bc-4096643bc4b7)

Try to figure out why it disappeared for you and put it there manually.
