### ISSUE TITLE
Attach Files from G-Drive 

### ISSUE THREAD

**Issue by ulissesgrz** [freescout-help-desk/freescout#4241]
hello partners!
any posible solution when receive attach files like a url from google drive drive ? 
![image](https://github.com/user-attachments/assets/bd1945cc-45d1-4bde-b2aa-008e6dafbf92)

aim using google gsuite on my company

PHP version: PHP 8.3.6
FreeScout version: 1.8.152    
Database: MySQL 
Are you using CloudFlare: Yes
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).
