### ISSUE TITLE
Increase font size?

### ISSUE THREAD

**Issue by jdevalk** [freescout-help-desk/freescout#4242]
Hi!

I'm using Freescout on a rather large monitor on a daily basis and find myself wanting to increase the font-size, but it looks like that's actually hard to do. Could this be an option in one of the design related modules perhaps? Or could I even hire someone to make this?

**Comment by freescout-help** [comment]
Unfortunately there is no such plans for now.

See https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer

**Comment by iconberg** [comment]
Can you give a hint where in the css-files we can set the size for the base size?

**Comment by iconberg** [comment]
As workaround just adding 


```
body {
        zoom: 125%;
}
```

at top of the css file:

`../public/css/style.css`

helps.

[style.zip](https://github.com/user-attachments/files/18841340/style.zip)
