### ISSUE TITLE
Spam Module - Block Account?

### ISSUE THREAD

**Issue by walterhpdx** [freescout-help-desk/freescout#4245]
First off, love this software!  As the owner of a non-profit, it's really saved my butt many, many times.

We use the Spam module which works like a charm.  But is there a way to block individuals from being able to open tickets?  This same person spams our Support queue one to 12 times a day with the same messages.  Sure, they go directly to Spam, but I'd love to block this spammer from being able to even log tickets.  Is that even possible?

![image](https://github.com/user-attachments/assets/fb06b8b8-91a5-47eb-a056-9de7cd585ec8)

PHP version: 7.4
FreeScout version: 1.8.152
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
You can delete those emails forever via Workflows Module.
