### ISSUE TITLE
Google Workspace requires OAuth

### ISSUE THREAD

**Issue by CAP-CalebNewville** [freescout-help-desk/freescout#4251]
PHP version: 7.4.33
FreeScout version: 1.8.153
Database: Mysql (5.5.5-10.5.26-MariaDB-0+deb11u1)
Are you using CloudFlare: No
Are you using non-official modules: No

Attempting to follow the instructions in these Wiki articles to connect G Suite for e-mail retrieval and sending does not work:

- [Connect G Suite to FreeScout](https://github.com/freescout-help-desk/freescout/wiki/Connect-G-Suite-to-FreeScout)
- [Mail Services Configuration Google Workspace (G Suite)](https://github.com/freescout-help-desk/freescout/wiki/Fetching-Emails#google-workspace-g-suite)

Google has [sunset](https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html) "Less Secure Apps". Fetching e-mails now requires authentication via [OAuth](https://apps.google.com/supportwidget/articlehome?hl=en&article_url=https%3A%2F%2Fsupport.google.com%2Fa%2Fanswer%2F10547014%3Fhl%3Den&assistant_id=generic-unu&product_context=10547014&product_name=UnuFlow&trigger_context=a). 

Request FreeScout support for OAuth in addition to POP/IMAP.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/issues/3707#issuecomment-1902060615

**Comment by CAP-CalebNewville** [comment]
<img width="852" alt="Screenshot 2024-09-25 at 00 13 47" src="https://github.com/user-attachments/assets/9dbf88f4-6b4c-4645-92c4-e51a5cbe5aee">

- 2 step verification is enabled.
- The App Passwords option is not available.

<img width="643" alt="Screenshot 2024-09-25 at 00 10 09" src="https://github.com/user-attachments/assets/a7731f26-bb89-46e0-9c9c-1d3175f4b3ef">

- Deep linking to App Passwords says it's not available.

<img width="1680" alt="Screenshot 2024-09-25 at 00 19 35" src="https://github.com/user-attachments/assets/7e9efd0b-c168-4ab2-b7f9-0d859289116f">

- 2 factor is enabled for the domain in the admin panel

<img width="1680" alt="Screenshot 2024-09-25 at 00 27 29" src="https://github.com/user-attachments/assets/489b0051-ecff-4805-bacb-7f6b6faeb19c">

- In "Less Secure App" settings of Admin --> Security -- Overview there is a warning that "To access platform-specific and third-party apps, you must use OAuth."

It apears that App Passwords are no longer supported.

**Comment by freescout-help** [comment]
Try to check with Google Workspace support why App Passwords are not available in your account.

**Comment by freescout-help** [comment]
FYI. App Passwords section has been moved to "2-Step Verification" section.

Follow [this](https://github.com/freescout-help-desk/freescout/wiki/Connect-G-Suite-to-FreeScout) instruction. Go to your account's Security, click "2-Step Verification" and there at the bottom you'll see App Passwords section.

![2024-09-25_16-31-50](https://github.com/user-attachments/assets/e37d7a4a-86db-4a5b-b22d-98e33f87eb8e)

**Comment by CAP-CalebNewville** [comment]
Ah, OK, that wasn't as easy to find. It looks like the [Wiki article](https://github.com/freescout-help-desk/freescout/wiki/Connect-G-Suite-to-FreeScout) got updated - thanks! One glitch I found in that article is in step 1, the link titled "Security --> Basic Settings" links to someone's domain on the admin console. Thanks!
