### ISSUE TITLE
Tags Module more colors?

### ISSUE THREAD

**Issue by Flexomatic81** [freescout-help-desk/freescout#4252]
Hello everyone,

We are using the Tag's module in our new FreeScout instance. We are wondering why there are only a handful of colors for coloring the tags.
Is there anything planned here?
It would be nice to have a larger color plate or even a mixer as we know it from other programs.

Best regards and many thanks in advance.

**Comment by freescout-help** [comment]
Unfortunately there is no plans to implement this.

**Comment by Flexomatic81** [comment]
Okay, all right.

Thanks for the feedback.
I think it would also make sense to include it in the future.
We work with plenty of tags and if you only have a limited number of colors to mark the tickets, it's a bit suboptimal.

Many thanks for the feedback.
