### ISSUE TITLE
User photo in signature is not displayed.

### ISSUE THREAD

**Issue by Flexomatic81** [freescout-help-desk/freescout#4254]
Greetings,

We are currently failing to get the user's photo to be displayed in the signature.
Only a broken placeholder is displayed.
Has anyone solved this?

Thank you.
-->

PHP version: PHP 8.2.20
FreeScout version: 1.8.153
Database: Mysql (10.11.6-MariaDB-0+deb12u1)
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Are you using https://freescout.net/module/embed-images/ ?

**Comment by Flexomatic81** [comment]
Hi,

We didn't have the module until now.
I have now purchased and activated it.
Unfortunately, it still doesn't work.

Do you have any tips on how I can embed the photo?

Thank you!

**Comment by Flexomatic81** [comment]
We have solved it.

Thank you very much!
