### ISSUE TITLE
Keyboard Shortcuts in conversation list

### ISSUE THREAD

**Issue by Flexomatic81** [freescout-help-desk/freescout#4255]
Greetings,

We also use the Keyboard Shortcuts module. 
It would be nice if the following shortcuts were also available in the list view.

R- reply
A- Assign
S- Status
V- Move
T- Add Tag

Is this already being considered?

Many thanks.

**Comment by freescout-help** [comment]
Unfortunately there is no plans to implement this for now.

**Comment by Flexomatic81** [comment]
Hi,

That's a pity to hear, we switched from Helpscout to FreeScout and were used to having the shortcuts that way. It might be worth adding it as a to-do.

Thanks for the feedback, though.
