### ISSUE TITLE
emails are not coming any more into freescout

### ISSUE THREAD

**Issue by jeepvillage** [freescout-help-desk/freescout#4256]
PHP version: 8.2.23
FreeScout version: 1.8.153
Database: MySQL / PostgreSQL MySQL
Are you using CloudFlare: Yes / No NO
Are you using non-official modules: Yes / No NO

Since 2 hours, Freescout isn't working, email are not coming.
I changed from 1.8.153 to 1.8.153, without success

I checked my mailbox , everything ok.

looking log i always get this message 

Allowed memory size of 134217728 bytes exhausted (tried to allocate 30325296 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 30325296 bytes) at /var/www/vhosts/jeepvillage.com/freescout.jeepvillage.com/overrides/webklex/php-imap/src/Structure.php:109)

trying to get them from CRON

i get this message 

Running scheduled command: '/opt/plesk/php/8.2/bin/php' 'artisan' freescout:fetch-monitor > '/dev/null' 2>&1
Running scheduled command: '/opt/plesk/php/8.2/bin/php' 'artisan' freescout:check-conv-viewers > '/dev/null' 2>&1
Running scheduled command: '/opt/plesk/php/8.2/bin/php' 'artisan' freescout:fetch-emails --identifier=e651c79bf60c210ccdfcca11c9bbfda5 --unseen=1 > '/var/www/vhosts/jeepvillage.com/freescout.jeepvillage.com/storage/logs/fetch-emails.log' 2>&1
Running scheduled command: '/opt/plesk/php/8.2/bin/php' 'artisan' freescout:reports-collect-data > '/dev/null' 2>&1

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Fetching-Emails#common-issues

**Comment by jeepvillage** [comment]
I tried many test

I have 2 mailboxes on freescout.
the both are working an address email coming from OVH.
one is working perfect
the other i can't connexion with, freescout said a problem with internet connexion ?

**Comment by jeepvillage** [comment]
Do not ask why, but everything is working now ?
