### ISSUE TITLE
Replies merging with incorrect threads

### ISSUE THREAD

**Issue by hendrikIK** [freescout-help-desk/freescout#4258]
My client is using the FreeScout ticketing system.

They reported an issue where their users would reply to a thread and have their message attached to a different, unrelated thread. At the time, they were running version 1.8.104 of FreeScout, so I upgraded them to version 1.8.153.

They reported that the issue persists; a user replied to their own thread, and the message got attached to a different email thread with a different ticket number. The only consistency I could pick up on was that it tends to attach to closed tickets.

My client's FreeScout system is running inside a Linux Ubuntu VM within a Docker container.

The modules that my client set up are the following:
API and Webhooks: 1.0.71
Custom Folders: 1.0.18
Export Conversations: 1.0.8
Reports: 1.0.35
Tags: 1.0.36
Ticket Number: 1.0.2

PHP version: 8.2.22
FreeScout version: 1.8.153
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Most likely their client is also using FreeScout, and that FreeScout is of an version and has to be upgraded.

**Comment by hendrikIK** [comment]
Unfortunately, I cannot disclose how my client operates.

Their clients send emails to the ticketing system via Gmail or outlook, they don't use Freescout themselves.

**Comment by freescout-help** [comment]
There was an issue in the past when incoming replies from customers were joining to the incorrect conversation but it was happening when the customer was also using the FreeScout. So it looks like we can't help here, you'll need to debug it by yourself on your server: https://github.com/freescout-help-desk/freescout/wiki/Debugging

**Comment by hendrikIK** [comment]
Regarding debugging, could you give me some guidance on where to investigate the issue in the database?

Details such as how conversations, threads, and tickets link to each other and how the data is structured in the context mentioned above.

Would it also be possible to give me the version number where the above-mentioned issue was fixed?

Your guidance would greatly be appreciated.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L557

**Comment by freescout-help** [comment]
> Would it also be possible to give me the version number where the above-mentioned issue was fixed?

https://github.com/freescout-help-desk/freescout/issues/2375#issuecomment-1345555840
