### ISSUE TITLE
Feature request: Add a "Reply-To" for mailboxes

### ISSUE THREAD

**Issue by devzing** [freescout-help-desk/freescout#4259]
My email is "from" support@email.example.com due to domain requirements from my email provider.

Other systems all me to specify a reply to email address to get around this. E.g. support@example.com

**Comment by freescout-help** [comment]
What mail provider are you using?

**Comment by KlausdB** [comment]
While it's not the simple interface solution you may be looking for, if you really need it now, you can hard-code it into the file config/mail.php

Add something like:
```
  'reply_to' => [
    'address' => 'user@domain.com',
    'name' => 'TheCompanyName',
],

```
I've done rudimentary testing on that without issue.

**Comment by devzing** [comment]
Thanks for the pointer. I did find a way to configure my DNS to work with the subdomain.
