### ISSUE TITLE
Unable to View Dashboard Tabs

### ISSUE THREAD

**Issue by aliraza34** [freescout-help-desk/freescout#4260]
Hi everyone,

I recently set up FreeScout on my local server. However, after installation, I'm unable to see essential dashboard elements such as tickets, assignment options for other agents, or notifications. Additionally, the related tabs that should appear in the header are also missing.

I've ensured that all installation prerequisites were met, and there were no issues during the setup process. Here's a screenshot for reference: 
![image](https://github.com/user-attachments/assets/0bb98b5a-9769-4bab-95ff-eaebcf0c3ad9)

Could anyone guide me on what might be causing this or how to resolve it? Any assistance would be greatly appreciated!

Best regards,
Ali Raza
![freescout error](https://github.com/user-attachments/assets/8392ca4c-edf5-496e-b56a-89433faa3ec7)

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#11-troubleshooting
