### ISSUE TITLE
small bug with activation of of paid plugins - chmod vars.js

### ISSUE THREAD

**Issue by podolinek** [freescout-help-desk/freescout#4261]
Hi guys,

thx for the app, awesome - old versions of all vendor libs but fixing all bugs and running on all php versions. Nice.
 
Today I installed lots of plugins and I have problem with two of them - Saved Replies and Custom Fields. Activation is finished by message:

`
Error occurred saving /storage/app/public/js/vars.js. Error: chmod(): Operation not permitted; File: /srv/www/helpdesk.xyz.com/vendor/league/flysystem/src/Adapter/Local.php (368)
`

I tried `php artisan freescout:clear-cache` but Custom Fields still missing in Settings (I see that in Demo).

In "Mailbox > Helpdesk > Settings" modules looks OK, so **no problem with running or activation only with Acivation result(???)**.  Other plugins (Tags, Mentions, Kanban, Dark Mode, Followers, Sticky Notes, Auto Login, API & Webhooks, SAML SSO, Teams, Workflows, End-User Portal, Customization & Rebranding, Reports, Extended Editor, Inbox) activation seem ok.

PHP version: 8.3
FreeScout version: 1.8.152
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Something is not OK with file/folder permissions: https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#-permissions-issue

**Comment by podolinek** [comment]
Thanks, fixed.
