### ISSUE TITLE
Mails in which a customers replies inline are not properly displayed

### ISSUE THREAD

**Issue by CodeAndWeb** [freescout-help-desk/freescout#4263]
**Freescout Version: 1.8.152**

## Current Behavior

When I receive a customer inquiry and respond to it, the customer may reply 
inline, quoting my previous message. However, the content of the customer’s 
response is not fully visible in FreeScout. It appears that FreeScout cuts off 
the email at the first citation.

### Example:
In the image below, you can see that the customer’s inline response to my 
previous reply is not fully displayed:

![Customer Inline Reply](https://github.com/user-attachments/assets/b4315a5e-976f-4b5f-b601-06c43af3b1bf)

The email content is truncated, which hinders effective communication, as 
shown below:

![Truncated Email Content](https://github.com/user-attachments/assets/4ae0385c-4907-440f-9285-127faaa7e1ed)

## Suggested Improvement

Apple Mail provides a better handling of inline replies. It does not cut the 
email at the first citation but trims the message only before the last large 
citation. This approach ensures that the most recent part of the conversation 
remains visible while reducing unnecessary quoted text.

### Example of Apple's Behavior:
In the image below, Apple Mail effectively displays the most recent part of 
the conversation:

![Apple Mail Inline Handling](https://github.com/user-attachments/assets/6c877ad8-efa3-4438-987a-b785c0ab41aa)

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/FAQ

**Comment by CodeAndWeb** [comment]
Which one? The "Show original mail"? I know that this exist, but it's not convenient.

**Comment by CodeAndWeb** [comment]
What about the apple mail behaviour?

Cutting the mail before the last citation instead of beginning with the first one?

**Comment by e-rwan** [comment]
I came to ask about the same thing.
we just updated from 1.8.99 to 1.8.152 and mail history(if the conversation started outside of freescout for exemple) is not included in client mail anymore.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/FAQ#some-emails-are-empty-or-truncated-in-freescout

If someone can implement a fix for this - please submit a pull request.
