### ISSUE TITLE
Reassign an email to a different mailbox?

### ISSUE THREAD

**Issue by jshrek** [freescout-help-desk/freescout#4264]
Just curious if there is a way to re-assign an email to a different Mailbox?
Example: 
Say we have three mailboxes: info@ and accounting@ and sales@
When an email comes to info@ that is for sales department, we would assign to the sales@ mailbox so it would now appear in the inbox for sales@ and not be in the info@ mailbox anymore.
Some of our departments have a LOT of people in them, and I do not want any of them having access to the info@ emails, so it is not really an option to give them access to info@ and then assign an email to them.

As a related question... what happens if I create a USER that has the same email address as one of the MAILBOXES?
Example:
I already have a mailbox using sales@ but now I create a new user called Sales Guy with the same sales@ email?
Will this create any loop where a notification about receiving an email will generate another notification?

Thanks

**Comment by freescout-help** [comment]
> As a related question... what happens if I create a USER that has the same email address as one of the MAILBOXES?

It's impossible - the system won't allow you to do it.

**Comment by jshrek** [comment]
Created a Feature Request for this: https://github.com/freescout-help-desk/freescout/issues/4269
