### ISSUE TITLE
Subject dissapeared when lot of tags applied

### ISSUE THREAD

**Issue by silenttoom** [freescout-help-desk/freescout#4265]
Hello, thank you for providing this great tools and help everybody out!

Just want to inform some minor bug to make freescout more readable & user friendly.
If we put a lot of tags (or long tags) in the tickets, somehow the subject of the tickets dissapear. I assume, its shifted by the tags and this makes user a bit hard to find quick glance of the topics in the tickets.

Attached the image as the sample :

![image](https://github.com/user-attachments/assets/0227c83e-60fb-4281-b77e-de5bf725e9d7)

The first row, the tags seems lot shorter than the second one. So the subject (the bold ones) in the first row appear but also trimmed by the small space. It would be nice if the ticket of the Subject put in the different row from the tags to prevent this.

Thank you!

**Comment by freescout-help** [comment]
If someone knows how to fix it - please submit a pull request.
