### ISSUE TITLE
Mailbox Icons are unused in End-User Portal (ticket view from customer) / no way to set mailbox avatar in End-User Portal

### ISSUE THREAD

**Issue by aine-etke** [freescout-help-desk/freescout#4268]
Hello,
I'm trying to set a custom avatar to the messages sent by users when viewing tickets from the end-user portal (by customer), but apparently, neither End-User Portal nor Mailbox Icons modules do that (screenshot attached).

As the Mailbox Icons module is expected to show icons everywhere, I suppose the fact they are not visible/propagated in End-User Portal ticket view (from customer perspective) is a bug.

Mailbox has an icon set in the Mailbox Icons modules, plus that mailbox has an icon set on gravatar.com
PHP version: 8.3
FreeScout version: latest
Database: PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules: Yes

![Untitled](https://github.com/user-attachments/assets/303af922-121e-40d8-a83c-c2ff7ed34224)

**Comment by freescout-help** [comment]
For now icons are supposed to be visible to support agents only. 
Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by aine-etke** [comment]
Thank you for clarification,
created https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/448878

Should this issue be closed or left as-is?
