### ISSUE TITLE
FEATURE REQUEST: Add ability to transfer a conversation to a different mailbox

### ISSUE THREAD

**Issue by jshrek** [freescout-help-desk/freescout#4269]
I would like to see the ability to be able TRANSFER (not assign) a conversation from one mailbox to another.

This would probably need another dropdown box option, similar to the ASSIGNEE dropdown, but it would be called TRANSFER and would have a list all other mailboxes you can transfer the conversation to. 
See attached mockup screenshot.

Example:
Say we have a couple mailboxes: info@ and sales@
When an email comes to info@ that is for sales department, we would transfer the conversation to the sales@ mailbox so it would now appear in the unassigned folder for sales@ and not be in the info@ mailbox anymore.

It could be implemented as paid Module add-on (this is a feature I would pay for).

- I did some testing in the DB and it looks like simply changing the _folder_id_ and _mailbox_id_ in the `conversations` table was sufficient to transfer it.
- Possibly the `folders` table also needs to be updated with adjusted _total_count_ and _active_count_ as the folder count will still show 1 unassigned conversation in the mailbox even though there are none (I suspect there is some kind of function that already does this, because when a new conversation comes into the mailbox the count is corrected).

![sample](https://github.com/user-attachments/assets/c0244ced-c308-4dc3-a22f-78cb20d0518f)

**Comment by freescout-help** [comment]
![2024-10-05_18-36-58](https://github.com/user-attachments/assets/2bb26c27-d15a-42ab-a99f-c944ac691fd5)

**Comment by jshrek** [comment]
Is there anyway to make MOVE appear up along the top beside ASSIGNEE drop dropdown?

![example](https://github.com/user-attachments/assets/04b724fd-f9fd-4b2d-a609-75dae62f2dbd)

**Comment by freescout-help** [comment]
Via a custom module: https://github.com/freescout-help-desk/freescout/wiki/Modules-Development

**Comment by jshrek** [comment]
I created a new module, but how do I figure out which Eventy filter I need to hook into in order to add the button where I want?
Thanks
