### ISSUE TITLE
Show operator avatar in the end user interface

### ISSUE THREAD

**Issue by PeopleInside** [freescout-help-desk/freescout#4272]
PHP version: 8.3
FreeScout version: [1.8.154]
Database: MySQL / PostgreSQL: Mysql
Are you using CloudFlare: No
Are you using non-official modules: No

---

When user check the ticket in the web interface never see the avatar of the operator that are replying.
The reply is not from the operator but from the department.

For be more clear user open a ticket in department : support
Me operator: Mark made a reply to the ticket

In the user interface the reply is from the support profile not from my operator profile Mark
On the admin side I see messages are from me with my avatar, on the user side there is not my operator name but it's a generic department profile without any avatar.

![immagine](https://github.com/user-attachments/assets/b815018d-0f25-40b6-9cf6-0f1694e53b0b)

When an operator reply to the user the reply should be from that operator not from the department name.
The reply should also have the operator avatar and not an empty one.

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by PeopleInside** [comment]
Done, thanks 
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/448957
