### ISSUE TITLE
Restricting Duplicate Ticket Creation for Recurring Alerts in FreeScout

### ISSUE THREAD

**Issue by Nigel-VSERV** [freescout-help-desk/freescout#4273]
Hi, I am using FreeScout as my organization's ticketing system and have configured system-generated email alerts for certain errors that trigger twice daily. To ensure these alerts are captured as tickets, I have directed the alert emails to the ticketing system's email address.

However, my concern is that these daily alerts result in multiple tickets being created until the issue is resolved. I would like to restrict this so that each unique alert is captured only once, and subsequent alerts are recorded only if the previous ticket has been closed.

Could you please assist me in understanding how this can be achieved through modules or other methods in FreeScout?
 
Thank you!

**Comment by freescout-help** [comment]
Try to delete those tickets using Workflows Module.

**Comment by Nigel-VSERV** [comment]
> Try to delete those tickets using Workflows Module.

Hi freescout-help,

I would like to request a call or an e-meeting to discuss the problem statement in detail, as it appears we may not be aligned.
Please help me with an Email address where we I can contact the Freescout team.

Thank you.

**Comment by freescout-help** [comment]
Unfortunately it's not possible.
