### ISSUE TITLE
"Move to Mailbox" should trigger notifications

### ISSUE THREAD

**Issue by ligi** [freescout-help-desk/freescout#4275]
Problem: when moving a mail to another Mailbox in a workflow -> no notifications are send

This especially becomes a problem when a user mutes the source mailbox

**Comment by freescout-help** [comment]
The "Move" feature does not trigger notifications when moving conversations manually or via Workflows.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/issues/5580#issuecomment-5354286077
