### ISSUE TITLE
retry after "send error"

### ISSUE THREAD

**Issue by ligi** [freescout-help-desk/freescout#4276]
we had a problem in our config that was leading to some "send error"s - it would be good to have a nice way to mitigate this. Ideally the system would just retry at some point. What could also work is a "retry" on the mail to trigger manually. 
What would also really help me currently is a way to filter the logs to only see all logs with "Email to customer" and status "send error" - currently it is quite some work to go through the logs and find the mails that failed.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/blob/dist/app/Jobs/SendReplyToCustomer.php#L330

**Comment by ligi** [comment]
Thanks - but this does not seem to work.
I went back in the logs to see a "Accepted for delivery" entry for the same user - but there is nothing. Also just asked a user and they did not get a mail.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Sending-Issues

**Comment by ligi** [comment]
Emails are going out now - my problem is just with the mails that where issued while the configuration problem was there.

**Comment by ligi** [comment]
I do not think this should be closed but is still a real problem.
