### ISSUE TITLE
Inquiry About Custom Email Subject Keywords for Ticket Association

### ISSUE THREAD

**Issue by agolanov** [freescout-help-desk/freescout#4277]
We are currently utilizing your system along with the majority of your paid modules. We are experiencing an issue with one of our clients during our email correspondence. When the client replies to us within an existing ticket, their email does not associate with the correct ticket; instead, a new ticket is created. We believe this is likely due to the "In-Reply-To" and "References" email headers being removed on their side.

In light of this, we have a question: Is there a module or any other solution that would allow the ticketing system to determine the association of an email with a specific ticket based on a keyword in the email subject line? Additionally, we would like to have the ability to fully define the format of this keyword ourselves. For example, we would like to add a keyword at the beginning of the email subject in the following format: [ABC-{TicketId}], such as [ABC-450], [ABC-630], and so forth.

**Comment by freescout-help** [comment]
FreeScout checks `References` header and special marker in the body of the email:
https://github.com/freescout-help-desk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L455C13-L455C26

**Comment by agolanov** [comment]
> FreeScout checks `References` header and special marker in the body of the email: https://github.com/freescout-help-desk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L455C13-L455C26

I have checked for the presence of the marker in the body of the email in several replies from the client—unfortunately, the marker is not there. The client is also using some sort of ticketing system on their end, and it appears that this system is somehow stripping out headers and markers.

This issue is occurring with only one of our clients (everything works flawlessly with all others), but correspondence with this particular client accounts for 80% of our total email volume. Therefore, the ability to identify emails by a keyword in the subject line, using our own format, would be an ideal solution for us.

**Comment by freescout-help** [comment]
You have the issue similar to https://github.com/freescout-help-desk/freescout/issues/4222
