### ISSUE TITLE
REQUEST: Add new FILTERs to conversations/view.blade.php for Conversations Toolbar

### ISSUE THREAD

**Issue by jshrek** [freescout-help-desk/freescout#4279]
Based on FreeScout v1.8.154 I would like to request the following additional two filters be added to :
/resources/views/conversations/view.blade.php

conversation.toolbar.convinfo.before
conversation.toolbar.convinfo.after

These will allow you add HTML code in the conf-info area of conversations toolbar before ASSIGNEE or after STATUS.
![screenshot](https://github.com/user-attachments/assets/3d004d5b-ba12-4d7b-b704-9a50bda494a6)

For the code, I am not sure if this is the proper way to do it, but I modified view.blade.php and it works.

See line 75 and 126 for the changes in attached view.blade.php:
[view.blade.php.txt](https://github.com/user-attachments/files/17302220/view.blade.php.txt)

**Comment by freescout-help** [comment]
Two actions added (`conversation.convinfo.prepend` and `conversation.convinfo.before_nav`) and will be published in the next release.

**Comment by jshrek** [comment]
I want to insert additional HTML at those locations, which is why I used a Filter. 
How can I add HTML with an Action, as there is nothing returned?

**Comment by freescout-help** [comment]
See "Actions and Filters" in the Guide: https://github.com/freescout-help-desk/freescout/wiki/Modules-Development

**Comment by jshrek** [comment]
Ok, well maybe I am not understanding how an Action works, but how can I modify the toolbar html (to add another button) with an action? 
The action simple sends me $conversation and $mailbox, but nothing I do with these will allow me to add another button to the toolbar.
The filter I setup in the example, adds empty quotes (so nothing) to the toolbar by default, but if I hook the filter, I can return HTML code to add another button and/or text to the toolbar.

**Comment by ilyakonovalenko** [comment]
> Ok, well maybe I am not understanding how an Action works, but how can I modify the toolbar html (to add another button) with an action?

You have to develop custom module where actions and hooks can be used to insert HTML content. It is the only proper way to add something to the FreeScout web interface.

**Comment by jshrek** [comment]
Yes, I have created custom module.
If you insert a FILTER into those two locations, then I can use the filter in MyModuleServiceProvider in the public function hooks like this:
```
\Eventy::addFilter('conversation.convinfo.prepend', function($data) {
            return $data."<li><div class='btn-group'>ADD A BUTTON TO TOOLBAR</div></li>";
        }, 20, 1);
```

However, you have added ACTIONS not filters, so since an action does not return anything back to where is was fired from, there is no way for me to add a new button to the toolbar. Again, if I am mis-understanding how actions work, please correct me.

**Comment by jshrek** [comment]
Okay, so with the Action I figured out I can ECHO what I want to insert.

Is this the correct way to do this?

```
\Eventy::addAction('conversation.convinfo.prepend', function($data) {
            echo "<li><div class='btn-group'>ADD A BUTTON TO TOOLBAR</div></li>";
        }, 20, 1);
```

**Comment by freescout-help** [comment]
Yes.
