### ISSUE TITLE
The page is not redirecting properly issue sometimes

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4283]
Hi @freescout-help Team,

Sometime when I close a pending ticket instead of the next ticket, I see this screen 

<img width="511" alt="Screenshot 2024-10-11 at 10 30 47 AM" src="https://github.com/user-attachments/assets/27db45a7-b775-4a14-a78b-5202706815da">

Thank You.

**Comment by freescout-help** [comment]
We can't reproduce it. You may need to debug it on your server: https://github.com/freescout-help-desk/freescout/wiki/Debugging
