### ISSUE TITLE
QUEUE IS FLOODING

### ISSUE THREAD

**Issue by Hamza31231** [freescout-help-desk/freescout#4284]
Hi,

I would like to ask for help:
My Job uque ist full because of undeliverable message loop.

Now I have deleted the Mailbox from freescout to stop flooding.

But my Freescout instance has a lot of jobs and I can not cancel them.

How to cancel jobs by SSH?

![p9jGNV1NzteUUveI](https://github.com/user-attachments/assets/26f8a9c5-6c64-439c-b70a-3dff12d9ac5d)

after removing the faulty jobs, they appear again after 2 minutes step by step

the jobs obove do not let cancel them.

after klicking canel, nothing happens - homepage reloads and the job stays.

The mails still arriving in the mailbox and I can not stop it.

Is there a possibility to stop it by ssh?

**Comment by freescout-help** [comment]
The Status page shows only 100 jobs. Apparently you have more than 100 jobs.

You can delete records from `jobs` table in the database.
