### ISSUE TITLE
Email is turning into clickable links

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4286]
Hi @freescout-help 

We are using FreeScout to send automated replies to users when they fill form on site. In such case the email address that contains a domain-like substring (for eg: devil123.com@gmail.com) is converted into a clickable hyperlink (devil123.com). Can you please take a look into this.

Thank You.

**Comment by freescout-help** [comment]
HTML-code and screenshots would be helpful.

**Comment by mahavirn** [comment]
Like this one:

<img width="361" alt="Screenshot 2024-10-14 at 7 02 39 PM" src="https://github.com/user-attachments/assets/6e647c50-f27a-4b82-ae5e-4308d8b43a41">

**Comment by freescout-help** [comment]
HTML code is needed. You can find it under the "Code" button in the FreeScout editor.

**Comment by mahavirn** [comment]
Hi @freescout-help 

Below is the HTML code we are using in Auto-Reply

```
Hello {%customer.firstName%},

Thank you so much for reaching out to us!

```

**Comment by mahavirn** [comment]
The issue is its not picking firstname or lastname when creating or updating the customer.

**Comment by rushikeshw01** [comment]
Yes, it is not picking the firstname or lastname in the case where user email is a domain like string (for eg. devil123.com@gmail.com)

In this case it is taking the email devil123.com from the email as the first/last name and converting it into a clickable hyperlink

**Comment by freescout-help** [comment]
@rushikeshw01 thanks for helping.

**Comment by rushikeshw01** [comment]
@freescout-help This is not fixed yet. 

We are using FreeScout to send automated replies to users when they fill form on site. In such case the email address that contains a domain-like substring (for eg: evil123.com@gmail.com) is converted into a clickable hyperlink. 

Steps to reproduce -
- Create a gmail account with email address that contains a domain-like substring ( for eg: evil123.com@gmail.com
- Submit a Form: Fill out the contact form using the email address created above.
- Check the Thank you Email Response on the above email address inbox- https://bsf.d.pr/i/KKi4wo - The name is shown as evil123.com and is hyperlinked. 

Please let us know if you still need help understanding the issue.
