### ISSUE TITLE
menu's are unresponsive after fresh install of freescout

### ISSUE THREAD

**Issue by eburgers81** [freescout-help-desk/freescout#4288]
I have installed a fresh installation of freescout on a ubuntu 22.04.5 LTS system with a remote mysql server. Installation goes fine but when the site is up and running all menu's seem to be unresponsive, menu's like Mange, user profile etc.

![image](https://github.com/user-attachments/assets/c3c62623-58b6-4079-a88f-897f522c1214)

I have now clue where to look about solving this.

Thanks,

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#11-troubleshooting
