### ISSUE TITLE
UpdateFolderCounters - There are multiple runs

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4289]
Hi @freescout-help 

I am using FreeScout and configured multiple MailBoxes, also have multiple custom Folders.

The issue is `UpdateFolderCounters` Job runs multiple times, and when any new conversation comes in any MailBox, it updates all the Folders count.

Can it be optimized?

Thank You.
<img width="954" alt="Screenshot 2024-10-16 at 11 02 38 PM" src="https://github.com/user-attachments/assets/bf980a1a-a478-4260-9e9d-368e2d8cfef2">
<img width="1207" alt="Screenshot 2024-10-16 at 11 02 47 PM" src="https://github.com/user-attachments/assets/2898e124-457c-4b9f-b90c-44e0cc2f72b1">

**Comment by freescout-help** [comment]
Sure. A pull request would be appreciated.
