### ISSUE TITLE
Persisting thread subject history?

### ISSUE THREAD

**Issue by IchHabeHunger54** [freescout-help-desk/freescout#4290]
PHP version: 8.2.20
FreeScout version: 1.8.152
Database: MySQL / ~~PostgreSQL~~
Are you using CloudFlare: ~~Yes~~ / No
Are you using non-official modules: Yes / ~~No~~

Hello, I was trying to implement a plugin that keeps a history of subject names for email threads. In a similar fashion to the "X has been assigned to Y" messages, these messages were supposed to be like "X renamed Y to Z".

I managed to get it mostly working, too, however one crucial detail was missing: As far as I can tell, thread subject history isn't actually persisted anywhere.

My question is, could this functionality be added? Either by adding it to the software natively, or by me making an extra database of some sort for it? If the latter, how exactly would I go about that?

Best regards and thank you in advance for your time.

**Comment by freescout-help** [comment]
There is no plans to implement something like this. You may need to figure it out yourself.

**Comment by IchHabeHunger54** [comment]
I understand, any tips/links for documentation you could provide me with?

**Comment by freescout-help** [comment]
You may need to figure it out yourself or find someone: https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer
