### ISSUE TITLE
How to paralyse Freescout for customer responses

### ISSUE THREAD

**Issue by kwm365** [freescout-help-desk/freescout#4293]
We wondered why there were no more replies from customers for two days.
Then we realised that it was due to an email that arrived in our inbox last Wednesday evening.
It contained so many PDF attachments that Freeescout was unable to import them. According to the log, we should increase the memory by a factor of two hundred.

Conclusion: If someone sends an e-mail with many / large attachments, this can lead to Freescout not importing any more e-mails at all, because Freescout fails to import this one e-mail and cancels fetching completely.

This is not a direct bug, but I just wanted to point out that this can be a possible source of error behaviour.

We are using Freescout with docker compose installation.

Regards

Martin

**Comment by freescout-help** [comment]
Are you using the latest FreeScout version?
Are you using IMAP or POP3 protocol to fetch emails?

**Comment by kwm365** [comment]
We are using last  version with IMAP Accounts

**Comment by freescout-help** [comment]
Strange. We could not reproduce your issue. Maybe it's related somehow to your server or mail server configuration.

**Comment by kwm365** [comment]
You can always say that quickly. It's just never happened before. Everything runs smoothly with Freescout. The customer had sent 4 e-mails in quick succession with lots of attachments. I have listed the attachments here with file

<img width="774" alt="2024-10-27_17-40-51" src="https://github.com/user-attachments/assets/224adfaf-1729-4d2d-a063-443a19cfa0fa">
<img width="781" alt="2024-10-27_17-40-40" src="https://github.com/user-attachments/assets/da34c454-b6aa-4b6d-a132-1aed5cb72c45">
<img width="776" alt="2024-10-27_17-41-04" src="https://github.com/user-attachments/assets/ec5c9797-a2f9-45eb-a948-0b319caaeced">
<img width="798" alt="2024-10-27_17-40-24" src="https://github.com/user-attachments/assets/07ec43c0-4085-49e7-baaa-0a0d062ef516">

**Comment by freescout-help** [comment]
If someone will be able to reproduce it please send a pull request.
