### ISSUE TITLE
Workflows Module: ERR_TOO_MANY_REDIRECTS for unassigned user after action

### ISSUE THREAD

**Issue by JoanaFigueira** [freescout-help-desk/freescout#4294]
Hi 👋

We are using your module Workflows and for a Manual configuration, with the following actions:
![image](https://github.com/user-attachments/assets/f914521f-e9c3-4fe3-b0c6-a1b2d7234bac)

we get the error: `ERR_TOO_MANY_REDIRECTS`, that is:

![image](https://github.com/user-attachments/assets/cc346134-8918-495e-9723-9033b0ba346c)

If we invert the order, everything works fine, but it's easy to mess up the order.  Could it be fixed?

Thanks! 

PHP version: 8.3.12
FreeScout version: 1.8.154
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Info has been added to the troubleshooting section: https://freescout.net/module/workflows/
