### ISSUE TITLE
issues fast forwarding and rewinding with default media player

### ISSUE THREAD

**Issue by nktech1135** [freescout-help-desk/freescout#4295]
PHP version: 8.2.20
FreeScout version: 1.8.154
Database: MySQL / PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules: No

How does one change the media player that is used to play audio files in freescout? The default one doesn't allow for fast forward or rewind if using the keyboard.

**Comment by freescout-help** [comment]
It's determined by your browser and unfortunately can't be adjusted.
