### ISSUE TITLE
Request for Assistance: Enhancing Ticket Management and Handling Duplication of Tickets in Freescout

### ISSUE THREAD

**Issue by Nigel-VSERV** [freescout-help-desk/freescout#4297]
PHP version: 8.2.22
FreeScout version: 1.8.152
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

Hi, I am seeking assistance with a specific use case involving the use of Freescout as our ticketing system.

Our system generates daily alert emails that need to be converted into tickets and assigned to specific users in Freescout based on the nature of the ticket.
The ticket’s nature will be identified using a mapping of two key identifiers, which we plan to configure in Freescout to ensure accurate ticket assignment.

To achieve this, we have the following requirements:
**Separate Column for Key Identifiers:**
We need a dedicated column in the mailbox to add our two key identifiers, enabling easy filtering.
**User Assignment Based on Identifiers:**
Each key identifier should be assignable to specific users, either during or after user creation, so tickets can be routed to the appropriate users based on these identifiers.
**Duplicate Ticket Management:**
When setting up the workflow, tickets are automatically assigned based on the identifier-to-user mapping. However, the same type of ticket is being repeatedly assigned to the same user (e.g., an alert raised today may reappear on subsequent days until resolved), causing duplicate tickets to accumulate in the mailbox.
We would like to address this duplication issue while maintaining proper trackability of tickets, using the Followers module to monitor ticket creation and closure effectively. We would greatly appreciate your guidance on how to address these use cases effectively.

**Comment by freescout-help** [comment]
You can add extra columns to table using a custom module and also you can add new actions/conditions to Workflows via a custom module.

**Comment by Nigel-VSERV** [comment]
Hi,

By Custom module do you mean Custom Fields Module? 
Request you to please clarify what Custom module means. Thank you

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Modules-Development
