### ISSUE TITLE
Knowledge Base Module - Allow indexing 

### ISSUE THREAD

**Issue by core23** [freescout-help-desk/freescout#4299]
Hi,

I'm using the knowledge base module on a public project. All pages are not indexed, because of the global `robots.txt` and the page specific `meta` html tag. Is there a way to allow indexing my help desk?

Thanks in advance

**Comment by freescout-help** [comment]
Unfortunately there is no such feature for now. 
Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by core23** [comment]
Just for documentation. 

There is existing issue on the Feedback list:
https://feedback.userreport.com/25a3cb5f-e4bd-4470-b6f3-79fcfaa8e90f/#idea/427165

**Comment by freescout-help** [comment]
There is a technical difficulty with implementing this as `robots.txt` file is the part of the repository and being rewritten during updates. So if someone have some ideas how this can be implemented - feel free to share.

**Comment by spikerguy** [comment]
> Hi,
> 
> I'm using the knowledge base module on a public project. All pages are not indexed, because of the global `robots.txt` and the page specific `meta` html tag. Is there a way to allow indexing my help desk?
> 
> Thanks in advance

I second this. 

We want to knowledge base to be indexed by search engines. It would be helpful to have an extension either paid or community project which can have seo settings and which gets restored after every update.
