### ISSUE TITLE
Suggested improvement: HMTL in user fields such as “notes”.

### ISSUE THREAD

**Issue by dhaula** [freescout-help-desk/freescout#4300]
Sometimes it's necessary to add a highlighted note for a customer. Something important that grabs attention. Something we can easily do with a bit of HTML.

I'm not asking for a rich text editor, just that if something like <span style=""> is added, it works, or something like <b>, or maybe Markdown language.

This could also be an improvement for the [Customers Management (CRM) Module](https://freescout.net/module/crm/).

Thanks.

**Comment by freescout-help** [comment]
Unfortunately there is no plans to implement something like this. You can try to do it via https://github.com/freescout-help-desk/freescout/wiki/Modules-Development
