### ISSUE TITLE
OAuth with Keycloak: User Logged in as Admin When Email is Missing?

### ISSUE THREAD

**Issue by alconbyte** [freescout-help-desk/freescout#4301]
Hi,

I’ve set up the Freescout OAuth module with Keycloak as a custom provider and disabled the "auto-create user" feature.

When I log in with Keycloak and the user's email exists in Freescout, it maps correctly. However, when the user's email doesn’t match any existing Freescout user, I receive the expected error indicating that the user can’t be found.

The issue arises when the user's email address in Keycloak is not set. In this case, Freescout logs the user in as the first user created in the system, which happens to be the admin account.

Is this expected behavior or could it be a misconfiguration on my end?

Thank you for your assistance.

PHP version: PHP 8.2.20
FreeScout version:   1.8.154 
Database: MySQL
Are you using CloudFlare:  No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Are you using the latest version of OAuth & Social Login Module?

**Comment by freescout-help** [comment]
Fixed in OAuth & Social Login Module v1.0.20
