### ISSUE TITLE
Recipient is not rendering

### ISSUE THREAD

**Issue by Querens** [freescout-help-desk/freescout#4302]
The recipient email is not rendering occasionally, even though it's obviously in the email's headers

![freescout_recipients](https://github.com/user-attachments/assets/bf08d4d2-9738-4586-96ab-e526513181d0)

**Comment by freescout-help** [comment]
It means it's not supposed to render.

**Comment by Querens** [comment]
@freescout-help so, is that normal behavior? What does it depend on? There's usually a recipient. This is important information, as there may be many aliases associated with a single mailbox.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/blob/dist/resources/views/conversations/partials/thread.blade.php#L107

**Comment by Querens** [comment]
@freescout-help Alright, thanks. I've carefully reviewed the code and the email, and it seems the sender has managed to send an email without specifying the recipient.

**Comment by Querens** [comment]
@freescout-help Alright, thanks. I've carefully reviewed the code and the email, and it seems the sender has managed to send an email without specifying the recipient.
