### ISSUE TITLE
The body of email is not rendering even though it does on a preview

### ISSUE THREAD

**Issue by Querens** [freescout-help-desk/freescout#4303]
Well, just as the title says. Here's how the body looks like

![freescout_empty](https://github.com/user-attachments/assets/f63bb704-619f-4db0-b35f-585f4bc47485)

Here's how preview looks like

![freescout_preview](https://github.com/user-attachments/assets/6aca1d5b-e4a6-4881-9195-716e6fef501f)

Here's the original body

![freescout_original](https://github.com/user-attachments/assets/3fd93d3d-0a5f-4a74-8861-e404d725a66e)

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/FAQ

**Comment by Querens** [comment]
@freescout-help do you refer to https://github.com/freescout-help-desk/freescout/wiki/FAQ#when-viewing-a-ticket-in-freescout-the-original-formatting-and-styles-are-removed ?

**Comment by Querens** [comment]
If I understand correctly, the issue might be due to the configuration of purifier.php rather than a bug. This probably sums up the problem well enough for me to move forward with solutions.
