### ISSUE TITLE
Order to send and close

### ISSUE THREAD

**Issue by ka0tik0** [freescout-help-desk/freescout#4304]
PHP version: 8.3.6
FreeScout version: 1.8.154
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

Hi!

I am trying to create a workflow so that a closing email is sent when a change is detected in the status and it transitions to closed, but I am encountering an issue where, when responding to a conversation, the closing message is sent first and then the response.

If I change the workflow to execute on 'New/Responded/Moved', it works correctly, but then I cannot detect the status change when it is done from the dropdown.

I would appreciate any guidance you could provide to help solve the issue.

Thank you very much!

**Comment by freescout-help** [comment]
Unfortunately there is no solution for this for now.
