### ISSUE TITLE
Webhook convo.status does not trigger when a request is closed using the send action

### ISSUE THREAD

**Issue by ka0tik0** [freescout-help-desk/freescout#4305]
I have to use the convo.agent.reply.created action to trigger the webhook, which results in multiple calls that won’t meet the expected outcome by evaluating whether the status is closed

PHP version: 8.3.6
FreeScout version: 1.8.154
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Fixed in API & Webhooks Module v1.0.82
