### ISSUE TITLE
Workflow module: Action to mark field as mandatory

### ISSUE THREAD

**Issue by jenskaesler** [freescout-help-desk/freescout#4306]
PHP version: 8.3.12
FreeScout version: 1.8.154
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

Hi,

I am trying to create a special workflow. In my case I will set a custom field named "solution description" as mandatory if the state changed to "closed" and also the field "solution description" is empty.

I was not able to found a way to realize this. Is there a possibility to create a feature request for this?

Many thanks in advance!

Regards, Jens

**Comment by freescout-help** [comment]
Unfortunately there is no plans to implement this. You can add an action via https://github.com/freescout-help-desk/freescout/wiki/Modules-Development
