### ISSUE TITLE
Can users be restricted to Unassigned and their own tickets?

### ISSUE THREAD

**Issue by planetahuevo** [freescout-help-desk/freescout#4309]
I know there is code to restrict the users to their own ticket (cannot find it now though, but it should be somewhere around here), but, is it possible so they can see the unassigned conversations as well? 

Thanks

**Comment by freescout-help** [comment]
There is no such feature for now.

**Comment by planetahuevo** [comment]
Will the teams extension can be used in such way? 

I need the users to be able to pick the non assigned ones (from their team?) and then do not see the discussions other users are having.

**Comment by freescout-help** [comment]
Unfortunately not.
