### ISSUE TITLE
Disable automatic reply with ticket number for certain senders

### ISSUE THREAD

**Issue by sbbo1** [freescout-help-desk/freescout#4310]
Unfortunately, senders of new e-mails still receive an automatic reply even though the sending of automatic messages is deactivated for this sender in the workflow

PHP version: 8.2.23
FreeScout version: 1.8.154
Database: MySQL
Are you using CloudFlare:  No
Are you using non-official modules:  No

**Comment by freescout-help** [comment]
Most likely the workflow does not trigger for you conditions. Try to attach screenshot of your workflow's conditions and headers of the incoming email.
