### ISSUE TITLE
Knowledge base widget and chat widget on the same page??

### ISSUE THREAD

**Issue by PaulBartelings** [freescout-help-desk/freescout#4311]
Hi, Can I use the Knowledge base widget and chat widget on the same page??

And how do I do that ?

Greats Paul

**Comment by freescout-help** [comment]
You can try. Embed HTML of those widgets into your page.

**Comment by PaulBartelings** [comment]
Thank you for your response. I did that, of course. But when I add the KNB code the chat widget disappears.
