### ISSUE TITLE
Question about variables with identifiers starting with “{#FS: ~”

### ISSUE THREAD

**Issue by Saroniii** [freescout-help-desk/freescout#4312]
■Background
We are currently in the process of verifying a migration study from another help desk system in use.
Due to security requirements of some customers, we have customers who create and reply to a new email instead of replying each time.
This causes a new conversation to be created instead of being linked to an existing conversation because it does not contain anything beginning with “{#FS: ~” (message_id?) to capture the message.

■Question
Another helpdesk system in use explicitly states to include it in the auto-response to work around this problem, but FreeScout does not appear to have a variable option to include such a thing, as far as I can tell.

Please let me check to see if there is currently a variable option to include it.
If so, please let me know the relevant variable option.

If not, I would like to check on plans to add it.
If so, please consider adding it, as we believe the workflow+custom field module can handle a variety of issues.

I apologize if my English is rude.
I am using machine translation, but I hope you understand that I have prepared the text in my native language as politely as possible.

PHP version: -
FreeScout version:1.8.154
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
> Another helpdesk system in use explicitly states to include it in the auto-response

Include what?

https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#emails-from-some-customers-are-not-joined-into-conversations

**Comment by Saroniii** [comment]
I apologize for any confusion.

To explain briefly, with the tool we are currently using, when customers reply with new emails, we guide them to explicitly include the message_id in the body of the email by utilizing a specific feature. However, it seems that FS does not support this functionality, so I am inquiring whether FS can accommodate this feature.

For example:

Regarding this case, we are managing it with the following ref id.

Could you please either reply without deleting the ref id, or if you are contacting this case with a new email, include the ref id below when sending?

[ref_xxxxx]

Therefore, I would like to automatically send similar messages and would like to check if there is a variable in FS that includes the message_id.

**Comment by freescout-help** [comment]
Have you tried this option in Manage >> Settings >> General?

![2024-10-31_12-00-39](https://github.com/user-attachments/assets/3d6529e5-b5fc-4ef3-9110-3873fea396da)

**Comment by Saroniii** [comment]
Yes, it is enabled. However, due to the security policies of some customers, there are cases where they respond by sending a new email rather than replying directly. To link these cases correctly, we need the customers to explicitly include the message_id in the body of their email.

*Note: Emails that do not fall under this case are, of course, being processed normally in FS.

To inform our customers about this requirement, I am looking for a way to include the message_id in the auto-reply customization.

**Comment by freescout-help** [comment]
You can try to solve this somehow via a custom module: https://github.com/freescout-help-desk/freescout/wiki/Modules-Development
