### ISSUE TITLE
Sending email to user with manual workflow

### ISSUE THREAD

**Issue by marcatsmci** [freescout-help-desk/freescout#4315]
Hello !

With a manual workflow, I want to add a tag (ok), add a note (ok) and send an email (not really ok). 
To do this, I've created a specific user and I'm trying to set up email notifications so that the user receives the notification.

![01](https://github.com/user-attachments/assets/7c6e3e5f-bd31-40bb-81cd-131838a8385a)

What are the notification settings to do this? 

![02](https://github.com/user-attachments/assets/08f0aa2b-fc9f-4f76-8e53-f0dfc946f754)

Is there any other way to send an email using a manual workflow?
BR

PHP version: 8.0.30
FreeScout version: 1.8.154
Database: MySQL / PostgreSQL : MariaDB
Are you using CloudFlare: Yes / No : No
Are you using non-official modules: Yes / No : No

**Comment by marcatsmci** [comment]
To clarify my questions:
- are the email notification settings correct? 
- is there another way to send an e-mail to a user from a workflow?

**Comment by freescout-help** [comment]
We've double checked it - it works fine. Make sure your support agent is actually able to receive emails - check https://github.com/freescout-help-desk/freescout/wiki/Sending-Issues

Also try to enable all checkboxes in user's Notification settings to be sure that something is not missing.
