### ISSUE TITLE
Recurring Authentication and SSL Errors with PHP-IMAP Client

### ISSUE THREAD

**Issue by inodario** [freescout-help-desk/freescout#4320]
Hello everyone,

We’re facing persistent issues with our setup, where specific errors keep appearing despite no recent changes to our mail server configuration or mailbox settings. These errors occur repeatedly and are hindering our ability to use the system reliably.

The errors we see are as follows:

1. **Connection Setup Failed:**

   `Error: connection setup failed: Authentication failed; File: /var/www/html/freescout/overrides/webklex/php-imap/src/Client.php (391)`

2. **Outgoing Mail Folder Error:**
   
   `Error: fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:0A00010F:SSL routines::bad length`
   

Has anyone else encountered similar issues, or does anyone have suggestions for resolving these recurring errors? We’ve tried various debugging steps but haven’t found a solution yet. Any advice or insights would be greatly appreciated.

Thanks in advance!

![image](https://github.com/user-attachments/assets/bfd9ea23-3033-4bbe-a59e-3589b026c028)

PHP version:  8.3.6
FreeScout version: 1.8.155
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
All we can suggested is mentioned here: https://github.com/freescout-help-desk/freescout/wiki/Fetching-Emails#troubleshooting-fetching
