### ISSUE TITLE
SMTP Exchange Server issue

### ISSUE THREAD

**Issue by MaxSeck** [freescout-help-desk/freescout#4322]
PHP version: PHP 8.1.2-1ubuntu2.19
FreeScout version: 1.8.156
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: No

Dear Freescout Team,

A few days ago, we transferred our emails to an Exchange server. This server communicates with the Freescout server via SMTP. Currently, we are facing an issue where emails are successfully sent out, but shortly afterward, we continuously receive an error message. More critically, all successfully sent emails are placed in a queue and are resent to our customers every 60 minutes, without an option to manually stop this process. From what I understand, the Freescout server expects a response code 221 to terminate the process, but it receives a response code 250 from the Exchange server, which it cannot properly identify.

Thank you for your help.

![1](https://github.com/user-attachments/assets/0586ba93-1107-4b2d-ba33-1a08adee9cb6)

**Comment by freescout-help** [comment]
Are you using Microsoft Exchange? https://github.com/freescout-help-desk/freescout/wiki/Connect-FreeScout-to-Microsoft-365-Exchange-via-oAuth

**Comment by MaxSeck** [comment]
No. We're using a microsoft exchange server on premise.

Thank you!

**Comment by freescout-help** [comment]
The only way to figure it out is for someone to debug on your server.

**Comment by MaxSeck** [comment]
We solved it. Thank you anyway!

**Comment by freescout-help** [comment]
What was the reason?
