### ISSUE TITLE
Module: Custom Folder / Tags

### ISSUE THREAD

**Issue by iantearle** [freescout-help-desk/freescout#4323]
When adding a custom folder I want to use a tag to add all the tagged threads appear in my folder. However when typing in the tags field all I get is "The Results Could Not Be Loaded" - there are no JS errors. 

I have the tags module installed. 

Also, when editing a tag, upon clicking the colour or editing the name it just hangs the browser without any JS errors. Nothing happens or saved. 

Custom Folders Version: 1.0.24
Tags Version: 1.0.37
FreeScout [1.8.154]

**Comment by freescout-help** [comment]
Check errors in your browser console. 
Check errors in Manage > Logs > App Logs. 
Try to disable all non-official modules.

**Comment by iantearle** [comment]
> Try to disable all non-official modules.
Should have thought about that sorry. Have a custom module to add a send button in the toolbar, was looking for a class that obviously didn't appear on that page. Wrapped with an if statement and all is good again. Thank you.
