### ISSUE TITLE
Issue by using freescout behind a proxy

### ISSUE THREAD

**Issue by dens38** [freescout-help-desk/freescout#4324]
PHP version: 8.2.24
FreeScout version: 1.8.156
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

I use freescout behind a proxy.
In my .env file, I set API_URL variable by specifing my website url.
This information is not used in all place in freescout as a lot of links menu seems to be base on $_SERVER[‘HTTP_HOST’] variable that is not my website url but url known only by my proxy…
Could you change this by using  API_URL variable and not $_SERVER[‘HTTP_HOST’] variable in freescout application code ?
To avoid this issue, I put in index.php, $_SERVER[‘HTTP_HOST’]= my_website_url but it is a dirty solution…
Thanks for your reply on this issue.
Regards

**Comment by freescout-help** [comment]
This looks like a misconfigured web server. You'll need to figure out how to set proper `HTTP_HOST` when executing PHP in your web server.

**Comment by dens38** [comment]
Hello,
I resolved my issue by adding this config in my nginx : fastcgi_param HTTP_HOST my_website_url;
Thanks for your help.
Regards
