### ISSUE TITLE
Latest update breaks installation

### ISSUE THREAD

**Issue by klwr-de** [freescout-help-desk/freescout#4326]
update from 1.8.155 to 1.8.158 gets me the following error:
`@extends('errors::layout') @section('title', 'Error') @section('message', 'Whoops, looks like something went wrong — check logs in /storage/logs') `

Log:
`[2024-11-06 18:57:22] production.ERROR: Undefined variable $mailbox (View: /home/www/helpdesk/resources/views/secure/dashboard.blade.php) {"userId":1,"email":"mailaddress@mailhost","exception":"[object] (ErrorException(code: 0): Undefined variable $mailbox (View: /home/www/helpdesk/resources/views/secure/dashboard.blade.php) at /home/www/helpdesk/storage/framework/views/e0ed1192912f32fa2993e23669f486376a37474d.php:21, ErrorException(code: 0): Undefined variable $mailbox at /home/www/helpdesk/storage/framework/views/e0ed1192912f32fa2993e23669f486376a37474d.php:21)
[`

Tried clearing the cache, got this result:
web145@s121 ~/www/helpdesk # php artisan freescout:clear-cache
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
The compiled services & packages files have been removed.
Cache cleared successfully.
Compiled views cleared!
Configuration cache cleared!
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
Configuration cached successfully!
Created: storage/app/public/js/vars.js

This is on a shared hosting environment so, any sudo stuff won't work. Used to work pretty fine until the update. I noted that the vendor directory now contains a lot more stuff (downloaded the current version and diffed against my current installation).

**Comment by freescout-help** [comment]
Try to re-update: https://github.com/freescout-help-desk/freescout/wiki/Updating-FreeScout#method-5-update-manually

Also check what you have in "/home/www/helpdesk/storage/framework/views/e0ed1192912f32fa2993e23669f486376a37474d.php" on line 21.

**Comment by klwr-de** [comment]
Did exactly as stated, i.e. removed /vendor, re-uploaded, cleared cache, cleared manually using tools.php, even manually deleted the files as stated in https://github.com/freescout-help-desk/freescout/wiki/Clearing-the-Cache

still get the following:
@extends('errors::layout') @section('title', 'Error') @section('message', 'Whoops, looks like something went wrong — check logs in /storage/logs')

**Comment by freescout-help** [comment]
Try to disable all non-official modules and update all modules to their latest versions.

**Comment by klwr-de** [comment]
I always kept my modules up to date but since I followed the manual update procedure, the modules folder is now empty.

**Comment by klwr-de** [comment]
switched from php8.3 to php8.2 which made the instance work again.

**Comment by freescout-help** [comment]
We can't reproduce the issue.
