### ISSUE TITLE
@fwd not recognised when forwarding from Outlook/Exchange

### ISSUE THREAD

**Issue by patrickklaeren** [freescout-help-desk/freescout#4333]
PHP version: 8.2.20
FreeScout version: 1.8.156
Database: MySQL 10.6.7-MariaDB
Are you using CloudFlare: No
Are you using non-official modules: No, only official

When using `@fwd` as the only text in the body of a forwarded email, it is not designating the conversation to the original email.

I have read the FAQs. I have read related issues #2940, #4036 and #4095.

The email was sent from [redacted]@live.co.uk, and forwarded by patrick.klaeren@[redacted]. The conversation should be created under [redacted]@live.co.uk. Instead it is created under patrick.klaeren@[redacted].

The email headers are as such:

```
Subject: Fw: Help again
Thread-Topic: Help again
Thread-Index: XXX
Date: Mon, 11 Nov 2024 00:02:34 +0000
Message-ID:
	<CWLPXXX@XXX.XXX.PROD.OUTLOOK.COM>
References:
	<PR3PXXX@XXX.XXX.PROD.OUTLOOK.COM>
In-Reply-To:
	<PR3PXXX@XXX.XXX.PROD.OUTLOOK.COM>
Accept-Language: en-GB, en-US
Content-Language: en-US
```

The email body is as such:

```html
<div class="elementToProof" style="font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);">
@fwd</div>
<div style="font-family: Aptos, Aptos_EmbeddedFont, Aptos_MSFontService, Calibri, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);">
<br>
</div>
<div id="appendonsend" style="color: inherit;"></div>
<hr style="display: inline-block; width: 98%;">
<div id="divRplyFwdMsg" dir="ltr" style="color: inherit;"><span style="font-family: Calibri, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);"><b>From:</b> Patrick Klaeren <[redacted]@live.co.uk><br>
<b>Sent:</b> Monday, November 11, 2024 00:02<br>
<b>To:</b> Patrick Klaeren <patrick.klaeren@[redacted]><br>
<b>Subject:</b> Help again</span>
<div> </div>
</div>
<div class="elementToProof" style="direction: ltr; font-family: Calibri, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
Hello</div>
```

Looking at the relevant code site does not yield me any pointers as to why this does not work. The first email found by the regex should be the correct [redacted]@live.co.uk email, not patrick.klaeren@[redacted].

https://github.com/freescout-help-desk/freescout/blob/e2360f21464c1a2c459beb3b708f0d8851f7ced8/app/Console/Commands/FetchEmails.php#L719-L733

However the conversation is created under the latter:

![image](https://github.com/user-attachments/assets/10281aaa-2151-49ec-a421-c1798f54b63c)

There are no logs pointing to errors, as this presumably is not an error but a mismatch.

**Comment by freescout-help** [comment]
Add some debugging https://github.com/freescout-help-desk/freescout/wiki/Debugging to check each condition in the code.
