### ISSUE TITLE
Filters for custom kanban in url

### ISSUE THREAD

**Issue by podolinek** [freescout-help-desk/freescout#4336]
Hi guys, thx for perfect helping speed,

is it possible to create url in kanban custom board with custom filters setup? Params in ajax call for kanban data are data in url, but not working in kanban url page. Only 2 params works: board_id and mailbox_id.

Thanks,

Ondrej

**Comment by freescout-help** [comment]
![kanban-link](https://github.com/user-attachments/assets/ba2fc4fa-09b1-4670-97a7-b8b6e5223aba)
