### ISSUE TITLE
Can we have some custom filter in next release

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4338]
Hi @freescout-help 

Can you please add custom filter in this function: 

Conversation::getConvTableSorting

So we can update below values by the filters:

```
$result = [
            'sort_by' => 'date',
            'order' => 'asc',
        ];
```

Thank You.

**Comment by freescout-help** [comment]
You can post here what you need or submit it as a pull request.

**Comment by mahavirn** [comment]
Sure, will be create a Pull Request, Thanks!
