### ISSUE TITLE
Merge Customer Automatic

### ISSUE THREAD

**Issue by szucher** [freescout-help-desk/freescout#4341]
Hi sorry for my bad englisch, 

i receive a few newsletters that are very important in my freescout instance. 

The problem is, the sender use for every newsletter an another mailadress, it is only the same after the @ 

Its possible that freescout merge this customer automaticly? I have already a lot of modules, but i didn´ t found a function to do this.

Thank you for your response :-)

**Comment by freescout-help** [comment]
Unfortunately it's not possible. You can try to implement this via a custom module: https://github.com/freescout-help-desk/freescout/wiki/Modules-Development
