### ISSUE TITLE
Merge Messages automaticly

### ISSUE THREAD

**Issue by szucher** [freescout-help-desk/freescout#4342]
Hi,

I have a travel agency with a few e-mail-adress. Sometimes i get the same newsletter to separate mailadress. Freescout makes for every Mail a new Conversation. Is there any opinion to merge this conversations automaticly? 

I tried it with workflow modul, but there is no option to merge conversations.

I need a function that merge the conversations automaticly or close every same mail after the first mail was received.

I add a picture of my Inbox in Freescout, so you are able to see what i mean.
![screenshot](https://github.com/user-attachments/assets/cb061f04-83c5-46fa-8bed-2956cdd30cbc)

**Comment by freescout-help** [comment]
Unfortunately it's not possible. You can try to implement this via a custom module: https://github.com/freescout-help-desk/freescout/wiki/Modules-Development
