### ISSUE TITLE
Unable to fetch large mailbox

### ISSUE THREAD

**Issue by shunkica** [freescout-help-desk/freescout#4343]
PHP version: 8.2
FreeScout version: 1.8.156
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

I am trying to set up Freescout for a mailbox which has around 50GB of unread mail from the last 10 or so days.

Even though I have given PHP a 2G memory limit it is still not enough, as the fetching process keeps crashing with:

> Allowed memory size of 2147483648 bytes exhausted (tried to allocate 5323576 bytes) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 5323576 bytes) at /www/html/overrides/webklex/php-imap/src/Structure.php:109)

And in the browser I get 504 timeout when running manual fetch.

It would appear as if the app was trying to buffer all the emails at once, because there is no single mail which is over 50MB in size, let alone 2G.

Default docker installation, no modules and no customizations. I am posting here as I don't believe this has anything to do with the app running in Docker.

Let me know if there is any additional info I can provide.

**Comment by freescout-help** [comment]
Email are fetches in bunches of 300 emails: https://github.com/freescout-help-desk/freescout/blob/dist/app/Console/Commands/FetchEmails.php#L62

Apparently you have some large email or email with a large attachment.

**Comment by shunkica** [comment]
Can i change the PAGE_SIZE via some env variable?

**Comment by freescout-help** [comment]
> Can I change the PAGE_SIZE via some env variable?

No.

> Also now I am still having the problem with script execution timeouts, and 504 timeouts.

Try to run fetching via the server console. There can be no timeouts via the console:
```
php artisan freescout:fetch-emails
```

**Comment by shunkica** [comment]
Ok, thank you. I will  post a feature request to allow modification of PAGE_SIZE.
