### ISSUE TITLE
"Mail delivery failed" flood

### ISSUE THREAD

**Issue by dabesa** [freescout-help-desk/freescout#4344]
Today we changed email address of a mailbox.
The new domain did not have SFP configured properly, and this triggered a flood of "Mail delivery failed" emails.

More than 2100 email notifications:
https://paste.pics/6b508d5acb9e451b1ed9c3f68b98f0d3

I understand that FreeScout is sending notifications to all the users, but why is such a big loop generated?

It stopped when I set a wrong SMTP password and cleared the failed job queue, but in the meantime the SMTP server blocked our sender email so I'm not sure what really stopped the issue.
Sorry I can't be more precise, but wondering if you have clues for such behavior.

PHP version: 8.1.30
FreeScout version: 1.8.156
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
Apparently your SMTP server was returning error or timeout while successfully sending the email.
