### ISSUE TITLE
Extended Editor Module: Odd looking table wizard

### ISSUE THREAD

**Issue by sofl88** [freescout-help-desk/freescout#4345]
Reproducible in the freescout demo.

https://github.com/user-attachments/assets/a02e8049-2559-4839-b68f-ea93e68a3355

PHP version: 8.3
FreeScout version: 1.8.156
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: Yes

Thanks in advance

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
