### ISSUE TITLE
no notification for followed ticket when it was closed 

### ISSUE THREAD

**Issue by gplast1981** [freescout-help-desk/freescout#4347]
if you follow a ticket and someone writes a message then you get a notification but if someone closes the ticket why don't you get a message?

if i follow a ticket i should also get a message if it is closed without a comment.

Can this be included?
Many thanks

**Comment by freescout-help** [comment]
Notifications are not sent on status change.

**Comment by gplast1981** [comment]
but this is a very important function. 
If I send a ticket to an employee who closes the ticket without comment, I as the ticket creator do not receive any feedback, so I do not know what has become of the ticket.
The notification for closed tickets is very important

**Comment by freescout-help** [comment]
You can try to do it via https://freescout.net/module/workflows/
