### ISSUE TITLE
Forwarding E-Mails: Necessity of `in-reply-to` header?

### ISSUE THREAD

**Issue by gerricom** [freescout-help-desk/freescout#4348]
PHP version: 8.2.24
FreeScout version: 1.8.157
Database: MariaDB 10.11.6-0+deb12u1
Are you using CloudFlare: No
Are you using non-official modules: No, also none of the official modules are installed

I'm finally getting us started using freescout for our shared inbox. At the moment I'm trying out different things and one thing is the forwarding of mails out of our personal inboxes to the shared inbox. I've tried five different mail clients and three of them (SOGo, Apple Mail, MailMate) don't send an `in-reply-to` while only two (Thunderbird, Afterlogic Webmail) attach that header.

Everybody here would like their personal mail client to their preference and I'd kindly like to ask why there is the `in-reply-to`-requirement when forwarding emails. As far, as I understand the code creating the new conversation, the header is not required, because it's a new conversation anyways and it's not necessary to map it to an existing thread. But maybe there is another wise reason for the requirement I'm not seeing for the moment.

If there is no particular reason for this header, how about dropping this requirement or making it optional?

Thanks!

**Comment by freescout-help** [comment]
You must be talking about `@fwd` instruction. The `in-reply-to` header check has been added just as an extra check to avoid accidental forwarding detections.

> I've tried five different mail clients and three of them (SOGo, Apple Mail, MailMate).

Can you share headers of those emails. Maybe there is some specific header used instead of `in-reply-to`.

**Comment by gerricom** [comment]
This is the header of SOGo:

```
From: "Markus Gerards" <redacted>
Content-Type: multipart/mixed; boundary="----=_=-_OpenGroupware_org_NGMime-3450205-1731657855.952036-1------"
X-Forward: redacted (here an IPv6 is found)
Date: Fri, 15 Nov 2024 09:04:15 +0100
To: redacted
MIME-Version: 1.0
Message-ID: <34a55d-67370080-3-125c5400@106595631>
Subject: =?utf-8?q?Fwd=3A?= redacted
User-Agent: SOGoMail 5.9.1
```

This is the header of Apple Mail on macOS 14

```
From: Markus Gerards <redacted>
Content-Type: multipart/alternative;
	boundary="Apple-Mail=_F698B483-4121-4219-BD1F-22EAD9F09CE9"
Mime-Version: 1.0 (Mac OS X Mail 16.0 \(3776.700.51\))
Subject: Fwd: redacted
X-Universally-Unique-Identifier: A65D8B61-4DFE-40E1-AB97-DA459EFAEE4B
Message-Id: <FA2CFCB4-DAE2-446F-BCE9-36BECDB581A4@redacted>
References: <7632a8a212034e77a2f0ad40fe5da486@redacted>
To: redacted
Date: Fri, 15 Nov 2024 09:20:23 +0100
```

MailMate on the other hand has an `in-reply-to` header. I must have missed this when first checking the headers. But the message is not processed as a `@fwd`-message. I will debug this on my own first - unless you notice the problem here:

```
From: Markus Gerards <redacted>
To: redacted
Subject: Fwd: redacted
Date: Fri, 15 Nov 2024 08:57:40 +0100
X-Mailer: MailMate (1.14r5939)
Message-ID: <5BE81726-4658-4D7B-A055-48318733DCBC@redacted>
In-Reply-To: <AS8PR09MB531795BE772F0D74E4DB1804DA242@redacted>
References: <PAWPR03MB1016874E6EDB299D57BC7A4FDF45B2@redacted>
 <9E6DDDD1-2A2D-4527-ACDC-52627C5FAB3D@redacted>
 <AS8PR09MB531795BE772F0D74E4DB1804DA242@redacted>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_MailMate_83319558-1C5C-4BBB-82F0-C4CDF35BE52D_="
Embedded-HTML: [{"plain":[89,4005],"uuid":"277F9AEF-AACA-49A7-86DB-40282DED8FE9"}]
```

**Comment by freescout-help** [comment]
`In-Reply-To` check has been removed. The update will be published in the next release.

**Comment by gerricom** [comment]
Thanks for this change!
