### ISSUE TITLE
Sensitive information in the error message

### ISSUE THREAD

**Issue by 8lad** [freescout-help-desk/freescout#4349]
**Description:**

 When creating a mailbox in FreeScout and connecting it with Gmail using an app password, if there is an issue with the password or authorization, the error message displayed includes sensitive authentication data. This exposes critical security information, which is not appropriate.

**Steps to Reproduce**

1. Log in to your FreeScout instance as an administrator.
2. Navigate to Mailboxes and create a new mailbox.
3. Connect the mailbox to Gmail and use an App Password for authentication.
4. Enter incorrect credentials or an invalid app password.
5. Attempt to send a test email.

**Expected Behavior**

The error message should describe the issue generically.
Sensitive data (e.g., app password or detailed authorization data) should never be exposed in the error message.

**Actual Behavior**

The error message displays sensitive authentication data (e.g., app password), exposing it to anyone with access to the interface, creating a security risk.
Thanks in advance

![bnqM1FKOH3](https://github.com/user-attachments/assets/67d87ba0-4d53-40e9-8e8f-42794a2fe3a1)

PHP version: 8.3.6
FreeScout version: 1.8.157
Database: PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules: Yes

**Comment by freescout-help** [comment]
Mailbox sending & fetching settings are configured by the admin who knows the password.
