### ISSUE TITLE
Freescout no longer accessible after adding code to footer

### ISSUE THREAD

**Issue by PaulBartelings** [freescout-help-desk/freescout#4350]
Hi all,
I did something stupid and don’t know how to fix it. I added a code in the footer in the Customization & Rebranding module, and now my entire installation is no longer accessible. I have no idea how to resolve this. Can you please tell me how to undo this?

**Comment by freescout-help** [comment]
https://freescout.net/module/customization/ --> Troubleshooting

**Comment by PaulBartelings** [comment]
thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you
thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you
thank you thank you thank you thank you thank you thank you thank you thank you thank you thank you

I didn't read it properly, but thank you so much :)
