### ISSUE TITLE
webhooks and x-freescout-signature - issue with accents and special characters.

### ISSUE THREAD

**Issue by ka0tik0** [freescout-help-desk/freescout#4351]
Hello,
I would like to know the conditions under which the signature for webhooks is generated because when I try to validate one containing accents or other characters like "ñ," I am unable to do so.
Without those characters, there is no problem.
Thank you very much!

**Comment by freescout-help** [comment]
See "Verifying Signature" at https://freescout.net/module/api-webhooks/

**Comment by ka0tik0** [comment]
Yes, I got the information from there, and it works correctly as long as there are no accents or characters like "ñ," for example.

**Comment by freescout-help** [comment]
It works with any symbols.

**Comment by ka0tik0** [comment]
The problem is that, on the origin side (Freescout), some kind of transformation must be happening that I don’t understand, such as escaping, substituting, or encoding those characters differently. As a result, when verifying the signature of the JSON body, the signature doesn’t match the processed message with SHA1 for validation.

**Comment by freescout-help** [comment]
We've double checked - it works just fine with "ñ" in conversation subject or one of the messages inside the conversation.

When checking the signature make sure to take the raw POST data as per instructions:

![2024-11-16_08-11-09](https://github.com/user-attachments/assets/3ada804a-ffe0-4ae5-b836-56813e40ea36)
