### ISSUE TITLE
Server Public IP changed. After clearing the cache, ticketing system is still not working

### ISSUE THREAD

**Issue by jeffrey4680** [freescout-help-desk/freescout#4352]
![4B3C0AE8-F9AA-4373-AC6E-0B4BA7C98C35](https://github.com/user-attachments/assets/39f39fec-8e44-4e89-81f2-ef151438d193)

Please check the screenshot and log file stored in the storage folder. As the subject described. I have cleared the cache with using app key stored in the .env file and cleared on the my-ticketing-system-domain.com/tools.php screen. it seems like cache cleared. However, I cannot log in to dashboard, there are so many css or js issue here as well. Please guide me how to solve this if possible. Thanks!

PHP version: 8.3
FreeScout version: 1.8.157
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules:  No
[laravel-2024-11-16 [2].log](https://github.com/user-attachments/files/17784258/laravel-2024-11-16.2.log)

**Comment by jeffrey4680** [comment]
It seems like file path changed too, the original path is diffrent from this. "/home/1366450.cloudwaysapps.com/eaxyjxpqap/"

**Comment by jeffrey4680** [comment]
Can Freescout support help with fixing this issue? Thank you so much!

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#11-troubleshooting

**Comment by jeffrey4680** [comment]
It's working now. Thanks :)
