### ISSUE TITLE
Fetching email does not get all the emails

### ISSUE THREAD

**Issue by silicahd** [freescout-help-desk/freescout#4355]
The system use to work just fine but a few weeks ago we did a an update and the system will mark emails as read in the server but will not bring them to freescout. If you go and press Festch All the system will bring them. But the cron is only set to bring the last  days of unread emails. Is there a way to set the cron to bring all the emails. 

PHP version: PHP 8.0.26
FreeScout version: 1.8.157
Database: MySQL 
Are you using CloudFlare: Yes 
Are you using non-official modules: No

**Comment by freescout-help** [comment]
The `freescout:fetch-emails` command has `--days=3` parameter. But your issue is not quite clear and it's not clear why do you need this parameter.

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Fetching-Emails#troubleshooting-fetching
