### ISSUE TITLE
Request for Guidance on Supporting AWS ECS with Docker Compose

### ISSUE THREAD

**Issue by luigimolinaro** [freescout-help-desk/freescout#4356]
**Description:**  
Hi FreeScout team,  

I’m currently working on deploying FreeScout on AWS ECS using Docker Compose. While I’ve made some progress, I’ve run into challenges specific to ECS compatibility. For example, volume mounts like:  

```yaml
- ./db:/var/lib/mysql
```  
don’t work with ECS, as it doesn’t support host-based volume mounts in this way.  

Could you provide guidance or suggestions on how to adapt FreeScout to work on ECS? Alternatively, are there any plans to support ECS officially in the future? I’m eager to make FreeScout functional on ECS and would be happy to share any insights from my implementation efforts.

**Comment by jtaylor69** [comment]
Run MySQL in its own container and then map the volume in the way that suits you best.
If you're looking to run multiple containers for availability, then you may need to look at using EFS and map the volume that way.
There's also RDS but that will of course raise the price somewhat, but will mean that you don't need to manage the MySQL container and you can then focus on PHP + webserver.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html
