### ISSUE TITLE
Faster Search plugin issue

### ISSUE THREAD

**Issue by mahavirn** [freescout-help-desk/freescout#4359]
Hi @freescout-help Team,

I am using "Speed up FreeScout search with Meilisearch!" - Faster Search plugin and connected it with Meilisearch

When i am doing search by customer email address, its returning lots of unwanted conversations. Can it be fixed and only show relevant results.

Thank You.

**Comment by freescout-help** [comment]
How are performing the search by customer email address? Can you attach the screenshot.

**Comment by mahavirn** [comment]
Here it is:

<img width="1026" alt="Screenshot 2024-11-20 at 11 51 05 AM" src="https://github.com/user-attachments/assets/fb9678ea-ebb0-4ad6-9d72-598924dbe0f5">

**Comment by freescout-help** [comment]
Here is how it should be done:

![2024-11-20_09-23-27](https://github.com/user-attachments/assets/98c6ec6f-2d2b-4680-a056-bfead898e9a5)

Otherwise the system will search the email and its parts inside the conversation body and in other fields.

**Comment by mahavirn** [comment]
Thanks!

**Comment by mahavirn** [comment]
I want to search conversation body as well. Perhaps another email has opened a ticket and mentioned this email that I am searching for in the body.

**Comment by freescout-help** [comment]
To search something in the email body do it as you've done before: https://github.com/freescout-help-desk/freescout/issues/4359#issuecomment-2487596032
