### ISSUE TITLE
SPAM Filter module

### ISSUE THREAD

**Issue by adam3278** [freescout-help-desk/freescout#4361]
Why spam filter doesn't marks incoming emails as spam, when there is a topic started with "SPAM" or "[SPAM]" (mail server filter prefix)? I set those prefixes as filtered in spam module settings, but without any result. That's quite dangerous.

Filter by the topic:
\*SPAM*
SPAM*
[SPAM]*

**Comment by freescout-help** [comment]
![1](https://github.com/user-attachments/assets/c02f6439-b26b-4a4a-9fd8-84bad87e958a)

**Comment by adam3278** [comment]
Never mind
