### ISSUE TITLE
Move to Sent breaks emails headers

### ISSUE THREAD

**Issue by adam3278** [freescout-help-desk/freescout#4362]
Hi,
I found that the outgoing emails copied to imap folder Sent have the recipient name broken in email header. There is an encoding issue - ex. łó -> Å‚Ã³. When trying to view the email source, there is no issue. The error occurs in MS Outlook and in Roundcube, so in most of the non-global email providers clients.

**Comment by freescout-help** [comment]
What's your FreeScout version?

Can you provide email headers?

**Comment by adam3278** [comment]
Yes, of course.
Freescout: 1.8.156
Headers (without addresses):
‘’’
Date: Fri, 22 Nov 2024 11:35:14 +0100
From: Biuro \*\*\* <biuro@\*\*\*>
Subject: Re: Sklep \*\*\*: Zamówienie nr \*\*\*
Bcc: j.jed\*\*\*@\*\*\*
To: Mariusz *** <mariusz.\*\*\*@\*\*\*>
Message-ID: reply-5591-5d10f63d47e2e2f4@\*\*\*
MIME-Version: 1.0
Content-Type: MULTIPART/mixed; BOUNDARY="0-262836907-1732271714=:862958"
References: <4857b54512598006628ac1f3567252bf@\*\*\*>
In-Reply-To: <4857b54512598006628ac1f3567252bf@\*\*\*>
‘’’
In this email the subject is broken “ó” -> “Ã³”

**Comment by freescout-help** [comment]
Can you please provide the screenshots from MS Outlook or Roundcube.

**Comment by adam3278** [comment]
It's my customer's mail server from shared hosting (DirectAdmin). Screenshots without their customers data below:

<img width="381" alt="Zrzut ekranu 2024-11-22 o 22 04 03" src="https://github.com/user-attachments/assets/b0483055-6593-4e54-b034-79b9bfe40deb">
<img width="616" alt="Zrzut ekranu 2024-11-22 o 22 04 46" src="https://github.com/user-attachments/assets/e9336a9c-b8f6-4a75-9312-48e19eb410c0">
<img width="466" alt="Zrzut ekranu 2024-11-22 o 22 04 18" src="https://github.com/user-attachments/assets/fbaef5c6-b52b-4531-b959-c6cfbce6d0ff">

**Comment by freescout-help** [comment]
Most likely the issue is related to the actual mail server used by your customer. DirectAdmin is not a mail server. You'll need to find out what mail server is used and after that we can try to reproduce the issue.

**Comment by adam3278** [comment]
Yes, I know. DA is using exim with dovecot.

**Comment by freescout-help** [comment]
And what is the name of the hosting? It looks like your customer is the only one experiencing this issue, so better to test it on that hosting.
