### ISSUE TITLE
Do not send autoreplies when Precedence: bulk

### ISSUE THREAD

**Issue by stsimb** [freescout-help-desk/freescout#4363]
Hello!

Today we got in a mail loop because freescout (correctly) sent autoreply emails to emails originating from mailman mailing list requests.

Message-ID: <mailman.0.1732265297.10216.colloq@cs.nyu.edu>
Date: Fri, 22 Nov 2024 03:48:17 -0500
Precedence: bulk
X-BeenThere: colloq@cs.nyu.edu
X-Mailman-Version: 2.1.15

Is it possible to not send auto-replies when the source has the header "Precedence: bulk" or "X-Mailman-Version" ?

Thanks!

**Comment by freescout-help** [comment]
"Precedence: bulk" is already there: https://github.com/freescout-help-desk/freescout/blob/dist/app/Misc/Mail.php#L594

Can you provide the full "X-Mailman-Version" header.

**Comment by stsimb** [comment]
Thanks for the reply.
We're using version 1.8.152.
Strange, we definitely had autoreplies going out...

**Comment by stsimb** [comment]
You're right.

Investigating further, I found that some of the emails we received had "Precedence: list", and they were the ones that got the auto-replies.

It looks like mailman 2 does that
https://bazaar.launchpad.net/~mailman-coders/mailman/2.1/view/head:/Mailman/Message.py#L289

Could you please amend the freescout code to include this as well?

Thanks!

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
