### ISSUE TITLE
Error: connection setup failed: Authentication failed

### ISSUE THREAD

**Issue by svermigo** [freescout-help-desk/freescout#4364]
m experiencing recurring email synchronization errors in FreeScout. The errors indicate authentication issues when attempting to fetch emails. The problem persists despite verifying login credentials and settings. 

PHP version: PHP 8.1.7-1ubuntu3.5
FreeScout version: 1.8.158
Database: MySQL (8.0.33-0ubuntu0.22.10.2)
Web Server: nginx/1.22.0
Are you using CloudFlare: Yes 
Are you using non-official modules: No

I am seeing repeated authentication failures (like 1-2 times a day) for the email accounts configured in FreeScout. Errors indicate connection setup failed: Authentication failed. All emails are  **gmail** hosted, issue appears randomly on any account (not a single account issue).

Below are the relevant error messages from the app logs:
`Error: connection setup failed: Authentication failedfailed to authenticate; File: /var/www/html/overrides/webklex/php-imap/src/Client.php (391)`

Any idea what can be done there? Let me know if further details or testing are required.

Thanks
Igor

**Comment by freescout-help** [comment]
Check SMTP settings for your system emails. Also see https://github.com/freescout-help-desk/freescout/wiki/Fetching-Emails#troubleshooting-fetching
