### ISSUE TITLE
Fatal Error since yesterday

### ISSUE THREAD

**Issue by picocodes** [freescout-help-desk/freescout#4365]
PHP version: 8.2
FreeScout version: 1.8.15 (I guess since I have auto-updates and now can't access my install to verify)
Database: MySQL
Are you using CloudFlare: Yes
Are you using non-official modules: No

### Error
>[2024-11-23 04:00:03] production.ERROR: Class "Webklex\IMAP\Providers\LaravelServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Webklex\\IMAP\\Providers\\LaravelServiceProvider\" not found at /html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:635)
[stacktrace]
#0 /html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(582): Illuminate\\Foundation\\Application->resolveProvider()
#1 /html/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register()
#2 /html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load()
#3 /html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#7 /html/artisan(60): Illuminate\\Foundation\\Console\\Kernel->handle()
#8 {main}
"} 

I see the class [is available in the official package](https://github.com/Webklex/laravel-imap/tree/master/src) but[ not the one provided with Freescout](https://github.com/freescout-help-desk/freescout/tree/dist/vendor/webklex/php-imap/src).

**Comment by freescout-help** [comment]
"Webklex/Laravel-imap" library has been removed from the project.

Use manual updating method: https://github.com/freescout-help-desk/freescout/wiki/Updating-FreeScout#method-5-update-manually

**Comment by picocodes** [comment]
Thanks. Rolling back to 1.8.156 fixed the issue.
