### ISSUE TITLE
'Class "Webklex\IMAP\Providers\LaravelServiceProvider" not found' after update

### ISSUE THREAD

**Issue by il2020** [freescout-help-desk/freescout#4366]
I updated it from version 1.8.157 to 1.8.158 using [the script](https://github.com/freescout-help-desk/freescout/wiki/Updating-FreeScout#method-2-update-using-console-script). While clearing the cache the following messages appeared:

```sh
Clearing cache:

In Application.php line 635:

  Class "Webklex\IMAP\Providers\LaravelServiceProvider" not found


Run DB migration and continue? (Y/n) [n]:

In Application.php line 635:

  Class "Webklex\IMAP\Providers\LaravelServiceProvider" not found



In Application.php line 635:

  Class "Webklex\IMAP\Providers\LaravelServiceProvider" not found



Would you like to update modules? (Y/n) [n]:

In Application.php line 635:

  Class "Webklex\IMAP\Providers\LaravelServiceProvider" not found
```

Whoops, looks like something went wrong — check logs in /storage/logs
```text
[2024-11-24 12:18:18] production.ERROR: Class "Webklex\IMAP\Providers\LaravelServiceProvider" not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class \"Webklex\\IMAP\\Providers\\LaravelServiceProvider\" not found at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:635)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(582): Illuminate\\Foundation\\Application->resolveProvider()
#1 /var/www/html/overrides/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(89): Illuminate\\Foundation\\Application->register()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(561): Illuminate\\Foundation\\ProviderRepository->load()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\\Foundation\\Application->registerConfiguredProviders()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\RegisterProviders->bootstrap()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\\Foundation\\Application->bootstrapWith()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\\Foundation\\Http\\Kernel->bootstrap()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#8 /var/www/html/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle()
#9 {main}
"}
```

PHP version: 8.2.24
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: Yes

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/issues/4365#issuecomment-2495341122

**Comment by nebulade** [comment]
We have hit the same issue in our CI for the Cloudron package. Running `php artisan freescout:clear-cache` hits the same issue. So that does not help, however the culprit here was in the bootstrap cache folder in both files `packages.php` and `services.php`. Removing those made the upgrade work, although I am not 100% sure if that is correct and why the normal cache clearing artisan command didn't work.

**Comment by vgstdev** [comment]
> We have hit the same issue in our CI for the Cloudron package. Running `php artisan freescout:clear-cache` hits the same issue. So that does not help, however the culprit here was in the bootstrap cache folder in both files `packages.php` and `services.php`. Removing those made the upgrade work, although I am not 100% sure if that is correct and why the normal cache clearing artisan command didn't work.

That worked for us as well. Thanks!

**Comment by planetahuevo** [comment]
Same issue here. I could not upgrade. I am trying now removing those files.
