### ISSUE TITLE
Text is not bolded in the editor

### ISSUE THREAD

**Issue by il2020** [freescout-help-desk/freescout#4367]
Italicizing and underlining work.

![2024-11-24 20 07 05](https://github.com/user-attachments/assets/be1613c0-7e11-464c-9642-c732cce58d35)

PHP version: 8.2.24
FreeScout version: 1.8.158
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: Yes

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.

**Comment by freescout-help** [comment]
> I'm experiencing the same issue. Headers like H1, H2, and H3 in the email aren't changing size either.

Fixed in the `master` branch and will be published in the next release.
