### ISSUE TITLE
Cleanup hosting space by deleting attachments 

### ISSUE THREAD

**Issue by joris85** [freescout-help-desk/freescout#4368]
Hi Guys, 

We have 20GB of storage on the Freescout and most of the data is ofcourse attachments. 
We would love to delete old attachments. 
Lets say older then 2 year delete all attachments. 

Is there a way do do this in Freescout?
If not is that nog a good module to cleanup space in your freescout?

Special Cleaning module to have a search and delete certain files. 
If email is older than 2 years and have attachment, delete files on server and in mail. 
Maybe a message in mail that it is deleted so you know they where there?

Thanks!

**Comment by freescout-help** [comment]
There is no such feature for now.

**Comment by joris85** [comment]
Is there anybody interested in developing this with me?
 
 Just an easy cleaner module to clearup space. 
 Delete emails and or attachments.
