### ISSUE TITLE
JavaScript (top menu as example) disabled due to quotes in custom translations

### ISSUE THREAD

**Issue by DavidPrachar** [freescout-help-desk/freescout#4369]
It already happened twice. Last week after disabling Auto Login module, today with enabling purchased Dark Mode module. Last time I spent few hours looking for a solution, resigned and restored FreeScout from 24h backup. It's very annoying and strange as it looks everything goes well, server replies with "enabling/disabling module was done", but menu stops working immediately.  I'm working with FreeScout thru Safari 18.1 (20619.2.8.11.10) on MacOS 15.1 and have no extensions installed in Safari. 

PHP version: 8.3.13
FreeScout version: 1.8.157
Database: MySQL 10.11.6-MariaDB-0+deb12u1
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by DavidPrachar** [comment]
Source of the problem is modification of /storage/app/public/js/vars.js

**Comment by DavidPrachar** [comment]
Funcional and corrupted vars.js comparison is bellow. It seems I made a translation (first line for czech language) and used quotation marks there. There should be used \" or something else for protection of the stored translations when saving. Going to test it. 

root@freescout:/var/www/html/freescout/storage/app/public/js# diff vars.js vars.js.x
267,269c267,269
<                             "time_tracking": "Time Tracking",
<                 "timetr_modal_text": "This is the amount of time you spent on this ticket. Edit the time, if needed, and then click Submit Time. Click Cancel if you don't want to save the time spent.",
<                 "submit_time": "Submit Time",
---
>                             "time_tracking": "Sledování času",
>                 "timetr_modal_text": "Toto je doba, kterou jsi strávil na tomto ticketu. V případě potřeby čas uprav a klikni na "Ručně zadat čas". Pokud nechceš strávený čas uložit, klikni na tlačítko "Zrušit".",
>                 "submit_time": "Ručně zadat čas",
776,781c776,781
<                             "confirm_delete_custom_field": "Бұл жекелендірілген өрісті жою барлық тарихи деректерді алып тастайды және оған байланысты жұмыс процестерін белсендісіздендіреді. Бұл жекелендірілген өрісті жоюға келісесіз бе?",
<                 "confirm_delete_cf_option": "Бұл түсірілетін тізім опциясын жою барлық тарихи деректерді алып тастайды және оған байланысты жұмыс процестерін белсендісіздендіреді. Бұл түсірілетін тізім опциясын жоюға келісесіз бе?",
<                             "kb_reference_title": "Білім базасының сілтемесін енгізу",
<                             "time_tracking": "Уақытты бақылау",
<                 "timetr_modal_text": "Бұл тикетке жұмсалған уақыт. Қажет болса, уақытты өңдеп, содан кейін Уақытты енгізу түймесін басыңыз. Жұмсалған уақытты сақтағыңыз келмесе, Қайтарту түймесін басыңыз.",
<                 "submit_time": "Уақытты енгізу",
---
>                             "confirm_delete_custom_field": "Deleting this custom field will remove all historical data and deactivate related workflows. Delete this custom field?",
>                 "confirm_delete_cf_option": "Deleting this dropdown option will remove all historical data and deactivate related workflows. Delete this dropdown option?",
>                             "kb_reference_title": "Insert Knowledge Base Reference",
>                             "time_tracking": "Time Tracking",
>                 "timetr_modal_text": "This is the amount of time you spent on this ticket. Edit the time, if needed, and then click Submit Time. Click Cancel if you don't want to save the time spent.",
>                 "submit_time": "Submit Time",
1290c1290
<                             "kb_reference_title": "Insertar referencia de la Knowledge Base",
---
>                             "kb_reference_title": "Insert Knowledge Base Reference",

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
