### ISSUE TITLE
Arial font and line height change

### ISSUE THREAD

**Issue by adam3278** [freescout-help-desk/freescout#4371]
Hello,
Is it possible to change font and text line height in emails? I can make custom module for that, but need some hints which freescout classes should I review.

**Comment by freescout-help** [comment]
Here is the template: https://github.com/freescout-help-desk/freescout/blob/dist/resources/views/emails/customer/reply_fancy.blade.php

**Comment by adam3278** [comment]
Hi,
I've edited the template via custom module, but there are some issues:
1. Freescout is using template "emails/customer/reply_fancy", not the "emails.customer.reply_fancy", so we cannot override the views namespace and had to do this this way:
```php
$this->app['view']->getFinder()->prependLocation(dirname(__DIR__) . '/Resources/views');
```
2. App applies some styling into incoming messages and their threads in conversation history (this which is sent to customer), so they have large margins between lines (margin-bottom of paragraphs). I need to prevent it from happening. Should I edit another template?
Thanks
