### ISSUE TITLE
1.8.158 breaks bold styling option in the editor

### ISSUE THREAD

**Issue by sofl88** [freescout-help-desk/freescout#4373]
Hello

I think the fix for #4354 breaks the bold button. When I create a new message and use the bold button, the b tags were applied but there is no visual feedback (the text stays normal but you see the b tags when you switch to code view).

I can reproduce this in the freescout demo when I apply the stylesheet (https://github.com/freescout-help-desk/freescout/commit/0e7e1a54f4f337e921ccfc35e9c73ded72d2724f) manually with the developer tools.

PHP version: 8.3
FreeScout version: 1.8.158
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: Yes

Thanks in advance

**Comment by hexabinaer** [comment]
Confirm, the stylesheet change breaks the preview. This also affects headlines.

@kluvi There are surely wonderful contributors trying to fix this for people like us. Personally I will bridge the waiting time with a custom style sheet loaded from local. Depending on what your browser resp. your browser's developer tools support:

freescout-4373_temporary-fix.css
```
.note-editor .note-editable strong {
  font-weight: bolder;
}

.note-editor .note-editable h2 {
  font-size: 1.5em;
}

.note-editor .note-editable h3 {
  font-size: 1.17em;
}
```
