### ISSUE TITLE
Laravel upgrade?

### ISSUE THREAD

**Issue by DaveLegg** [freescout-help-desk/freescout#4378]
I'm evaluating using Freescout, which for us will mean developing a number of custom modules to add some specific functionality we need. I've noticed Freescout is based on a pretty old version of Laravel (5.5) which was released in 2017 and stopped receiving security patches in 2020. I'm a little concerned about the age of this framework and wanted to ask if there was any intention within the project to upgrade to a more modern version?

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/FAQ
