### ISSUE TITLE
Information Request: Consistent CSS Color Adjustments

### ISSUE THREAD

**Issue by MyMattes** [freescout-help-desk/freescout#4379]
Could you point me to some documentation how to adjust the UI colors, e.g. using the „Custom CSS“ option of the „Customization“ module?

For obvious reasons this module cannot be tested with the demo, but it looks like it‘s only adjusting the header colors out of the box. I‘d like to work on a consistent color scheme, including links, icons et cetera - having all relevant UI elements in shades of red.

I found some discussions about an early dark mode CSS, and a closed dispute with some customer raising a similar request. While it‘s understood this request might not be addressed by the core, a more sophisticated „Customization“ module or some documentation about the relevant CSS tags for individual adjustments would be great! Maybe it‘s already possible to maintain all UI colors at a single place?

**Comment by freescout-help** [comment]
You may need to find someone who can help you adjust it: https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer

**Comment by MyMattes** [comment]
Thanks a bunch for responding. I'm currently enhancing the "[Themes](https://github.com/avenjamin/freescout-Themes-Module)" community module to cover more UI elements, which is 100% suiting my needs.
