### ISSUE TITLE
Unable to login on app with Custom Homepage Module

### ISSUE THREAD

**Issue by Mario-Greiner** [freescout-help-desk/freescout#4380]
Hello,
ive recently bought and installed all the Modules and noticed a problem with the mobile app.

Once the Custom Homepage module is installed and activated im unable to login. (The login url is not changed)

With the custom homepage module im just redirecting to the knowledge base.

This is because the browser wrapper inside the app does not have an address bar or the option to add a button.

**Comment by freescout-help** [comment]
Can you send screenshot of your Custom Homepage settings.
Can you share URL of your helpdesk or send it to support@freescout.net?

> This is because the browser wrapper inside the app does not have an address bar or the option to add a button.

Which button do you mean?

**Comment by Mario-Greiner** [comment]
Sure i will send you a Mail with all the details.

With button i mean just a "workaround". Would be helpful if users could enable a login button or similar for staff members.

**Comment by freescout-help** [comment]
As we can see your FreeScout instance automatically redirects to your Knowledge Base URL. Probably you've configured via your web server or some other way. The mobile app simply shows your FreeScout instance inside the app, that is why in the mobile app you'll also see your Knowledge Base instead of Login page.

**Comment by Mario-Greiner** [comment]
Thats right i configured the custom homepage module to redirect to the knowledge base.
But thats where the problem occurs. I assume the mobile app just opens my instance in a browser. On the iphone the default browser controls are visible in the bottom of the app. So i was wondering if there is maybe a way to display also the adressbar so i could manual navigate to the login page, as i dont want to show a href on the public/consumer pages.

**Comment by freescout-help** [comment]
Unfortunately it's not possible.

**Comment by Mario-Greiner** [comment]
Got u
