### ISSUE TITLE
Is there anyway to show Knowledge base on Widget Chat ?

### ISSUE THREAD

**Issue by spikerguy** [freescout-help-desk/freescout#4381]
PHP version:  8.0.30
FreeScout version:  1.8.158
Database: 	Mysql (10.5.22-MariaDB)
Are you using CloudFlare: Yes
Are you using non-official modules: No

Live chat is blank and user have to type something in search to show.  Why don't we have a way to show top level KB categories ?
![image](https://github.com/user-attachments/assets/34b57511-f22b-44be-be8b-67a76dbaa1dc)

**Back button does not respond.** 
![image](https://github.com/user-attachments/assets/c3e755d2-f7fc-45a5-8268-d5b00ab384d2)

 I will raise a feature request too for the same. 
 
 Thanks.

**Comment by freescout-help** [comment]
![1](https://github.com/user-attachments/assets/61d95912-4425-4b1c-8022-4da641bc79c2)
