### ISSUE TITLE
ReCAPTCHA not appearing on iframed End-user Portal module contact form 

### ISSUE THREAD

**Issue by Dunceantix** [freescout-help-desk/freescout#4384]
I have the End-User Portal and the extra security module and reCAPTCHA appears correctly when viewing the contact form widget.

![image](https://github.com/user-attachments/assets/78c3494b-ee3f-4629-9988-8d76dd18b894)

However if you then use the form as an embed through an iframe (following the instructions on how to do that correctly) 
The resulting form does not have reCAPTCHA on it. 

![image](https://github.com/user-attachments/assets/a5aca465-0da5-417b-a2e0-23f15c77fdbe)

**Comment by freescout-help** [comment]
![2024-12-02_19-45-38](https://github.com/user-attachments/assets/f20a9ff0-d4bf-446c-831c-4b63e2d7ec19)

This option enables RECAPTCHA on "Submit a Ticket" form but it does not affect "Contact Us" widget and you are embedding the "Contact Us" widget via the iframe.

**Comment by Dunceantix** [comment]
Thank you for your reply, are there are any plans to support the "Contact Us" widget with reCAPTCHA? I think we might see a number of bot support tickets being raised through this widget otherwise.

**Comment by freescout-help** [comment]
Unfortunately not as the captcha is not supposed to be shown in the widget.

**Comment by freescout-help** [comment]
The option allowing to disable the Contact Form Widget for a mailbox has been added in End-User Portal Module v1.0.102.
