### ISSUE TITLE
Issues with Gmail Thread Integration and Broken Attachments in FreeScout User Portal

### ISSUE THREAD

**Issue by dsm-developer** [freescout-help-desk/freescout#4386]
Description:

We are encountering multiple issues with the FreeScout User Portal:

Missing Gmail Thread Integration: When a ticket is submitted through the user portal form, it does not appear in the Gmail thread. This prevents us from accessing the ticket requests via Gmail, which is critical for tracking and responding to customer inquiries.

Broken Attachments: Ticket requests that include attachments (e.g., images or files) result in broken images/files within FreeScout. These attachments cannot be viewed or downloaded due to this issue.

The combination of these problems means we are unable to fully access or manage customer ticket requests, including their associated attachments, either in FreeScout or Gmail. Please investigate and resolve these issues to restore full functionality.

PHP version: 8.1.30
FreeScout version: 1.8.159
Database: MySQL 
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
> Missing Gmail Thread Integration: When a ticket is submitted through the user portal form, it does not appear in the Gmail thread. This prevents us from accessing the ticket requests via Gmail, which is critical for tracking and responding to customer inquiries.

The issue is not quite clear. Can you elaborate a bit.

Regarding the issue with attachments - see https://github.com/freescout-help-desk/freescout/issues/4385#issuecomment-2512286297
