### ISSUE TITLE
Broken Attachments

### ISSUE THREAD

**Issue by adrianmxh** [freescout-help-desk/freescout#4388]
When receiveing attachments via email, most of the times they are broken and a question mark "?" is being added within their name.
![image](https://github.com/user-attachments/assets/91c1b202-e6d3-40a7-99dc-cf2667e590b1)
If I open the image in a new tab and remove the ? before the AM, the image is displayed perfectly fine.

I've read all your previous articles about broken attachments and none of them apply.
Please help with a fix if possible!

**Comment by freescout-help** [comment]
Can you send an example of such email to support@freescout.net or send it as EML file.

**Comment by freescout-help** [comment]
It looks like you can't obtain the EML file and without it the issue can't be reproduced.
