### ISSUE TITLE
Tags Module Simply Still Not Appearing

### ISSUE THREAD

**Issue by ruess** [freescout-help-desk/freescout#4389]
Hi looks like my last issue was closed. Unfortunately, after fixing the permissions errors and manually updating the app, the Tags module still is completely missing! I'm simply baffled. I even tried disabling each and every other module to see if there might be some conflict, and it made absolutely no difference.

Anyone else having this issue?

Thanks!

----------
FreeScout Support Wrote:
Better to fix all permissions issues and try to re-activate the module: https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#-permissions-issue

If still no luck, try to re-update your FreeScout using the manual updating method: https://github.com/freescout-help-desk/freescout/wiki/Updating-FreeScout#method-5-update-manually

_Originally posted by @freescout-help in https://github.com/freescout-help-desk/freescout/issues/4357#issuecomment-2492896625_

**Comment by freescout-help** [comment]
So the only way to figure it out is for someone to check on your server (https://github.com/freescout-help-desk/freescout/wiki/Hire-Developer) or you can email at support@freescout.net
