### ISSUE TITLE
Custom Module "Custom Fields"

### ISSUE THREAD

**Issue by rogoos** [freescout-help-desk/freescout#4390]
I purchased the "Custom Fields Module" and have written a webhook catching custom fields.
This all works fine until I have moved an Email from a mailbox to a different one: Then i noticed I lost my custom fields.
The database seem to be looking at an auto-number as an ID, so the ID per mailbox can never be the same.
I was hoping that the NAME would be leading.
I now have this is the database:
id,conversatiionid, custom_field_id,value 
113,107,13,TEST
114,107,9,TEST
And if the custom_field_id would be the same on all mailboxes that would do the trick, or if the NAME would be leading.

We are running this in 7 languages and the field are over all the mailboxes the same 
The other option would be a API but then again the field id's will not be the same.

I guess this would be a feature request.

PHP version: 8.1
FreeScout version: 
Database: MySQL
Are you using CloudFlare:  No
Are you using non-official modules: Yes

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by vanessa804** [comment]
@rogoos Same problem; did you submit a feature request?
