### ISSUE TITLE
Failed to authenticate on SMTP server with username \"username@mailserver.xx\" using 0 possible authenticators.

### ISSUE THREAD

**Issue by PhillerEU** [freescout-help-desk/freescout#4391]
PHP version: 8.x
FreeScout version: 1.8.158
Database: MySQL
Are you using CloudFlare: Yes 
Are you using non-official modules: Yes

We keep getting below send errors on two mailboxes out of all our 15. 
Tried switching to own mail server so we could rule out O365 as the issue. That didn't help. 
We can send testmails from the testfunction in freescout, but no actual conversations get sent. 
I can connect and send from the mailserver just fine from another vendor.
Tried to change from 587 TLS to 465 SSL, no difference. 

Hopefully someone has dealt with this and can help. 

(username and server redacted) 

[2024-12-01 10:20:27] production.ERROR: Failed to authenticate on SMTP server with username "username@mailserver.net" using 0 possible authenticators. {"exception":"[object] (Swift_TransportException(code: 0): Failed to authenticate on SMTP server with username \"username@mailserver.net\" using 0 possible authenticators. at /var/www/html/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:191)
[stacktrace]
#0 /var/www/html/overrides/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(371): Swift_Transport_Esmtp_AuthHandler->afterEhlo()
#1 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(148): Swift_Transport_EsmtpTransport->doHeloCommand()
#2 /var/www/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\\Mail\\Mailer->sendSwiftMessage()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(125): Illuminate\\Mail\\Mailer->send()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(250): Illuminate\\Mail\\Mailable->send()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(205): Illuminate\\Mail\\Mailer->sendMailable()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(99): Illuminate\\Mail\\Mailer->send()
#9 /var/www/html/app/Jobs/SendAutoReply.php(82): Illuminate\\Mail\\PendingMail->send()
#10 [internal function]: App\\Jobs\\SendAutoReply->handle()
#11 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#12 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#14 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(76): Illuminate\\Queue\\CallQueuedHandler->call()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(320): Illuminate\\Queue\\Jobs\\Job->fire()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(270): Illuminate\\Queue\\Worker->process()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(114): Illuminate\\Queue\\Worker->runJob()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#26 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#27 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array()
#28 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#29 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod()
#30 /var/www/html/overrides/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#32 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run()
#34 /var/www/html/vendor/symfony/console/Application.php(992): Illuminate\\Console\\Command->run()
#35 /var/www/html/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand()
#36 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run()
#39 /var/www/html/artisan(62): Illuminate\\Foundation\\Console\\Kernel->handle()
#40 {main}
"}

**Comment by PhillerEU** [comment]
Sent a message from both mailboxes yesterday afternoon, they just arrived this morning. Any idea of what could cause that?

**Comment by freescout-help** [comment]
Unfortunately no clues.

All the advices are here: https://github.com/freescout-help-desk/freescout/wiki/Sending-Issues

**Comment by freescout-help** [comment]
> Maybe someone wiser than us that can tell if it could be releated to this: https://github.com/freescout-help-desk/freescout/commit/0280e4f30d66c8b9c2b6fe0d8cc31b217c19d97c

No. That issue has been fixed.

**Comment by clementmoulin** [comment]
Hello

We have the same issue. We have 3 mailboxes configured, and having the issue on 2.
The one working fine is using MS365, the two others are IMAP/SMTP based (and for me, this is the issue, having both type).

There are connecting to our SMTP, so we have some trace. For example yesterday the errors occurs dozen of times.
So I checked SMTP logs for earlier connections:
```Jan 22 23:46:53 scylla postfix/submission/smtpd[17922]: lost connection after EHLO from unknown[X.X.X.X]
Jan 22 23:46:53 scylla postfix/submission/smtpd[17922]: disconnect from unknown[X.X.X.X] ehlo=2 starttls=1 commands=3
Jan 22 23:46:53 scylla postfix/submission/smtpd[17922]: connect from unknown[X.X.X.X]
Jan 22 23:46:53 scylla postfix/submission/smtpd[17922]: lost connection after EHLO from unknown[X.X.X.X]
Jan 22 23:46:53 scylla postfix/submission/smtpd[17922]: disconnect from unknown[X.X.X.X] ehlo=2 starttls=1 commands=3```
As you can see Freescout did not tried to login.

Sending test email is working fine from configuration page.
But on it, I can see "Microsoft Exchange" under Password field.

Running freescout in docker on version 1.8.166.

BR
