### ISSUE TITLE
Problem with time-tracking module

### ISSUE THREAD

**Issue by chakh1ik** [freescout-help-desk/freescout#4392]
Hello, we have a problem with the time-tracking module.

When sending a message, the timer does not turn off, but keeps counting the total amount of time. Although the timer should stop when the status is pending. 

PHP version: 8.2.7
FreeScout version: 1.8.159
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
![2](https://github.com/user-attachments/assets/5a06fcb7-fe5c-49aa-b3e2-1546e81ea343)

https://freescout.net/module/time-tracking/

**Comment by chakh1ik** [comment]
The timer should stop when the message is in pending status. This used to be the case, but now the timer does not stop.

Could you please help with this?

**Comment by freescout-help** [comment]
Maybe you've made some customizations to the module's code and after updating of the module those adjustments have been overwritten?

**Comment by chakh1ik** [comment]
No, we have not made any changes to the module. I can provide you with the module code if you need it.

**Comment by chakh1ik** [comment]
Thank you for your help
