### ISSUE TITLE
Spam module

### ISSUE THREAD

**Issue by adam3278** [freescout-help-desk/freescout#4394]
Hi,
I’m experiencing some problems with spam filter module. For last 3 weeks it was behaving too weak - a lot of spam in inbox. Now, it’s to strong, because a’lot of my customers emails goes to spam. Even my own store emails are treated like that. I cannot reset the learning memory, because of spam amount, but now it’s not usable. Is there any option to opt-out some emails from spam filter? Thanks in advance.

**Comment by freescout-help** [comment]
Use these filters:

![1](https://github.com/user-attachments/assets/379878bd-1599-4d25-b391-1dbf8331fb55)

**Comment by adam3278** [comment]
Ok, but as far I can see there is no syntax to exclude from filtering.

**Comment by freescout-help** [comment]
Yes. There is no.
