### ISSUE TITLE
All incoming & outgoing connection's passwords are lost after update

### ISSUE THREAD

**Issue by rosinghal** [freescout-help-desk/freescout#4395]
I'm not sure what happened but I don't see any value in password fields for both incoming and outgoing connections for all mailboxes, system email shows the password but fails to send.

Even after adding new credentials, I get the following error 

```
Failed to authenticate on SMTP server with username "XXXXX" using 2 possible authenticators. Authenticator LOGIN returned Swift_TransportException: Expected response code 235 but got code "535", with message "535 Authentication Credentials Invalid "
```

**Comment by freescout-help** [comment]
Have you changed `APP_KEY` in the .env file? All passwords are encrypted using this key. If it changes all passwords won't work anymore.

**Comment by freescout-help** [comment]
It should.

**Comment by rosinghal** [comment]
That worked, however I did change a password in a couple of mailboxes. Can you tell me where is encrypted passwords stored so that I can revert that as well?

**Comment by freescout-help** [comment]
> That worked, however I did change a password in a couple of mailboxes earlier.

Simply set them again and they should start working. Passwords for mailboxes are stored in the database in `mailboxes` table.

**Comment by rosinghal** [comment]
Worked, thanks a lot for quick help.
