### ISSUE TITLE
Kanban missused value/id State/Bundesland

### ISSUE THREAD

**Issue by mmagineo** [freescout-help-desk/freescout#4398]
Hello, during initial Install and Testing for evaluation purpose we saw a "Translation Error".

If you choose at the Kanban Filter Selector the Dropdown Menu, you can access the 3rd value "State". This is translated in german to "Bundesland" which means a regional part of Germany, not the "Status", e.g "Published", "Draft".

As it is the correct translation, but wrong attribute/field-id/label ist should be fixed within the Module. Changing Translation won´t help due to usage of the value at other places within Freshdesk, e.g Customer Details.

THX for your great work!

**Comment by freescout-help** [comment]
See https://github.com/freescout-help-desk/freescout/wiki/Translate

**Comment by mmagineo** [comment]
Thx, i know this doks. It is not possible to translate, as  the value is used for 2 complete different meanings:
- **Within Kanban Module**, it is used for "state" with the sense of a status
- **Within Core App** it is used for Customers regional province/state of a country

**Comment by mmagineo** [comment]
Yes, access is given to the choices (Published, Draft, Deleted) - the function is given!
-> A proper Translation for "State" in German (de) would be "Status". 
As this is already used within the filter it could be better something like "Kanban Status"
This probably makes the difference between the Filter options "Status" and "State" more easy to understand - in every lang..

**Comment by freescout-help** [comment]
Fixed in Kanban Module v1.0.24
