### ISSUE TITLE
Look at ditching the `ps` requirement

### ISSUE THREAD

**Issue by jdevalk** [freescout-help-desk/freescout#4400]
PHP version: any
FreeScout version: latest
Database: any
Are you using CloudFlare: Yes

I'm running into the fact that on a SiteGround GoGeek plan, which in itself is perfectly fine to run FreeScout on, `ps` is not available. In looking into where `ps` is used, I find it [here](https://github.com/freescout-help-desk/freescout/blob/dist/app/Misc/Helper.php#L1453), and [here](https://github.com/freescout-help-desk/freescout/blob/dist/app/Http/Controllers/SystemController.php#L100). 

I'm wondering if it wouldn't be possible to keep track of running processes inside the app better, so `ps` wouldn't be needed?

**Comment by jdevalk** [comment]
Oh and to be clear: I'm willing to fund the development of this to some extent if needed.

**Comment by jdevalk** [comment]
I've found a workaround which makes it "sort of" work: I'm firing off a regular cron job that does

```php artisan freescout:send-monitor```

which seems to fix the fact that emails aren't sending.

**Comment by remcotolsma** [comment]
I'm running in the same issue, system status also reports:

<img width="1118" alt="Scherm­afbeelding 2024-12-10 om 09 40 09" src="https://github.com/user-attachments/assets/1b2dea4b-7a13-4204-ac91-b48292e4385b">

> `queue:work`
> Laatste run: ? Laatste succesvolle run: ? Probeer de cache te legen om de start van het commando te forceren.

I found the following issue about this:

- https://github.com/freescout-help-desk/freescout/issues/4329

Checked https://github.com/freescout-help-desk/freescout/wiki/Background-Jobs and executed the following command: 

```
php artisan freescout:check-requirements
```

```
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
Error, do this: mount -t proc proc /proc
PHP Version
 8.2.26........................ OK
PHP Extensions
 OpenSSL....................... OK
 PDO........................... OK
 Mbstring...................... OK
 Tokenizer..................... OK
 JSON.......................... OK
 XML........................... OK
 IMAP.......................... OK
 GD............................ OK
 fileinfo...................... OK
 ZIP........................... OK
 iconv......................... OK
 cURL.......................... OK
 DOM........................... OK
 libxml........................ OK
 intl.......................... OK
 pcntl (console PHP)........... OK
Error, do this: mount -t proc proc /proc
Functions
 shell_exec (PHP).............. OK
 proc_open (PHP)............... OK
 fpassthru (PHP)............... OK
 symlink (PHP)................. OK
 iconv (PHP)................... OK
 pcntl_signal (console PHP).... OK
 ps (shell).................... NOT FOUND
```

If the use of `ps` could be eliminated and sending emails would run more smoothly, that would be great.

**Comment by freescout-help** [comment]
If someone can replace `ps` with something else - please submit a pull request.

**Comment by Lars-** [comment]
I'm looking into this

**Comment by freescout-help** [comment]
@jdevalk @remcotolsma 
Try to put the attached file into the `/public` folder in your FreeScout, open `https://your-freescout.com/test_proc.php` and send us the output.

[test_proc.zip](https://github.com/user-attachments/files/18079206/test_proc.zip)

**Comment by jdevalk** [comment]
The output is: 

```
PIDS:
```

**Comment by Lars-** [comment]
Then you don't have access to the /proc directory which is required to get all the running processes. 
@freescout-help the only way that I can think of to fix this is by setting some sort of flag when a process starts, but then there is no way to check if it actually did...

**Comment by jdevalk** [comment]
How do we start processes? Because most ways of starting a process in PHP return a PID...

**Comment by Lars-** [comment]
Good question, can't find it very easily. But even if a PID is returned, I doubt if we can check if it is running without having access to /proc.

**Comment by jdevalk** [comment]
No. I think the solution should be to store PIDs when starting processes.

**Comment by freescout-help** [comment]
> I think the solution should be to store PIDs when starting processes.

It's not reliable. We'll leave it as it is and keep recommending to use hosting services supporting `ps`.

**Comment by Lars-** [comment]
@remcotolsma @jdevalk let me know if you need hosting for your freescout instance that does support ps (and anything else). My company hosts around 50 instances right now varying from ones with a couple hundred to millions of conversations.
