### ISSUE TITLE
Links not rendered properly in dark mode

### ISSUE THREAD

**Issue by ligi** [freescout-help-desk/freescout#4401]
this is how it looks in dark mode - you cannot spot the link:

![image](https://github.com/user-attachments/assets/43a84bb1-9be4-412a-a0dd-4813634c61cf)

in light mode you can see it:

![image](https://github.com/user-attachments/assets/8dc828d7-18f9-4d17-8863-c6d28f17b266)

**Comment by freescout-help** [comment]
Fixed in Dark Mode Module v1.0.16
