### ISSUE TITLE
How can I assign a ticket to a service agent depending on working time?

### ISSUE THREAD

**Issue by ThomasBergmann123456** [freescout-help-desk/freescout#4402]
HI,
I want to assign a ticket to a service agent outside normal working times. Unfortunally the Out-Of-Office Module only sends auto-reply mails and with the existing automated tasks, I don't see a time is earlier or before rule.

Does anyone has a hint how to solve this?

PHP version: 
FreeScout version: 1.8.159 
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: Yes

**Comment by freescout-help** [comment]
There is no such feature for now.
