### ISSUE TITLE
How create a new ticket?

### ISSUE THREAD

**Issue by Babelfisch** [freescout-help-desk/freescout#4403]
Sometimes customers do not write to the support address and instead reply to an order confirmation. I would like to create such messages manually as a ticket and assign them to an agent. Unfortunately, I can't find a way to do this. I can only start a new conversation, but then a reply is sent directly to the customer.

How can I create a ticket for a customer without sending a response to them immediately?

**Comment by freescout-help** [comment]
The only way is to use API or some services (Zapier or Make).

**Comment by darkp-team** [comment]
I regularly encounter this situation and resolve it using one of three methods, depending on the case:

1. Create a new ticket as a phone call: This allows me to add the message as an internal note (invisible to the client).
2. Use the "Submit a Ticket" form on the Portal: I fill out the form with the client's details and message via copy-paste. This creates a new ticket in the system on behalf of the client.
3. Forward the email to FreeScout: I use the @fwd command to forward the email directly into FreeScout as a new ticket.

**Comment by Babelfisch** [comment]
Thanks, I will try it.

It would be great to add a easy way to create a new ticket – like in Freshdesk – in future.

**Comment by alvarotrigo** [comment]
Yeap, this is super important.
Creating tickets for users. Especially if we want to migrate from another platform where the users might still continue the conversation in the old ticket system. 

I guess I'll have to tell Claude Code to do this for me using the API :D
