### ISSUE TITLE
Mismatched web and CSV reports

### ISSUE THREAD

**Issue by henrijsilva** [freescout-help-desk/freescout#4404]
Hello,

I am using the Time Tracking report, from the reports module, the reports show the correct time for all cases, between the time period that I specify, regardless of when the conversation was created.

When I try to export to CSV the report only shows the conversations that have time tracked, and were created on the specified time period. 

I have attached an example of this where the web shows 2 conversations, but the CSV only shows 1, because the created time falls out of the scope.

How can I change so the CSV, shows the same as web, without the creation date limitation.

Thank you in advance.
Best regards,
Henrique

PHP version: PHP 8.1.2-1ubuntu2.19
FreeScout version: 1.8.147
Database: Mysql (8.0.40-0ubuntu0.22.04.1) 
Are you using CloudFlare: No
Are you using non-official modules: No

Modules
Reports Version: 1.0.42
Export Conversations Version: 1.0.10
Time Tracking Version: 1.0.17
![Export](https://github.com/user-attachments/assets/3ce0ef23-0e2d-4db5-86ec-b2922942a761)
[export_2024-12-05.csv](https://github.com/user-attachments/files/18024647/export_2024-12-05.csv)

**Comment by freescout-help** [comment]
Fixed in Export Conversations Module v1.0.12

**Comment by henrijsilva** [comment]
Thank you so much, you guys are awesome.
