### ISSUE TITLE
Broken conversation - PHP timeout in HTMLPurifier/Injector/AutoParagraph.php

### ISSUE THREAD

**Issue by sinister3vil** [freescout-help-desk/freescout#4406]
Hello,

As per title I have a single, specific conversation, that's failing to load. Logs show that there's a timeout in PHP execution:

```
2024/12/06 11:34:37 [error] 183#183: *794299 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Injector/AutoParagraph.php on line 335" while reading response header from upstream, client: 5.203.172.79, server: freescout.*******, request: "GET /conversation/289197?folder_id=3 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "freescout.*******", referrer: "https://freescout.*******/search?f%5Bnumber%5D=289197&q="
```

This conversation is quite hot and I need to fix. I'm assuming there's some shitty HTML in one of the thread replies that can't get "purified". How would I edit this outside of Freescout or what are troubleshooting steps I can take?

PHP version: PHP 7.4.33
FreeScout version: 1.8.159
Database: Mysql (5.5.5-10.1.48-MariaDB-0ubuntu0.18.04.1)
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by freescout-help** [comment]
The only option is to go to the database and clean `body` field for conversations threads one by one in the `threads` table.

**Comment by sinister3vil** [comment]
Thanks for the pointers, you can consider this closed!
