### ISSUE TITLE
Embed Images URL change 

### ISSUE THREAD

**Issue by kimsonvu** [freescout-help-desk/freescout#4408]
Hi,

I moved my helpdesk to another URL. After that, all my email answers with embedded images old URL keep as old.

What do i need to do? Which table on Database or file config need to adjust?

**Comment by freescout-help** [comment]
There is no any automatic way to change them. You'll need to change URLs by editing messages in conversations or edit records in `threads` table in DB.

**Comment by kimsonvu** [comment]
any way to edit mass body record in threads table with phpadmin connect ?
