### ISSUE TITLE
Extended Attachments - Sidebar missing

### ISSUE THREAD

**Issue by johanoloflindberg** [freescout-help-desk/freescout#4409]
Hello! We are experiencing issues with the "Extended Attachments" module. We can no longer see attached files in the sidebar menu. 

It worked a few days ago but has recently disappeared. The attached files are visible under the message.

Grateful for any assistance! 

PHP version: PHP 8.1.30
FreeScout version: 1.8.159
Database: Mysql (10.6.20-MariaDB-cll-lve)
Are you using CloudFlare: Yes
Are you using non-official modules: Yes

**Comment by freescout-help** [comment]
It looks like the module got deactivated somehow for you. Check it. Also try to clear cache.
