### ISSUE TITLE
[Improvement] Knowledge Base

### ISSUE THREAD

**Issue by MyMattes** [freescout-help-desk/freescout#4410]
It would be great if the KB module would use an article's title as the default "_Text to insert_" when selecting a knowledge base article  in a conversation. Currently there is no default, but some text is obviously required to insert a KB link.

**Comment by freescout-help** [comment]
Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by MyMattes** [comment]
Feature request submitted.
