### ISSUE TITLE
Installation on Shared Hosting

### ISSUE THREAD

**Issue by omexlu** [freescout-help-desk/freescout#4415]
Hello,

I cant find any documentation how to install freescount on shared hosting?

Thanks in advance.

**Comment by Speedy059** [comment]
Just unzip the download in your public_html folder and go through the setup?

**Comment by mywebhero** [comment]
You can unzip the package into your folder and then follow the steps from the installation guide here: [Installation Guide](https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#8-installing-the-application).

However, most shared hosting services offer auto-installers, like Softaculous, which can simplify the process for you.
