### ISSUE TITLE
Incorrect Encoding of IMAP Email with Base64 and Quoted-Printable Content

### ISSUE THREAD

**Issue by darkp-team** [freescout-help-desk/freescout#4417]
Hello,
I'm experiencing an issue where emails retrieved via IMAP are displayed with incorrect encoding in FreeScout. The same email appears correctly when viewed in the Spark mail client on macOS. This issue seems to affect only this particular sender, and it's the first time I've encountered it.

The message body in FreeScout shows the following content instead of readable text:
```
------=_NextPart_001_01FB_01DB4BCF.551032C0 Content-Type: text/plain; charset="utf-8" Content-Transfer-Encoding: base64

0JfQvdCw0YfQuNGCINC90LUg0YHRg9C00YzQsdCwDQoNCiANCg0K... ... (and so on)
```

It also contains multipart/alternative parts with both base64 and quoted-printable encodings.

I suspect there might be an issue with how FreeScout processes this combination of encodings. The IMAP server is configured correctly, and other emails display without issues.

Thank you for your help!

<img width="866" alt="394892226-6e6e3d53-4893-4214-b1e8-bac10704d990" src="https://github.com/user-attachments/assets/d0d12dee-4cd4-4ae7-9f4e-dcbc23e670a8" />

**Comment by freescout-help** [comment]
Can you share the EML file of the email or send it to support@freescout.net

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
