### ISSUE TITLE
Support to listen on multiple URLs behind reverse proxy

### ISSUE THREAD

**Issue by jozefrebjak** [freescout-help-desk/freescout#4418]
PHP version: PHP 8.2.20
FreeScout version: 1.8.154
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

If `SITE_URL` is set to `support.example1.com`, then requests from `support.example2.com` are redirected to `support.example1.com`. This is confusing for users because a user who is a member of example1.com doesn't need to see example2.com in the URL and vice versa.

### Expected Behavior

Requests from `support.example2.com` should not be redirected to `support.example1.com`. Each domain should maintain its own URL in the browser.

### Actual Behavior

Requests from `support.example2.com` are redirected to `support.example1.com`, causing confusion for users.

### Steps to Reproduce

1. Set up Traefik reverse proxy to listen on multiple hosts:
    ```
    Host(`support.example1.com`,`support.example2.com`)
    ```
2. Set `SITE_URL` to `support.example1.com`.
3. Access the app using `support.example2.com`.

**Comment by freescout-help** [comment]
Unfortunately there is no plans to implement this. Maybe someone else would wish to implement this.
