### ISSUE TITLE
Error deleting a mailbox

### ISSUE THREAD

**Issue by jordiponsp** [freescout-help-desk/freescout#4419]
Hi,

When I try to delete a mailbox, it returns the following connection error:

Error occured. Please check your internet connection and try again.

In the records of the app in freescout i see the following error:

``
Allowed memory size of 2147483648 bytes exhausted (tried to allocate 134217736 bytes) {"userId":X,"email":"user@domain","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Allowed memory size of 2147483648 bytes exhausted (tried to allocate 134217736 bytes) at /opt/freescout/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:262)
[stacktrace]
#0 {main}
"}
``

In php errors:

``
2024/12/11 16:15:46 [error] 1068246#1068246: *6250 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 134217736 bytes) in /opt/freescout/overrides/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 262" while reading response header from upstream, client: <IP>, server: server.domain, request: "POST /mailbox/ajax HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "server.domain", referrer: "https://server.domain/mailbox/settings/13"
``
I have tried to increase php memory but the error continues.

Thank you for your time,

PHP version: 8.3.10
FreeScout version: 1.8.157
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: No

**Comment by mywebhero** [comment]
It looks like your server is running out of memory while executing the scripts. This could be due to a large mailbox that’s taking longer to delete. Try increasing your memory limit to see if that resolves the issue.
