### ISSUE TITLE
Not everyone on Freescout how to deal with that ? 

### ISSUE THREAD

**Issue by McRosbeef** [freescout-help-desk/freescout#4420]
In my company, some users work with the Outlook
desktop client (using 0365 licenses) because our
ERP automatically opens Outlook with a pre-filled
email and a PDF attachment, allowing them to send
it directly to the client.

The issue is that I don't see these outgoing emails,
sent via Outlook, appearing in FreeScout. Is there a
way to have these emails show up in FreeScout, so I
can potentially use a workflow rule to close the
conversation once they're sent?

Thanks in advance for any guidance!

**Comment by freescout-help** [comment]
Unfortunately not.

**Comment by ilyakonovalenko** [comment]
It seems the solution is to write some script to grab sent emails from mail server and create conversations in FreeScout. This can be done with API. Another solution is to send emails from FreeScout (directly or via API) which is probably the most reliable solution.
