### ISSUE TITLE
Selfhosted fresh install - email from header decoding problem

### ISSUE THREAD

**Issue by GrayHoax** [freescout-help-desk/freescout#4421]
I have installed a fresh installation with migration from a dockerized install. On the hosting server, whose configuration uses nginx (for static serving) and Apache mod_php (8.3), I restored a MySQL dump from the dockerized installation.

When FreeScout receives a new message from a non-existent customer, it does not normally import the customer's name. The customer profile looks fine, but the name is UTF-encoded, like this: =?UTF-8?B?SXZhbg==?=. I have checked the collation in the customers table, and it is utf8mb4_unicode_ci. I have checked MySQL migrations - 'Nothing to migrate.'

In my case, I think mb_decode_mimeheader is not working correctly. Please help me find a solution.

PHP version: 8.3
FreeScout version: 1.8.159
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: Not yet

**Comment by freescout-help** [comment]
Can you share the EML file of the email or send it to support@freescout.net

**Comment by GrayHoax** [comment]
Thanks for quick reaction!
Message sent.

**Comment by freescout-help** [comment]
Sender's name looks fine:
![2024-12-13_20-28-47](https://github.com/user-attachments/assets/6fb3d289-4ad9-46c0-9bbc-3d99bc1c340f)

Try to check the EML on your server: https://github.com/freescout-help-desk/freescout/wiki/Fetching-Emails#checking-eml-file

**Comment by GrayHoax** [comment]
Interesting...
When I try to eval php code from cli, like `php -r 'echo mb_decode_mimeheader("=?UTF-8?B?SXZhbg==?=");'` php returns successed result.

**Comment by freescout-help** [comment]
Do you have `imap` extension enabled in your console php?

Try to debug this function: https://github.com/freescout-help-desk/freescout/blob/dist/overrides/webklex/php-imap/src/Header.php#L651

https://github.com/freescout-help-desk/freescout/wiki/Debugging

**Comment by GrayHoax** [comment]
OMG!
Thats it! My CRON job is processing with default interpreter, which have no imap ext. It installed only for php-fpm module.

Thanks a lot!
