### ISSUE TITLE
Contact form - Get site URL

### ISSUE THREAD

**Issue by ScottChampagne** [freescout-help-desk/freescout#4422]
When a ticket is submitted via the contact form widget, is there a way to capture what website page the user was on when the form was submitted?

This was one thing that the helpscout beacon did well and was rather valuable.  For example;
<img width="989" alt="image" src="https://github.com/user-attachments/assets/d1d9e55e-72da-4c03-aa05-a8fa578d1e8d" />
Capturing the location information is also nice, but the location on the website is more valuable at this time.

PHP version: php8.3-1.17.96
FreeScout version: [1.8.159]
Database: MySQL / PostgreSQL
Are you using CloudFlare:  No
Are you using non-official modules:  No

**Comment by freescout-help** [comment]
There is no such feature for now.  Feel free to [submit a feature request](https://freescout.net/request-feature/).
