### ISSUE TITLE
Convert chat conversation into email conversation

### ISSUE THREAD

**Issue by AkronGit** [freescout-help-desk/freescout#4423]
Is it possible to switch chat conversation into mail conversation and avoid opening new conversation in the process?

**Comment by freescout-help** [comment]
Unfortunately not for now.

**Comment by ruess** [comment]
This would be a really nice feature, as we sometimes accidentally miss chats and it would be so great to be able to click a button and just reply to a summary of all their chats with an email instead of recreating a new one and copying and pasting their chat history.

Thanks!
