### ISSUE TITLE
Keyboard Shortcut Module - Command-Enter Not working on Mac

### ISSUE THREAD

**Issue by ScottChampagne** [freescout-help-desk/freescout#4425]
Keyboard Shortcut Module is installed.

On a macbook, command-enter is not working to send the message.  I have tried on Firefox and Chrome.

PHP version: 8.3.14
FreeScout version:  1.8.159
Database: PostgreSQL
Are you using CloudFlare: No
Are you using non-official modules:  No

**Comment by freescout-help** [comment]
The issue has been fixed in Keyboard Shortcuts Module v1.0.10. Please check it.

**Comment by ScottChampagne** [comment]
Updated the module and tested in both browsers.

Nothing doing. 

Other keystrokes work just fine.  (Reply, Delete, status, etc.)

**Comment by freescout-help** [comment]
Try to open this https://jsfiddle.net/4h1d3cou/. Place the cursor inside the textarea, press COMMAND+ENTER and send us the text shown below the textarea.

**Comment by ScottChampagne** [comment]
`altKey: false, ctrlKey: false, shiftKey: false, metaKey: true, key: 13`

**Comment by freescout-help** [comment]
The only possible reason is that module's JavaScript is still cached by browsers. Try to clear browsers cache and clear FreeScout cache in Manage > Tools.

If still no luck, someone will need to debug `ksBind()` function in module's `/Public/js/module.js` on your Mac.

**Comment by simonnelli** [comment]
I have the same problem. Output is the same:
altKey: false, ctrlKey: false, shiftKey: false, metaKey: true, key: 13

Tried clearing the cache, tried Safari, Firefox, Chrome, tried different keyboard layouts (CH and US).

**Comment by simonnelli** [comment]
Just noticed: It works in Chrome and Firefox by hitting CTRL+ENTER (not CMD), in Safari nothing happens with CMD nor CTRL

**Comment by freescout-help** [comment]
Try to change line 195 in `/Modules/KeyboardShortcuts/Public/js/module.js` to the following:

> console.log('altKey: '+e.altKey+', ctrlKey: '+e.ctrlKey+', shiftKey: '+e.shiftKey+', metaKey: '+e.metaKey+', key: '+e.which);

After that clear FreeScout cache, browser cache. Open browser console, click COMMAND+ENTER and send the screenshot of what you'll have in the browser console.

**Comment by ScottChampagne** [comment]
Control-Enter is what is currently sending.

Added that text to module.js, cleared FreeScout Cache and the Browser Cache.

I don't see any activity in the browser console when I hit command-enter.

Control-Enter generates:
`14:55:15.340
XHRGET
https://contile.services.mozilla.com/v1/tiles
[HTTP/3 200  142ms]

14:55:15.341
XHRPOST
https://spocs.getpocket.com/spocs
[HTTP/3 200  230ms]

14:55:15.342
XHRPOST
https://merino.services.mozilla.com/api/v1/curated-recommendations
[HTTP/3 200  129ms]
`

**Comment by freescout-help** [comment]
Try this fiddle https://jsfiddle.net/3wy5j026/1/ and send the debug output you will get when pressing CMD+ENTER.

**Comment by jonalange** [comment]
Still an issue
The latest fiddle linked gives: 

CMD+ENTER (how it should be on mac):
```
DEBUG:
metaKey=false, ctrlKey=false
```

CTRL+ENTER (how it should not be on mac and feels like "windows style keyboard"):
```
DEBUG:
metaKey=false, ctrlKey=true
run callback
DEBUG:
metaKey=false, ctrlKey=false
```
But CTRL+ENTER does different things in the fiddle (different output depending on how long I hold each button)

**Comment by jonalange** [comment]
> Try to change line 195 in `/Modules/KeyboardShortcuts/Public/js/module.js` to the following:

Using chrome:
This will output:
CMD+ENTER:
```
altKey: false, ctrlKey: false, shiftKey: false, metaKey: false, key: 93
```

CTRL+ENTER:
```
altKey: false, ctrlKey: true, shiftKey: false, metaKey: false, key: 13
altKey: false, ctrlKey: false, shiftKey: false, metaKey: false, key: 17
```

Playing around with this in freescout:
Key 93: Right Command
Key 91: Left Command
Key 17: Left/ right control (no difference which one is pressed)


I changed the logging a bit:
```
$(document).on('keydown keyup', function(e) {
		const ev = e.originalEvent || e;
		console.log(e.type, {
			key: ev.key,
			code: ev.code,
			which: e.which,
			ctrlKey: ev.ctrlKey,
			metaKey: ev.metaKey,
			altKey: ev.altKey,
			shiftKey: ev.shiftKey,
			repeat: ev.repeat
		});
	});
```

Gives:
Right Command:
```
keydown {key: 'Meta', code: 'MetaRight', which: 93, ctrlKey: false, metaKey: true, …}
keydown {key: 'Enter', code: 'Enter', which: 13, ctrlKey: false, metaKey: true, …}
altKey: false, ctrlKey: false, shiftKey: false, metaKey: false, key: 93
keyup {key: 'Meta', code: 'MetaRight', which: 93, ctrlKey: false, metaKey: false, …}
```
Left Command:
```
keydown {key: 'Meta', code: 'MetaLeft', which: 91, ctrlKey: false, metaKey: true, …}
keydown {key: 'Enter', code: 'Enter', which: 13, ctrlKey: false, metaKey: true, …}
altKey: false, ctrlKey: false, shiftKey: false, metaKey: false, key: 91
keyup {key: 'Meta', code: 'MetaLeft', which: 91, ctrlKey: false, metaKey: false, …}
```

Could the issue be that it's not just "meta key" but rather "MetaLeft" and "MetaRight"? Just a guess

**Comment by mchuc** [comment]
I'm sorry, but is it not possible to add your own settings for this function, because for example I would like to have F1, F2, etc. assigned, because these keys on the keyboard are wasted... or my own shortcuts, the ones you provided in Polish are not intuitive...
