### ISSUE TITLE
Extended editor - borders to a table after save

### ISSUE THREAD

**Issue by shax-xxx** [freescout-help-desk/freescout#4429]
PHP version: 
FreeScout version: 1.8.159
Database: MySQL
Are you using CloudFlare:  No
Are you using non-official modules: No

Hello.
Extended editor add tables to replies

If you add a table in edit mode it has borders and looks like this:

![table_with_borders](https://github.com/user-attachments/assets/597d6701-430b-4032-af3b-2daba66e0cd7)

But after saving it turns into a table without borders:
![table_without_borders](https://github.com/user-attachments/assets/f45ca2ab-42f9-4d9f-b1c9-95ab5eeff1f9)

Is there any possibility to keep the view with borders?

**Comment by freescout-help** [comment]
Fixed in the `master` branch and will be published in the next release.
