### ISSUE TITLE
Reply to closed conversation

### ISSUE THREAD

**Issue by adam3278** [freescout-help-desk/freescout#4433]
Hi,
When we reply to conversation with closed status, it doesn't update the last activity date in conversations list. Is it proper behavior? How to fix it? Thanks in advance.

**Comment by freescout-help** [comment]
What do you mean under "last activity date"?

**Comment by adam3278** [comment]
This
![last activity date](https://github.com/user-attachments/assets/65b5bba1-17da-4139-9353-730f0d715257)

**Comment by freescout-help** [comment]
This is not the "Last activity date":

![2024-12-22_08-23-30](https://github.com/user-attachments/assets/ca150f1a-9f2b-4a9e-a552-c9fdb1fc5dba)
