### ISSUE TITLE
Multiple new tabs in browser

### ISSUE THREAD

**Issue by adam3278** [freescout-help-desk/freescout#4435]
Hello,
We're facing a serious problem when operating the freescout app. We're using the "Tags" module and when we click the one of the tags attached to conversation, the new tab appears in browser. The same applies to some other buttons in application. At the middle of the day, there can be about 100 tabs open and no-one can operate it. Yes, our workers can simply close them, but they don't do it automatically. So, how to disable target _blank from elements with onclick JS action? Thanks for help.

**Comment by adam3278** [comment]
Can you change it in your module or it’s planned behavior? It’s really annoying.

**Comment by freescout-help** [comment]
Unfortunately there is no plans to change it.
