### ISSUE TITLE
Split the conversation

### ISSUE THREAD

**Issue by adam3278** [freescout-help-desk/freescout#4436]
Hi,
How can we split the conversation into smaller ones? I see, there is a information we cannot un-join the conversation threads, but there is a question: can we duplicate the whole conversation and then remove the unwanted messages in database without breaking everything? Some of the new workers sometimes don't create new conversations. They're changing the topic and mails with clients without any regrets. Then, I had to clean this mess up, so how to do it? Thanks!

**Comment by freescout-help** [comment]
> can we duplicate the whole conversation and then remove the unwanted messages in database without breaking everything?

It may cause problems with joining incoming emails into those conversations.

**Comment by adam3278** [comment]
Ok, what about changing id of both separated conversations? I would be able to join new messages to them later. It’s better than nothing.

**Comment by freescout-help** [comment]
It's not clear what you are suggesting.
