### ISSUE TITLE
List conversations API by subject just get exact subjects

### ISSUE THREAD

**Issue by afecte** [freescout-help-desk/freescout#4450]
The API documentation says "Look up conversations containing a text in the subject." but I'm making test and I only get conversations with exact same subject. If I try with words contained in the subject, I don't get those conversations.

For example, if there is a conversation with a subject "test", I get that result using subject=test but not using subject=tes

I tried in https://demo.freescout.net/ and I get the same problem.

**Comment by freescout-help** [comment]
Fixed in API & Webhooks Module v1.0.83
